<div class="panel panel-primary">
	<div class="panel-heading">
		<h3 class="panel-title">Créer devis / facture</h3>
	</div>
	<div class="panel-body">

		<?php echo $this->form ?>
	</div>
</div>

<?php if($this->id_devis): ?>
	<div class="panel panel-primary">
		<div class="panel-heading">
			<h3 class="panel-title">Ajouter / modifier item</h3>
		</div>
		<div class="panel-body">
			<div class="table-responvive">
				<table class="table">
					<thead>
						<tr>
							<th>#</th>
							<th>D&eacute;signation</th>
							<th>P.U.</th>
							<th>Quantit&eacute;</th>
							<th>Remise (%)</th>
							<th>P.H.T.</th>
							<th></th>
						</tr>
					</thead>
					<tbody>
						<tr>
							<td>
								<?php echo $this->formItemDevis->getElement('id_devis'); ?>
								<?php echo $this->formItemDevis->getElement('id_item'); ?>
							</td>
							<td>
								<?php echo $this->formItemDevis->getElement('designation'); ?>
							</td>
							<td>
								<?php echo $this->formItemDevis->getElement('pu'); ?>
							</td>
							<td>
								<?php echo $this->formItemDevis->getElement('qte'); ?>
							</td>
							<td>
								<?php echo $this->formItemDevis->getElement('remise'); ?>
							</td>
							<td>
								<?php echo $this->formItemDevis->getElement('pht'); ?>
							</td>
							<td>
								<?php echo $this->formItemDevis->getElement('ajouter'); ?>
							</td>
						</tr>
					</tbody>

				</table>
			</div>
		</div>
	</div>
	<div class="panel panel-primary">
		<div class="panel-heading">
			<h3 class="panel-title">Elements du devis / facture</h3>
		</div>
		<div class="panel-body">
			<div class="table-responvive">
				<table class="table">
					<thead>
						<tr>
							<th>#</th>
							<th>D&eacute;signation</th>
							<th>P.U.</th>
							<th>Quantit&eacute;</th>
							<th>Remise (%)</th>
							<th>P.H.T.</th>
							<th></th>
						</tr>
					</thead>
					<tbody id="liste_items_devis"></tbody>
					<tfoot>
						<tr>
							<td></td>
							<td colspan="4" style="text-align: right;font-weight: bold;">TOTAL .H.T.</td>
							<td></td>
							<td></td>
						</tr>
					</tfoot>
				</table>
			</div>
		</div>
	</div>
	<div class="panel panel-primary">
		<div class="panel-heading">
			<h3 class="panel-title">R&eacute;daction du devis</h3>
		</div>
		<div class="panel-body">
			<button type="button" class="btn btn-success pull-right" aria-label="Left Align" id="preview_<?php $this->id_devis?>">
			  	<span class="glyphicon glyphicon-eye-open" aria-hidden="false">&nbsp;Aperçu avant impression</span>
			</button><br /><br />
			<?php echo $this->formRedaction->getElement('redactionDevis') ?>
			<?php echo $this->formRedaction->getElement('validerRedactionDevis') ?>

		</div>
	</div>
<?php endif; ?>