<div class="row-fluid">
	<div class="col-lg-12">
		<div class="panel panel-primary">
			<div class="panel-heading">
				<h3 class="panel-title">Devis en attente de signature</h3>
			</div>
			<div class="panel-body">
				<div class="table-responvive">
					<table class="table table-hover table-condensed tablesorter" id="sorter">
						<thead>
							<tr>
								<th>Dossier</th>
								<th>Cr&eacute;ation</th>
								<th>Validit&eacute;</th>
								<th>Titre</th>
								<th>Client</th>
								<th></th>
							</tr>
							<tr>
								<td>
									<?php echo $this->filtre->getElement('id_client')?>
									<?php echo $this->filtre->getElement('id_projet')?>
									<?php echo $this->filtre->getElement('valide')?>
									<?php echo $this->filtre->getElement('type_filtre')?>
								</td>
								<td colspan="2">
									<div class="row">
										<div class="col-xs-6">
											<?php echo $this->filtre->getElement('mois')?>
										</div>
										<div class="col-xs-6">
											<?php echo $this->filtre->getElement('annee')?>
										</div>
									</div>
									
								</td>
<!-- 								<th></th> -->
								<td><?php echo $this->filtre->getElement('projet')?></td>
								<td><?php echo $this->filtre->getElement('client')?></td>
								<td style="text-align: right;">
									<?php echo $this->filtre->getElement('rechercher')?><?php echo $this->filtre->getElement('resetClient')?>
								</td>
							</tr>
						</thead>
						<tbody id="listeFactures">
							<?php foreach($this->paginator as $dev): ?>
								<tr id="devis_<?php echo $dev->id ?>" style="display: table; width:100%;">
									<td>
										<?php echo $dev->ref ?>
									</td>
									<td><?php echo date('d/m/Y', strtotime($dev->date)) ?></td>
									<td>
										<span style="color:<?php echo $this->GetFlagDate($dev->date_validite) ?>">&#x25A3;</span> &nbsp;&nbsp;
										<?php echo date('d/m/Y', strtotime($dev->date_validite)) ?>
									</td>
									<td><?php echo $dev->titre ?></td>
									<td><?php echo $this->GetClientById($dev->id_client) ?></td>
									<td style="text-align: right;">
										<button type="button" class="btn btn-success" aria-label="Left Align" id="valid_devis_<?php echo $dev->id ?>">
										  <span class="glyphicon glyphicon-check" aria-hidden="true"></span>
										</button>
										<button type="button" class="btn btn-primary" aria-label="Left Align" id="fiche_facturation_<?php echo $dev->id ?>">
										  <span class="glyphicon glyphicon-eye-open" aria-hidden="true"></span>
										</button>
										<button type="button" class="btn btn-warning" aria-label="Left Align" id="edit_facturation_<?php echo $dev->id ?>">
										  <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>
										</button>
									</td>
								</tr>
							<?php endforeach; ?>
						</tbody>
						<tfoot>
							<tr>
								<td colspan="6">
									<?php echo $this->paginationControl($this->paginator); ?>
								</td>
							</tr>
						</tfoot>
					</table>
				</div>
			</div>
		</div>
	</div>
</div>
