<?php $nbArtices = count($this->articles) + 1; ?>
<div class="container">
	<div class="row">
		<div class="col-xs-5">
			<div style="text-align: center;">
				<img src="<?php echo $this->baseUrl('/images/MarneEnseignes.png')?>" />
			</div>
			<p style="text-align: center; margin-top: 10px; font-size: 10px;">
				Z.I.S.E. Rue Maurice Hollande BP 362<br />
				51689 REIMS CEDEX 02
			</p>
			<p style="text-align: center; margin-top: 10px; font-weight: bold; font-size: 10px;">
				Tél : 03 26 82 52 95<br />
				Fax : 03 26 05 02 49<br />
				marneenseigne@wanadoo.fr
			</p>
			<p style="text-align: center; margin-top: 10px; font-size: 10px;">
				Siret : 43204005100017<br />
				Sarl au capital de 7622 &euro;
				<br /><br />
				TVA INTRACOMMUNAUTAIRE : FR 84 432 040 061
			</p>
		</div>
		<div class="col-xs-7">
			<div class="row">
				<div class="col-xs-7">
					<div class="panel panel-default">
<!-- 						<div class="panel-body" style="height:60px;"> -->
							<p style="text-align: center;">
								Devis numéro <span style="font-weight: bold;"><?= $this->devis->num_devis ?></span>
							</p>
							<p style="text-align: center;">Reims le <span style="font-weight: bold;"><?php echo date('d/m/Y', strtotime($this->devis->date))?></span></p>
<!-- 						</div> -->
					</div>
				</div>
				<div class="col-xs-5">
					<div class="panel panel-default">
<!-- 						<div class="panel-body"> -->
							<p style="text-align: center;">REF CLIENT</p>
							<p style="text-align: center;"><span style="font-weight: bold;"><?php echo sprintf('%05d', $this->client->ref) ?></span></p>
<!-- 						</div> -->
					</div>
				</div>
			</div>
			<div class="row">
				<div class="col-xs-12">
					<h5><?php echo $this->client->societe ?></h5>
					<p style="font-size: 11px;"><?php echo $this->client->adresse ?></p>
					<p style="font-size: 11px;">
						<?php echo $this->client->codepostal?> <span style="text-transform: uppercase;"><?php echo $this->client->ville ?></span>
					</p>
				</div>
			</div>
			<div class="row">
				<div class="col-xs-12">
					<?php if ($this->devis->ref != null) :?>
						<p style="font-size: 10px; font-weight: bold;">Référence projet n° <?php echo $this->devis->ref ?></p>
					<?php endif; ?>
				</div>
			</div>
		</div>
	</div>
	<div class="row"> <!-- style="page-break-after: always;" -->
		<div class="col-xs-12">
			<div class="panel panel-default">
				<table class="table table-bordered" style="font-size:11px;">
					<thead>
						<tr>
							<th style="width:63%;">DESIGNATION</th>
							<th style="width:5%;">QTE</th>
							<th style="width:16%;">P.U. HT</th>
							<th style="width:16%;">MONTANT HT</th>
						</tr>
					</thead>
					<?php $totalHt = $this->GetSum($this->devis->id) ?>
					<tbody>
						<tr>
							<td style="height:<?= 435 / ($nbArtices) ?> px;">
								<?php echo $this->devis->redaction ?>
							</td>
							<td style="text-align:center; vertical-align: bottom;">
								1
							</td>
							<td style="text-align:right; vertical-align: bottom;">
								<?php echo $totalHt ?>
							</td>
							<td style="text-align:right; vertical-align: bottom;">
								<?php echo  $totalHt ?>
							</td>
						</tr>
                        <?php foreach($this->articles as $article):?>
                            <?php $json = json_decode(preg_replace("/\r\n|\r|\n/",'<br/>',$article->json), true) ?>
                            <tr>
                                <td>
                                    <?php echo $json['itemredaction'] ?>
                                </td>
                                <td style="text-align:center; vertical-align: bottom;">
                                    <?php echo $json['qte'] ?>
                                </td>
                                <td style="text-align:right; vertical-align: bottom;">
                                    <?php echo $json['pxvente'] ?>
                                </td>
                                <td style="text-align:right; vertical-align: bottom;">
                                    <?php echo $json['pxvente'] ?>
                                </td>
                            </tr>
                        <?php endforeach; ?>
					</tbody>
				</table>
			</div>
		</div>
	</div>
	<div class="row">
		<div class="col-xs-7">
			<div class="row">
				<div class="col-xs-12">
					<div class="panel panel-default">
						<p style="font-size: 10px; line-height: 40px; margin: 0px; padding-left: 10px;">
							DELAI DE REALISATION&nbsp;&nbsp;&nbsp;&nbsp;
							<span style="font-weight:bold;"><?php echo $this->devis->delai ?></span>
						</p>
					</div>
				</div>
			</div>
			<div class="row">
				<div class="col-xs-12">
					<div class="panel panel-default">
						<p style="font-size: 10px; line-height: 40px; margin: 0px; padding-left: 10px;">MODE DE REGLEMENT
							<span style="font-weight:bold;text-transform: uppercase;"><?php echo $this->devis->reglement ?></span>
						</p>
					</div>
				</div>
			</div>
		</div>
		<div class="col-xs-5">
			<div class="panel panel-default" style="height:104px;">
				<p style="font-size: 10px; line-height: 40px; margin: 0px; padding-left: 10px;">BON POUR ACCORD, SIGNATURE</p>
			</div>
		</div>
	</div>
	<div class="row">
		<div class="col-xs-12">
			<div class="panel panel-default">
				<table class="table table-bordered">
					<thead>
						<tr>
							<th style="font-size: 10px;text-align: center;">BASES HT</th>
							<th style="font-size: 10px;text-align: center;">TAUX REMISE</th>
							<th style="font-size: 10px;text-align: center;">MONTANT HT APRES REMISE</th>
							<th style="font-size: 10px;text-align: center;">TAUX TVA</th>
							<th style="font-size: 10px;text-align: center;">MONTANT TVA</th>
							<th style="font-size: 10px;text-align: center;">TOTAL TTC</th>
						</tr>
					</thead>
					<?php $remise = $this->devis->remise;?>
					<?php $montantTVA = sprintf('%0.2f', $totalHt * 0.2) ?>
					<tbody>
						<tr>
							<td style="font-size: 12px; font-weight: bold; text-align: center;">
								<?php echo $totalHt?> &euro;
							</td>
							<td style="font-size: 12px; font-weight: bold; text-align: center;">
								<?php echo sprintf('%0.2f', $remise) ?> %
							</td>
							<td style="font-size: 12px; font-weight: bold; text-align: center;">
								<?php echo sprintf('%0.2f', $totalHt - ($totalHt * ($remise / 100)))?> &euro;
							</td>
							<td style="font-size: 12px; font-weight: bold; text-align: center;">
								20.00 %
							</td>
							<td style="font-size: 12px; font-weight: bold; text-align: center;">
								<?php echo sprintf('%0.2f', $montantTVA) ?> &euro;
							</td>
							<td style="font-size: 14px; font-weight: bold; text-align: center;">
								<?php echo sprintf('%0.2f', $totalHt + $montantTVA) ?> &euro;
							</td>
						</tr>
					</tbody>
				</table>
			</div>
		</div>
	</div>
	<p style="text-align: center; font-size: 8px;">
		Clauses de propriété : La marchandise reste notre propriété jusqu'au paiement intégral de la facture correspondante - Loi du 12/05/1980
	</p>
</div>