<script>
    document.addEventListener('DOMContentLoaded', function() {
        if (localStorage.getItem('currentLine')){
            $('#' + localStorage.getItem('currentLine')).css('border', '3px solid orange');
            $('#' + localStorage.getItem('currentLine'))[0].scrollIntoView(true);
        }

    }, false);

    document.onkeydown = checkKey;

    function checkKey(e) {

        e = e || window.event;

        if (e.keyCode == '38') {
            var current = $('#' + localStorage.getItem('currentLine'));
            $('#' + localStorage.getItem('currentLine')).css('border', 'none');

            localStorage.setItem('currentLine', '');
            current.prev().css('border', '3px solid orange');
            localStorage.setItem('currentLine', current.prev().attr('id'));
        }

        if (e.keyCode == '40') {
            var current = $('#' + localStorage.getItem('currentLine'));
            $('#' + localStorage.getItem('currentLine')).css('border', 'none');

            localStorage.setItem('currentLine', '');
            current.next().css('border', '3px solid orange');
            localStorage.setItem('currentLine', current.next().attr('id'));
        }
    }
</script>
<style>
    thead, tbody { display: block;}

    tbody {
        height: calc(100vh - 450px);
        overflow-y: auto;
        overflow-x: hidden;
    }
</style>

<div class="panel panel-primary">
    <div class="panel-heading">
        <h3 class="panel-title">Liste des articles</h3>
    </div>
    <div class="panel-body">
        <div class="table-responvive">
            <form name="formFiltre" method="post">
                <table class="table table-hover table-condensed tablesorter" id="sorter">
                    <thead style="display: table; width:100%;">
                    <tr style="display: inline-table;width: 100%;">
                        <th width="10%">Code</th>
                        <th width="80%">Libelle</th>
                        <th>&nbsp;</th>
                    </tr>
                    <tr style="display: inline-table;width: 100%;">
                        <td width="10%">
                            <?= $this->filtre->getElement('code')?>
                        </td>
                        <td width="80%">
                            <?= $this->filtre->getElement('libelle')?>
                        </td>
                        <td>
                            <?= $this->filtre->getElement('rechercher')?>
                            <?= $this->filtre->getElement('resetFiltreArticle')?>
                        </td>
                    </tr>
                    </thead>
                    <tbody id="listeFactures">
                    <?php foreach($this->paginator as $article): ?>
                        <tr id="devis_<?= $article->id ?>" style="display: inline-table;width: 100%;">
                            <td width="10%">
                                <?= $article->code ?>
                            </td>
                            <td width="80%">
                                <?=
                                    preg_replace("/\r\n|\r|\n/",'<br/>',$article->libelle)
                                ?>
                            </td>
                            <td width="10%">
                                <button type="button" class="btn btn-warning" aria-label="Left Align" id="edit_article_<?= $article->id ?>">
                                    <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>
                                </button>
                                <button type="button" class="btn btn-danger" aria-label="Left Align" id="delete_article_<?= $article->id ?>">
                                    <span class="glyphicon glyphicon-trash" aria-hidden="true"></span>
                                </button>
                            </td>
                        </tr>
                    <?php endforeach; ?>
                    </tbody>
                    <tfoot>
                    <tr>
                        <td colspan="3">
                            <?= $this->paginationControl($this->paginator); ?>
                        </td>
                    </tr>
                    </tfoot>
                </table>
            </form>
        </div>
    </div>
</div>

