<div class="panel panel-primary">
    <div class="panel-heading nav navbar-default">
        <div class="row">
            <div class="col-md-6">
                <h3 class="panel-title">Editer un devis</h3>
            </div>
            <?= $this->render('devis/partNavBarHeader.phtml') ?>
        </div>
    </div>
	<div class="panel-body">
        <?= $this->render('devis/partBodyDevis.phtml') ?>
	</div>
</div>

<div id="dialog_nom_modele">
    <?php echo $this->formNomModele ?>
</div>

<div id="liste_catalogue">
    <div style="float: right; margin-bottom: 15px;">
        <button type="button" class="btn btn-success btn-xs" aria-label="Left Align" id="close_catalogue">
            <span class="glyphicon glyphicon-remove-circle" aria-hidden="true"></span>
        </button>
    </div>
    <div class="table-responvive">
        <table class="table table-hover table-condensed tablesorter" id="sorter">
            <thead>
            <tr>
                <th style="width:10%">
                    Référence ME
                </th>
                <th>Fournisseur</th>
                <th>Type</th>
                <th style="width:8%">Epaisseur</th>
                <th style="width:10%">Format</th>
                <th style="width:35%">D&eacute;signation</th>
                <th style="width:6%">P.U.</th>
                <th>Unité</th>
                <th>Coef</th>
                <th></th>
            </tr>
            <tr>
                <td>
                    <?php echo $this->filtreForm->getElement('reference') ?>
                </td>
                <td>
                    <?php echo $this->filtreForm->getElement('fournisseur') ?>
                </td>
                <td><?php echo $this->filtreForm->getElement('type') ?></td>
                <td><?php echo $this->filtreForm->getElement('epaisseur') ?></td>
                <td></td>
                <td>
                    <?php echo $this->filtreForm->getElement('produit') ?>
                </td>
                <td colspan="4" style="text-align:right;">
                    <img src="/images/load.gif" alt="loader" id="loader"/>
                    <?php echo $this->filtreForm->getElement('rechercher') ?>
                    <?php echo $this->filtreForm->getElement('resetCatalogue') ?>
                </td>
            </tr>
            </thead>
            <tbody id="liste_produits">
            <?php foreach($this->catalogues as $catalogue):?>
                <tr>
                    <td><?php echo $catalogue->code_me?></td>
                    <td><?php echo $catalogue->fournisseur?></td>
                    <td><?php echo $catalogue->type?></td>
                    <td><?php echo $catalogue->epaisseur?></td>
                    <td><?php echo $catalogue->format?></td>
                    <td><?php echo $catalogue->designation ?></td>
                    <td style="text-align:right;">
                        <?php if(!(int) $catalogue->unitaire):?>
                            <?php if($catalogue->prixM2 == null):?>
                                <?php echo $catalogue->prixML ?>
                            <?php else:?>
                                <?php echo $catalogue->prixM2 ?>
                            <?php endif;?>
                        <?php else:?>
                            <?php echo $catalogue->unitaire ?>
                        <?php endif;?>
                        &nbsp;&euro;
                    </td>
                    <td style="text-align:center;">
                        <?php if(!(int) $catalogue->unitaire):?>
                            <?php if($catalogue->prixM2 == null):?>
                                Ml
                            <?php else:?>
                                M2
                            <?php endif;?>
                        <?php else:?>
                            Unitaire
                        <?php endif;?>
                    </td>
                    <td style="text-align:right;"><?php echo $catalogue->coeff_marge?></td>
                    <td style="text-align:right;">
                        <button type="button" class="btn btn-warning" aria-label="Left Align" id="fill_form_<?php echo $catalogue->id_produit ?>">
                            <span class="glyphicon glyphicon-arrow-right" aria-hidden="true"></span>
                        </button>
                    </td>
                </tr>
            <?php endforeach; ?>
            </tbody>
        </table>
    </div>
</div>