<div class="panel panel-primary">
	<div class="panel-heading">
		<h3 class="panel-title">Fiche devis</h3>
	</div>
	<div class="panel-body">

        <div id="tabs">
            <ul>
                <li><a href="#tabs-1">Informations</a></li>
                <li><a href="#tabs-2">Historique</a></li>
            </ul>
            <div id="tabs-1">
                <div class="table-responvive">
                    <table class="table">
                        <thead>
                        <tr>
                            <th>Infos</th>
                            <th>Tarifs</th>
                        </tr>
                        </thead>
                        <tbody>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
	</div>
</div>
