<div class="row-fluid">
    <div class="col-lg-12">
        <div class="panel panel-primary">
            <div class="panel-heading">
                <h3 class="panel-title">Historique des devis</h3>
            </div>
            <div class="panel-body">
                <div class="table-responvive">
                    <table class="table table-hover table-condensed tablesorter" id="sorter">
                        <thead style="display: contents; width:100%;">
                        <tr style="display: table-row;width: 100%;">
                            <th width="10%">Dossier</th>
                            <th width="10%">Cr&eacute;ation</th>
                            <th width="10%">Validit&eacute;</th>
                            <th width="50%">Titre</th>
                            <th width="10%">Client</th>
                            <th width="10%"></th>
                        </tr>
                        <tr style="display: table-row;width: 100%;">
                            <td width="10%">
                                <?= $this->filtre->getElement('id_client')?>
                                <?= $this->filtre->getElement('id_projet')?>
                                <?= $this->filtre->getElement('valide')?>
                                <?= $this->filtre->getElement('type_filtre')?>
                            </td>
                            <td width="10%" >
                                <div class="row">
                                    <div class="col-xs-6">
                                        <?= $this->filtre->getElement('mois')?>
                                    </div>
                                    <div class="col-xs-6">
                                        <?= $this->filtre->getElement('annee')?>
                                    </div>
                                </div>

                            </td>
                            <td width="10%" ></td>
                            <!-- 								<th></th> -->
                            <td width="50%"><?= $this->filtre->getElement('projet')?></td>
                            <td width="10%"><?= $this->filtre->getElement('client')?></td>
                            <td width="10%" style="text-align: right;">
                                <?= $this->filtre->getElement('rechercher')?><?= $this->filtre->getElement('resetClient')?>
                            </td>
                        </tr>
                        </thead>
                        <tbody id="listeFactures">
                        <?php foreach($this->paginator as $dev): ?>
                            <tr id="devis_<?= $dev->id ?>" style="display: table-row; width:100%;">
                                <td width="10%">
                                    <?= $dev->ref ?>
                                </td>
                                <td width="10%"><?= date('d/m/Y', strtotime($dev->date)) ?></td>
                                <td width="10%">
                                    <span style="color:<?= $this->GetFlagDate($dev->date_validite) ?>">&#x25A3;</span> &nbsp;&nbsp;
                                    <?= date('d/m/Y', strtotime($dev->date_validite)) ?>
                                </td>
                                <td width="50%"><?= $dev->titre ?></td>
                                <td width="15%"><?= $this->GetClientById($dev->id_client) ?></td>
                                <td width="15%" style="text-align: right;">
                                    <button type="button" class="btn btn-primary" aria-label="Left Align" id="fiche_devis_<?= $dev->id ?>">
                                        <span class="glyphicon glyphicon-eye-open" aria-hidden="true"></span>
                                    </button>
                                </td>
                            </tr>
                        <?php endforeach; ?>
                        </tbody>
                        <tfoot>
                        <tr>
                            <td colspan="6">
                                <?= $this->paginationControl($this->paginator); ?>
                            </td>
                        </tr>
                        </tfoot>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
