<script>
    document.addEventListener('DOMContentLoaded', function() {
        if (localStorage.getItem('currentLine')){
            $('#' + localStorage.getItem('currentLine')).css('border', '3px solid orange');
            $('#' + localStorage.getItem('currentLine'))[0].scrollIntoView(true);
        }

    }, false);

    document.onkeydown = checkKey;

    function checkKey(e) {

        e = e || window.event;

        if (e.keyCode == '38') {
            var current = $('#' + localStorage.getItem('currentLine'));
            $('#' + localStorage.getItem('currentLine')).css('border', 'none');

            localStorage.setItem('currentLine', '');
            current.prev().css('border', '3px solid orange');
            localStorage.setItem('currentLine', current.prev().attr('id'));
        }

        if (e.keyCode == '40') {
            var current = $('#' + localStorage.getItem('currentLine'));
            $('#' + localStorage.getItem('currentLine')).css('border', 'none');

            localStorage.setItem('currentLine', '');
            current.next().css('border', '3px solid orange');
            localStorage.setItem('currentLine', current.next().attr('id'));
        }
    }
</script>
<style>
    thead, tbody { display: block;}

    tbody {
        height: calc(100vh - 450px);
        overflow-y: auto;
        overflow-x: hidden;
    }
</style>

<div class="panel panel-primary">
    <div class="panel-heading">
        <h3 class="panel-title">Devis en attente de signature</h3>
    </div>
    <div class="panel-body">
        <div class="table-responvive">
            <form name="formFiltre" method="post">
                <table class="table table-hover table-condensed tablesorter" id="sorter">
                    <thead>
                    <tr style="display: table;width: 100%;">
                        <th width="10%">Devis</th>
                        <th width="10%">Dossier</th>
                        <th width="15%">Cr&eacute;ation</th>
                        <th width="30%">Titre</th>
                        <th width="25%">Client</th>
                        <th width="10%"></th>
                    </tr>
                    <tr style="display: table;width: 100%;">
                        <td width="10%">
                            <?= $this->filtre->getElement('num_devis')?>
                        </td>
                        <td width="10%">
                            <?= $this->filtre->getElement('ref')?>
                            <?= $this->filtre->getElement('id_projet')?>
                            <?= $this->filtre->getElement('type_filtre')?>
                        </td>
                        <td width="15%">
                            <div class="row">
                                <div class="col-xs-6">
                                    <?= $this->filtre->getElement('mois')?>
                                </div>
                                <div class="col-xs-6">
                                    <?= $this->filtre->getElement('annee')?>
                                </div>
                            </div>

                        </td>
                        <td width="30%"><?= $this->filtre->getElement('titre')?></td>
                        <td width="25%"><?= $this->filtre->getElement('client')?></td>
                        <td width="10%" style="text-align: right;">
                            <?= $this->filtre->getElement('rechercher')?><?= $this->filtre->getElement('resetFiltreDevis')?>
                        </td>
                    </tr>
                    </thead>
                    <tbody id="listeFactures">
                    <?php foreach($this->paginator as $dev): ?>
                        <tr id="devis_<?= $dev->id ?>" style="display: table;width: 100%;">
                            <td width="10%">
                                <?= $dev->num_devis ?>
                            </td>
                            <td width="10%">
                                <?= $dev->ref ?>
                            </td>
                            <td width="15%"><?= date('d/m/Y', strtotime($dev->date)) ?></td>
                            <td width="30%"><?= $dev->titre ?></td>
                            <td width="25%"><?= $this->GetClientById($dev->id_client) ?></td>
                            <td width="10%">
                                <button type="button" class="btn btn-success" aria-label="Left Align" id="valid_devis_<?= $dev->id ?>">
                                    <span class="glyphicon glyphicon-check" aria-hidden="true"></span>
                                </button>
                                <button type="button" class="btn btn-primary" aria-label="Left Align" id="fiche_devis_<?= $dev->id ?>">
                                    <span class="glyphicon glyphicon-eye-open" aria-hidden="true"></span>
                                </button>
                                <button type="button" class="btn btn-warning" aria-label="Left Align" id="edit_devis_<?= $dev->id ?>">
                                    <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>
                                </button>
                                <button type="button" class="btn btn-danger" aria-label="Left Align" id="delete_devis_<?= $dev->id ?>">
                                    <span class="glyphicon glyphicon-trash" aria-hidden="true"></span>
                                </button>
                            </td>
                        </tr>
                    <?php endforeach; ?>
                    </tbody>
                    <tfoot>
                    <tr>
                        <td colspan="6">
                            <?= $this->paginationControl($this->paginator); ?>
                        </td>
                    </tr>
                    </tfoot>
                </table>
            </form>
        </div>
    </div>
</div>

