<div class="row-fluid">
    <div class="col-lg-12">
        <div class="panel panel-primary">
            <div class="panel-heading">
                <h3 class="panel-title">Devis en attente de signature</h3>
            </div>
            <div class="panel-body">
                <div class="table-responvive">
                    <table class="table table-hover table-condensed tablesorter" id="sorter">
                        <thead>
                        <tr>
                            <th>Devis</th>
                            <th>Dossier</th>
                            <th>Cr&eacute;ation</th>
                            <th width="200px">Titre</th>
                            <th>Client</th>
                            <th></th>
                        </tr>
                        <tr>
                            <td>
                                <?= $this->filtre->getElement('num_devis')?>
                            </td>
                            <td>
                                <?= $this->filtre->getElement('ref')?>
                                <?= $this->filtre->getElement('id_projet')?>
                                <?= $this->filtre->getElement('type_filtre')?>
                            </td>
                            <td colspan="1">
                                <div class="row">
                                    <div class="col-xs-6">
                                        <?= $this->filtre->getElement('mois')?>
                                    </div>
                                    <div class="col-xs-6">
                                        <?= $this->filtre->getElement('annee')?>
                                    </div>
                                </div>

                            </td>
                            <!-- 								<th></th> -->
                            <td><?= $this->filtre->getElement('titre')?></td>
                            <td><?= $this->filtre->getElement('client')?></td>
                            <td style="text-align: right;">
                                <?= $this->filtre->getElement('rechercher')?><?= $this->filtre->getElement('resetClient')?>
                            </td>
                        </tr>
                        </thead>
                        <tbody id="listeFactures">
                        <?php foreach($this->paginator as $dev): ?>
                            <tr id="devis_<?= $dev->id ?>">
                                <td>
                                    <?= $dev->num_devis ?>
                                </td>
                                <td>
                                    <?= $dev->ref ?>
                                </td>
                                <td><?= date('d/m/Y', strtotime($dev->date)) ?></td>
                                <td><?= $dev->titre ?></td>
                                <td><?= $this->GetClientById($dev->id_client) ?></td>
                                <td style="text-align: right;">
                                    <button type="button" class="btn btn-success" aria-label="Left Align" id="valid_devis_<?= $dev->id ?>">
                                        <span class="glyphicon glyphicon-check" aria-hidden="true"></span>
                                    </button>
                                    <button type="button" class="btn btn-primary" aria-label="Left Align" id="fiche_devis_<?= $dev->id ?>">
                                        <span class="glyphicon glyphicon-eye-open" aria-hidden="true"></span>
                                    </button>
                                    <button type="button" class="btn btn-warning" aria-label="Left Align" id="edit_devis_<?= $dev->id ?>">
                                        <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>
                                    </button>
                                    <button type="button" class="btn btn-danger" aria-label="Left Align" id="delete_devis_<?= $dev->id ?>">
                                        <span class="glyphicon glyphicon-trash" aria-hidden="true"></span>
                                    </button>
                                </td>
                            </tr>
                        <?php endforeach; ?>
                        </tbody>
                        <tfoot>
                        <tr>
                            <td colspan="5">
                                <?= $this->paginationControl($this->paginator); ?>
                            </td>
                        </tr>
                        </tfoot>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
