<form action="" method="POST" name="formDevis">

        <input type="hidden" name="idClient"        id="idClient"       value="<?= (isset($this->devis->id_client))? $this->devis->id_client : -1 ?>">
        <input type="hidden" name="valide"          id="valide"         value="<?= (isset($this->devis->valide))? $this->devis->valide : 0 ?>">
        <input type="hidden" name="date_validation" id="date_validation" value="<?= (isset($this->devis->date_validation))? $this->devis->date_validation : -1 ?>">
        <input type="hidden" name="facture"         id="facture"        value="<?= (isset($this->devis->facture))? $this->devis->facture : 0 ?>">
        <input type="hidden" name="date_facture"    id="date_facture"   value="<?= (isset($this->devis->date_facture))? $this->devis->date_facture : -1 ?>">
        <input type="hidden" name="paye"            id="paye"           value="<?= (isset($this->devis->paye))? $this->devis->paye : 0 ?>">
        <input type="hidden" name="redaction_facture" id="redaction_facture" value="<?= (isset($this->devis->redaction_facture))? $this->devis->redaction_facture : 0 ?>">
        <input type="hidden" name="date_paiement"   id="date_paiement"  value="<?= (isset($this->devis->date_paiement))? $this->devis->date_paiement : -1 ?>">
        <input type="hidden" name="acompte"         id="acompte"        value="<?= (isset($this->devis->acompte))? $this->devis->acompte : 0 ?>">

        <div class="panel-devis-head">
            <div class="entete-devis entete-devis-left">
                <table >
                    <tr>
                        <td colspan="2">
                            <?= $this->form->numDevis ?>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <?= $this->form->codeClient ?>
                            <datalist id="listeClientsDevis">
                            </datalist>
                        </td>
                        <td>
                            <?= $this->form->refDossier ?>
                            <datalist id="refDossierListe">
                            </datalist>
                        </td>
                    </tr>
                    <tr>
                        <td colspan="2">
                            <?= $this->form->dateCreation ?>
                        </td>
                    </tr>
                    <tr>
                        <td colspan="2">
                            <?= $this->form->delai ?>
                        </td>
                    </tr>
                    <tr>
                        <td colspan="2">
                            <?= $this->form->reglement ?>
                            <datalist id="listeReglement">
                                <?php foreach($this->listeReglement as $reglement): ?>
                                    <option value="<?= $reglement->libelle_reglement ?>" data-id="<?= $reglement->id ?>"><?= $reglement->libelle_reglement ?></option>
                                <?php endforeach; ?>
                            </datalist>
                        </td>
                    </tr>
                </table>
            </div>
            <div class="entete-devis entete-devis-right">
                <div style="width: 100%" class="pull-left">
                    <table id="tableEntete" class="table-entete-devis" >
                        <tr>
                            <td colspan="8">
                                <table width="100%">
                                    <tr>
                                        <td colspan="4">
                                            <?= $this->form->nomClient ?>
                                        </td>
                                        <td colspan="5">
                                            <?= $this->form->intitule ?>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td colspan="3">
                                            <Label>Montant Total avant remise</Label>
                                            <div id="montantTotal" style="text-align: right; font-weight: bolder"></div>
                                        </td>
                                        <td colspan="3">
                                            <Label>Montant Remise(%)</Label><br/>
                                            <input type="text" name="remise" id="remise" value="<?= $this->montantRemise ?>" onchange="fctChangeValeurRemise();">
                                        </td>
                                        <td colspan="3">
                                            <Label>Montant Total</Label>
                                            <div id="montantTotalRemise" style="text-align: right; font-weight: bolder"></div>
                                        </td>
                                    </tr>
                                </table>
                            </td>
                        </tr>
                        <tr>
                            <th>Largeur</th>
                            <th>Hauteur</th>
                            <th>Surface</th>
                            <th>Quantité</th>
                            <th>Surf totale</th>
                            <th>Coef pub</th>
                            <th>Surf pub</th>
                            <th>Périmètre</th>
                            <th></th>
                        </tr>
                        <?php $nbLigne = 0 ; ?>
                        <?php if (isset($this->devis->jsonEntete) ) : ?>
                            <?php $nbLigne = count(json_decode($this->devis->jsonEntete, true)); ?>
                            <?php foreach(json_decode($this->devis->jsonEntete, true) as $key => $entete): ?>
                            <tr  id="ligneRefEntete"  data-key="ligneRefEntete_<?= $key ?>">
                                <td><input type="text" name="largeurTableEntete"     onchange="fctChangeTableEntete();" onFocus="fctSetFocus();" title="" class="txtEntete" value="<?= $entete['largeurTableEntete'] ?>"></td>
                                <td><input type="text" name="hauteurTableEntete"     onchange="fctChangeTableEntete();" onFocus="fctSetFocus();" title="" class="txtEntete" value="<?= $entete['hauteurTableEntete'] ?>"></td>
                                <td><input type="text" name="surfaceTableEntete"     onchange="fctChangeTableEntete();" onFocus="fctSetFocus();" title="" class="txtEntete" value="<?= $entete['surfaceTableEntete'] ?>"></td>
                                <td><input type="text" name="qteTableEntete"         onchange="fctChangeTableEntete();" onFocus="fctSetFocus();" title="" class="txtEntete" value="<?= $entete['qteTableEntete'] ?>"></td>
                                <td><input type="text" name="surfTotalTableEntete"   onchange="fctChangeTableEntete();" onFocus="fctSetFocus();" title="" class="txtEntete" value="<?= $entete['surfTotalTableEntete'] ?>"></td>
                                <td><input type="text" name="coefPubTableEntete"     onchange="fctChangeTableEntete();" onFocus="fctSetFocus();" title="" class="txtEntete" value="<?= $entete['coefPubTableEntete'] ?>"></td>
                                <td><input type="text" name="surfacePubTableEntete"  onchange="fctChangeTableEntete();" onFocus="fctSetFocus();" title="" class="txtEntete" value="<?= $entete['surfacePubTableEntete'] ?>"></td>
                                <td><input type="text" name="perimetreTableEntete"   onchange="fctChangeTableEntete();" onFocus="fctSetFocus();" title="" class="txtEntete" value="<?= $entete['perimetreTableEntete'] ?>"></td>
                                <td><span class="glyphicon glyphicon-trash" aria-hidden="true" onClick="fctSupprimeLigneEntete(<?= $key ?>);" title="Supprimer la ligne" ></span></td>
                            </tr>
                            <?php endforeach; ?>
                        <?php endif; ?>
                        <tfoot>
                            <tr>
                                <td colspan="4" class="titrefooter haTotal">Surface totale</td>
                                <td id="sommeSurfTotale" class="titrefooter haTotal"></td>
                                <td class="haTotal">Surf pub</td>
                                <td id="sommeSurfPub" class="titrefooter marge" ></td>
                                <td id="sommePerimetre" class="marge"></td>
                            </tr>
                        </tfoot>
                    </table>
                    <input type="hidden" name="jsonEntete" id="jsonEntete" value="<?= json_encode($this->devis->jsonEntete) ?>">
                </div>
                <div class="elemCache">
                    <table class="table-entete-devis">
                        <tr id="elemCacheTableEntete">
                            <td><input type="text" name="largeurTableEntete"     onchange="fctChangeTableEntete();" onFocus="fctSetFocus();" title="" class="txtEntete" ></td>
                            <td><input type="text" name="hauteurTableEntete"     onchange="fctChangeTableEntete();" onFocus="fctSetFocus();" title="" class="txtEntete"></td>
                            <td><input type="text" name="surfaceTableEntete"     onchange="fctChangeTableEntete();" onFocus="fctSetFocus();" title="" class="txtEntete"></td>
                            <td><input type="text" name="qteTableEntete"         onchange="fctChangeTableEntete();" onFocus="fctSetFocus();" title="" class="txtEntete"></td>
                            <td><input type="text" name="surfTotalTableEntete"   onchange="fctChangeTableEntete();" onFocus="fctSetFocus();" title="" class="txtEntete"></td>
                            <td><input type="text" name="coefPubTableEntete"     onchange="fctChangeTableEntete();" onFocus="fctSetFocus();" title="" class="txtEntete"></td>
                            <td><input type="text" name="surfacePubTableEntete"  onchange="fctChangeTableEntete();" onFocus="fctSetFocus();" title="" class="txtEntete"></td>
                            <td><input type="text" name="perimetreTableEntete"   onchange="fctChangeTableEntete();" onFocus="fctSetFocus();" title="" class="txtEntete"></td>
                            <td><span class="glyphicon glyphicon-trash" aria-hidden="true" onClick="fctSupprimeLigneEntete(XXX);" title="Supprimer la ligne" ></span></td>
                        </tr>
                    </table>
                    <input type="hidden" name="nbLigneTableEntete" id="nbLigneTableEntete" value="<?= $nbLigne + 1 ?>" >
                </div>
            </div>
        </div>

        <div class="corps-devis">
            <div id="corps-devis-custom" >

                <?php if (count($this->itemsProduit) >0) : ?>
                    <?= $this->render('/ajax/panelproduits.phtml'); ?>
                <?php endif ?>

                <?php if (count($this->itemsSousTraitance) >0) : ?>
                    <?= $this->render('/ajax/panelsoustraitance.phtml'); ?>
                <?php endif ?>

                <?php if (count($this->itemsPrestation) >0) : ?>
                    <?= $this->render('/ajax/panelprestation.phtml'); ?>
                <?php endif ?>

                <?php if (count($this->itemsFaconnage) >0) : ?>
                    <?= $this->render('/ajax/panelfaconnage.phtml'); ?>
                <?php endif ?>

                <?php if (count($this->itemsAdhesif) >0) : ?>
                    <?= $this->render('/ajax/paneladhesif.phtml'); ?>
                <?php endif ?>

                <?php if (count($this->itemsFraisTechnique) >0) : ?>
                    <?= $this->render('/ajax/panelfraistechniques.phtml'); ?>
                <?php endif ?>

                <?php if (count($this->itemsForfaitPrestation) >0) : ?>
                    <?= $this->render('/ajax/panelforfaitprestation.phtml'); ?>
                <?php endif ?>

                <?php if (count($this->itemsDeplacement) >0) : ?>
                    <?= $this->render('/ajax/paneldeplacement.phtml'); ?>
                <?php endif ?>

                <?php if (count($this->itemsFourniture) >0) : ?>
                    <?= $this->render('/ajax/panelfourniture.phtml'); ?>
                <?php endif ?>

                <?php if (count($this->itemsPose) >0) : ?>
                    <?= $this->render('/ajax/panelpose.phtml'); ?>
                <?php endif ?>

            </div>
            <?= $this->render('/ajax/panelredaction.phtml'); ?>
        </div>
    </div>
    <div id="liste_catalogue">
        <div style="float: right; margin-bottom: 15px;">
            <button type="button" class="btn btn-success btn-xs" aria-label="Left Align" id="close_catalogue">
                <span class="glyphicon glyphicon-remove-circle" aria-hidden="true"></span>
            </button>
        </div>
        <div class="table-responvive">
            <table class="table table-hover table-condensed tablesorter" id="sorter">
                <thead>
                <tr>
                    <th style="width:10%">
                        Référence ME
                    </th>
                    <th>Fournisseur</th>
                    <th>Type</th>
                    <th style="width:8%">Epaisseur</th>
                    <th style="width:10%">Format</th>
                    <th style="width:35%">D&eacute;signation</th>
                    <th style="width:6%">P.U.</th>
                    <th>Unité</th>
                    <th>Coef</th>
                    <th></th>
                </tr>
                <tr>
                    <td>
                        <?= $this->filtreForm->getElement('reference') ?>
                    </td>
                    <td>
                        <?= $this->filtreForm->getElement('fournisseur') ?>
                    </td>
                    <td><?= $this->filtreForm->getElement('type') ?></td>
                    <td><?= $this->filtreForm->getElement('epaisseur') ?></td>
                    <td><?= $this->filtreForm->getElement('format') ?></td>
                    <td>
                        <?= $this->filtreForm->getElement('produit') ?>
                    </td>
                    <td colspan="4" style="text-align:right;">
                        <img src="/images/load.gif" alt="loader" id="loader"/>
                        <?= $this->filtreForm->getElement('rechercher') ?>
                        <?= $this->filtreForm->getElement('resetCatalogue') ?>
                    </td>
                </tr>
                </thead>
                <tbody id="liste_produits">
                <?php foreach($this->catalogues as $catalogue):?>
                    <tr>
                        <td><?= $catalogue->code_me?></td>
                        <td><?= $catalogue->fournisseur?></td>
                        <td><?= $catalogue->type?></td>
                        <td><?= $catalogue->epaisseur?></td>
                        <td><?= $catalogue->format?></td>
                        <td><?= $catalogue->designation ?></td>
                        <td style="text-align:right;">
                            <?php if(!(int) $catalogue->unitaire):?>
                                <?php if($catalogue->prixM2 == null):?>
                                    <?= $catalogue->prixML ?>
                                <?php else:?>
                                    <?= $catalogue->prixM2 ?>
                                <?php endif;?>
                            <?php else:?>
                                <?= $catalogue->unitaire ?>
                            <?php endif;?>
                            &nbsp;&euro;
                        </td>
                        <td style="text-align:center;">
                            <?php if(!(int) $catalogue->unitaire):?>
                                <?php if($catalogue->prixM2 == null):?>
                                    Ml
                                <?php else:?>
                                    M2
                                <?php endif;?>
                            <?php else:?>
                                Unitaire
                            <?php endif;?>
                        </td>
                        <td style="text-align:right;"><?= $catalogue->coeff_marge?></td>
                        <td style="text-align:right;">
                            <button type="button" class="btn btn-warning" aria-label="Left Align" id="fill_form_<?= $catalogue->id_produit ?>">
                                <span class="glyphicon glyphicon-arrow-right" aria-hidden="true"></span>
                            </button>
                        </td>
                    </tr>
                <?php endforeach; ?>
                </tbody>
            </table>
        </div>
    </div>
    <input type="submit" class="btn btn-primary" value="Enregistrer" >

    <input type="hidden" name="fromDevis" id="fromDevis" value="1">
</form>
