<div class="col-md-6">
    <ul class="nav navbar-nav navbar-right navbarPanel">
        <li id="BtAjoutligneTableEntete" title="Ajouter une ligne" onclick="fctAjoutLigneTableEntete();">
            <span class="glyphicon glyphicon-plus"></span>
        </li>
        <!--
        <li id="BtSuprimeligneTableEntete" title="Supprimer une ligne" onclick="fctSupprimeLigneTableEntete();">
            <span class="glyphicon glyphicon-minus"></span>
        </li>
        -->
        <li class="dropdown">
            <a href="#" class="dropdown-toggle monDropDownNavBar" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Ajouter <span class="caret"></span></a>
            <ul class="dropdown-menu">
                <li data-addbloc="produit"><a href="#">Produit</a></li>
                <li data-addbloc="sousTraitance"><a href="#">Sous traitance</a></li>
                <li data-addbloc="prestation"><a href="#">Prestation</a></li>
                <li data-addbloc="faconnage"><a href="#">Façonnage</a></li>
                <li data-addbloc="adhesif"><a href="#">Adhésif</a></li>
                <li data-addbloc="fraisTechniques"><a href="#">Frais Techniques</a></li>
                <li data-addbloc="forfaitPresation"><a href="#">Forfait Prestation</a></li>
                <li data-addbloc="deplacement"><a href="#">Déplacement</a></li>
                <li data-addbloc="fourniture"><a href="#">Fourniture</a></li>
                <li data-addbloc="pose"><a href="#">Pose</a></li>
                <li data-addbloc="itemredaction"><a href="#">Article de devis</a></li>
            </ul>
        </li>
    </ul>
</div>