<form action="" method="POST" name="formDevis">

        <input type="hidden" name="idClient"        id="idClient"       value="<?= (isset($this->devis->id_client))? $this->devis->id_client : -1 ?>">
        <input type="hidden" name="valide"          id="valide"         value="<?= (isset($this->devis->valide))? $this->devis->valide : -1 ?>">
        <input type="hidden" name="date_validation" id="date_validation" value="<?= (isset($this->devis->date_validation))? $this->devis->date_validation : -1 ?>">
        <input type="hidden" name="facture"         id="facture"        value="<?= (isset($this->devis->facture))? $this->devis->facture : -1 ?>">
        <input type="hidden" name="date_facture"    id="date_facture"   value="<?= (isset($this->devis->date_facture))? $this->devis->date_facture : -1 ?>">
        <input type="hidden" name="paye"            id="paye"           value="<?= (isset($this->devis->paye))? $this->devis->paye : -1 ?>">
        <input type="hidden" name="redaction_facture" id="redaction_facture" value="<?= (isset($this->devis->redaction_facture))? $this->devis->redaction_facture : -1 ?>">
        <input type="hidden" name="date_paiement"   id="date_paiement"  value="<?= (isset($this->devis->date_paiement))? $this->devis->date_paiement : -1 ?>">
        <input type="hidden" name="acompte"         id="acompte"        value="<?= (isset($this->devis->acompte))? $this->devis->acompte : -1 ?>">
        <input type="hidden" name="remise"          id="remise"         value="<?= (isset($this->devis->remise))? $this->devis->remise : -1 ?>">

        <div class="panel-devis-head">
            <div class="entete-devis entete-devis-left">
                <table >
                    <tr>
                        <td>
                            <?= $this->form->codeClient ?>
                            <datalist id="listeClientsDevis">
                            </datalist>
                        </td>
                        <td>
                            <?= $this->form->refDossier ?>
                        </td>
                    </tr>
                    <tr>
                        <td colspan="2">
                            <?= $this->form->dateCreation ?>
                        </td>
                    </tr>
                    <tr>
                        <td colspan="2">
                            <?= $this->form->delai ?>
                        </td>
                    </tr>
                    <tr>
                        <td colspan="2">
                            <?= $this->form->reglement ?>
                            <datalist id="listeReglement">
                                <?php foreach($this->listeReglement as $reglement): ?>
                                    <option value="<?= $reglement->libelle_reglement ?>" data-id="<?= $reglement->id ?>"><?= $reglement->libelle_reglement ?></option>
                                <?php endforeach; ?>
                            </datalist>
                        </td>
                    </tr>
                </table>
            </div>
            <div class="entete-devis entete-devis-right">
                <div style="width: 100%" class="pull-left">
                    <table id="tableEntete" class="table-entete-devis">
                        <tr>
                            <td colspan="4">
                                <?= $this->form->nomClient ?>
                            </td>
                            <td colspan="4">
                                <?= $this->form->intitule ?>
                            </td>
                        </tr>
                        <tr>
                            <th>Largeur</th>
                            <th>Hauteur</th>
                            <th>Surface</th>
                            <th>Quantité</th>
                            <th>Surf totale</th>
                            <th>Coef pub</th>
                            <th>Surf pub</th>
                            <th>Périmètre</th>
                        </tr>
                        <?php if (isset($this->devis->jsonEntete) ) : ?>
                            <?php foreach(json_decode($this->devis->jsonEntete, true) as $key => $entete): ?>
                            <tr>
                                <td><input type="text" name="largeurTableEntete"     onchange="fctChangeTableEntete();" onFocus="fctSetFocus();" title="" class="txtEntete" value="<?= $entete['largeurTableEntete'] ?>"></td>
                                <td><input type="text" name="hauteurTableEntete"     onchange="fctChangeTableEntete();" onFocus="fctSetFocus();" title="" class="txtEntete" value="<?= $entete['hauteurTableEntete'] ?>"></td>
                                <td><input type="text" name="surfaceTableEntete"     onchange="fctChangeTableEntete();" onFocus="fctSetFocus();" title="" class="txtEntete" value="<?= $entete['surfaceTableEntete'] ?>"></td>
                                <td><input type="text" name="qteTableEntete"         onchange="fctChangeTableEntete();" onFocus="fctSetFocus();" title="" class="txtEntete" value="<?= $entete['qteTableEntete'] ?>"></td>
                                <td><input type="text" name="surfTotalTableEntete"   onchange="fctChangeTableEntete();" onFocus="fctSetFocus();" title="" class="txtEntete" value="<?= $entete['surfTotalTableEntete'] ?>"></td>
                                <td><input type="text" name="coefPubTableEntete"     onchange="fctChangeTableEntete();" onFocus="fctSetFocus();" title="" class="txtEntete" value="<?= $entete['coefPubTableEntete'] ?>"></td>
                                <td><input type="text" name="surfacePubTableEntete"  onchange="fctChangeTableEntete();" onFocus="fctSetFocus();" title="" class="txtEntete" value="<?= $entete['surfacePubTableEntete'] ?>"></td>
                                <td><input type="text" name="perimetreTableEntete"   onchange="fctChangeTableEntete();" onFocus="fctSetFocus();" title="" class="txtEntete" value="<?= $entete['perimetreTableEntete'] ?>"></td>
                            </tr>
                            <?php endforeach; ?>
                        <?php endif; ?>
                        <tfoot>
                            <tr>
                                <td colspan="4" class="titrefooter haTotal">Surface totale</td>
                                <td id="sommeSurfTotale" class="titrefooter haTotal"></td>
                                <td class="haTotal">Surf pub</td>
                                <td id="sommeSurfPub" class="titrefooter marge" ></td>
                                <td id="sommePerimetre" class="marge"></td>
                            </tr>
                        </tfoot>
                    </table>
                    <input type="hidden" name="jsonEntete" id="jsonEntete" value="<?= json_encode($this->devis->jsonEntete) ?>">
                </div>
                <div class="elemCache">
                    <table class="table-entete-devis">
                        <tr id="elemCacheTableEntete">
                            <td><input type="text" name="largeurTableEntete"     onchange="fctChangeTableEntete();" onFocus="fctSetFocus();" title="" class="txtEntete" ></td>
                            <td><input type="text" name="hauteurTableEntete"     onchange="fctChangeTableEntete();" onFocus="fctSetFocus();" title="" class="txtEntete"></td>
                            <td><input type="text" name="surfaceTableEntete"     onchange="fctChangeTableEntete();" onFocus="fctSetFocus();" title="" class="txtEntete"></td>
                            <td><input type="text" name="qteTableEntete"         onchange="fctChangeTableEntete();" onFocus="fctSetFocus();" title="" class="txtEntete"></td>
                            <td><input type="text" name="surfTotalTableEntete"   onchange="fctChangeTableEntete();" onFocus="fctSetFocus();" title="" class="txtEntete"></td>
                            <td><input type="text" name="coefPubTableEntete"     onchange="fctChangeTableEntete();" onFocus="fctSetFocus();" title="" class="txtEntete"></td>
                            <td><input type="text" name="surfacePubTableEntete"  onchange="fctChangeTableEntete();" onFocus="fctSetFocus();" title="" class="txtEntete"></td>
                            <td><input type="text" name="perimetreTableEntete"   onchange="fctChangeTableEntete();" onFocus="fctSetFocus();" title="" class="txtEntete"></td>
                        </tr>
                    </table>
                    <input type="hidden" name="nbLigneTableEntete" id="nbLigneTableEntete" value="<?= count($this->itemsEntete) + 1 ?>" >
                </div>
            </div>
        </div>
        <div class="corps-devis">
            <div id="corps-devis-custom" >

                <?php if (count($this->itemsProduit) >0) : ?>
                    <?= $this->render('/ajax/panelproduits.phtml'); ?>
                <?php endif ?>

                <?php if (count($this->itemsDeplacement) >0) : ?>
                    <?= $this->render('/ajax/paneldeplacement.phtml'); ?>
                <?php endif ?>

                <?php if (count($this->itemsFaconnage) >0) : ?>
                    <?= $this->render('/ajax/panelfaconnage.phtml'); ?>
                <?php endif ?>

                <?php if (count($this->itemsForfaitPrestation) >0) : ?>
                    <?= $this->render('/ajax/panelforfaitprestation.phtml'); ?>
                <?php endif ?>

                <?php if (count($this->itemsFourniture) >0) : ?>
                    <?= $this->render('/ajax/panelfourniture.phtml'); ?>
                <?php endif ?>

                <?php if (count($this->itemsFraisTechnique) >0) : ?>
                    <?= $this->render('/ajax/panelfraistechniques.phtml'); ?>
                <?php endif ?>

                <?php if (count($this->itemsPose) >0) : ?>
                    <?= $this->render('/ajax/panelpose.phtml'); ?>
                <?php endif ?>

                <?php if (count($this->itemsPrestation) >0) : ?>
                    <?= $this->render('/ajax/panelprestation.phtml'); ?>
                <?php endif ?>

                <?php if (count($this->itemsSousTraitance) >0) : ?>
                    <?= $this->render('/ajax/panelsoustraitance.phtml'); ?>
                <?php endif ?>

                <?php if (count($this->itemsAdhesif) >0) : ?>
                    <?= $this->render('/ajax/paneladhesif.phtml'); ?>
                <?php endif ?>

            </div>
            <?= $this->render('/ajax/panelredaction.phtml'); ?>
        </div>
    </div>
    <input type="submit" class="btn btn-primary" value="Enregistrer" >
</form>