<div class="panel panel-primary">
	<div class="panel-heading">
		<h3 class="panel-title">Editer un prospect / client</h3>
	</div>
	<div class="panel-body">
		<div class="row">
			<div class="col-lg-12" style="text-align: right;">
				<a href="/projets/ajout/id_client/<?php echo $this->id_client ?>" class="btn btn-success">Créer un projet avec ce client</a>
			</div>
		</div>
		<?php echo $this->form ?>
	</div>
</div>