<div class="panel panel-primary">
	<div class="panel-heading">
		<h3 class="panel-title">Liste des clients / prospects</h3>
	</div>
	<div class="panel-body">
		<div class="table-responvive">
			<table class="table table-hover table-condensed tablesorter" id="sorter">
				<thead>
					<tr>
						<th>Num client</th>
						<th>Soci&eacute;t&eacute;</th>
						<th>Adresse</th>
						<th>T&eacute;l&eacute;phone</th>
						<th>Email</th>
                        <th>Contact</th>
						<th></th>
					</tr>
					<form method="post">
						<tr>
							<td>
								<?= $this->filtreClient->getElement('num_client')?>
							</td>
							<td>
								<?= $this->filtreClient->getElement('id_client')?>
								<?= $this->filtreClient->getElement('type_filtre')?>
								<?= $this->filtreClient->getElement('client')?>
							</td>
							<td><?= $this->filtreClient->getElement('adresse')?></td>
							<td></td>
							<td></td>
                            <td><?= $this->filtreClient->getElement('contact')?></td>
							<td style="text-align: right;">
								<?= $this->filtreClient->getElement('rechercher')?><?php echo $this->filtreClient->getElement('resetClient')?>
							</td>
						</tr>
					</form>
				</thead>
				<tbody id="listeClients">
					<?php foreach($this->paginator as $client): ?>
						<tr>
							<td><?php echo $client->ref ?></td>
							<td style="text-transform: uppercase;"><?php echo $client->societe ?></td>
							<td style="text-transform: uppercase;">
								<?php echo $client->adresse . ' - ' . $client->codepostal . ' ' . $client->ville?>
							</td>
							<td>
								<?php $tels = explode(',', $client->tel)?>
								<?php foreach($tels as $tel): ?>	
									<p><?php echo $tel ?></p>
								<?php endforeach; ?>
							</td>
							<td>
								<?php $mails = explode(',', $client->mel)?>
								<?php foreach($mails as $mail): ?>
									<p><a href="mailto:<?php echo $mail?>"><?php echo $mail?></a></p>
								<?php endforeach; ?>
							</td>
                            <td>
                                <?= $client->contact_nom ?>
                            </td>
							<td style="text-align: right;">
								<button type="button" class="btn btn-primary" aria-label="Left Align" id="fiche_clients_<?php echo $client->id_client?>">
								  <span class="glyphicon glyphicon-eye-open" aria-hidden="true"></span>
								</button>
								<button type="button" class="btn btn-warning" aria-label="Left Align" id="edit_clients_<?php echo $client->id_client?>">
								  <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>
								</button>
								<button type="button" class="btn btn-danger" aria-label="Left Align" id="delete_clients_<?php echo $client->id_client?>">
								  <span class="glyphicon glyphicon-trash" aria-hidden="true"></span>
								</button>
							</td>
						</tr>
					<?php endforeach; ?>
				</tbody>
				<tfoot>
					<tr>
						<td colspan="7">
							<?php echo $this->paginationControl($this->paginator); ?>
						</td>
					</tr>
				</tfoot>
			</table>
		</div>
	</div>
</div>