<div id="tabs">
	<ul>
		<li><a href="#tabs-1">Gestion des taches</a></li>
		<li><a href="#tabs-2">Informations</a></li>
	</ul>
	<div id="tabs-2">
		<div class="panel panel-primary">
			<div class="panel-heading">
				<h3 class="panel-title">Modifier un projet</h3>
			</div>
			<div class="panel-body">
				<a href="/projets/fiche/id/<?= $this->projet->id_projet?>" class="btn btn-primary pull-right" style="margin-left: 5px;margin-right: 5px;">
					<span class="glyphicon glyphicon-eye-open" aria-hidden="true">&nbsp;Voir la fiche projet</span>
				</a>
				<br />
				<?= $this->form ?>
			</div>
		</div>
	</div>
	<div id="tabs-1">
        <div id="tabs-3">
            <div class="panel panel-primary">
                <div class="panel-heading">
                    <h3 class="panel-title">Infos du projet</h3>
                </div>
                <div class="panel-body">
                    <div> Nom du projet : <?= $this->projet->titre ?> </div>

                    <div> Nom de la société : <?= $this->GetClientById($this->projet->id_client) ?> </div>

                    <div> Numéro de dossier : <a href="/projets/fiche/id/<?= $this->projet->id_projet ?>"><?= $this->projet->dossier ?></a></div>
                </div>
            </div>
        </div>
		<div class="panel panel-primary">
			<div class="panel-heading">
				<h3 class="panel-title">Ajouter une &eacute;tape</h3>
			</div>
			<div class="panel-body">
				<div class="table-responvive">
					<table class="table">
						<thead>
							<tr>
								<th>#</th>
								<th>T&acirc;che</th>
								<th>Affectée &agrave;</th>
								<th>Nombre d'heures</th>
                                <th>Visible</th>
								<th></th>
							</tr>
						</thead>
						<tbody>
							<tr>
								<td>
									<?= $this->formProjet->getElement('id_projet') ?>
									<?= $this->formProjet->getElement('id_tache') ?>
								</td>
								<td><?= $this->formProjet->getElement('tache') ?></td>
								<td>
									<?= $this->formProjet->getElement('id_user1') ?>
									<?= $this->formProjet->getElement('id_user2') ?>
									<?= $this->formProjet->getElement('id_user3') ?>
								</td>
								<td><?= $this->formProjet->getElement('duree') ?></td>
                                <td><?= $this->formProjet->getElement('visible') ?></td>
								<td><?= $this->formProjet->getElement('ajouter') ?></td>
							</tr>
						</tbody>
					</table>
				</div>
			</div>
		</div>
		<div id="alertTache" style="display: none;"></div>
		<div class="panel panel-primary" id="planTache">
			<div class="panel-heading">
				<h3 class="panel-title">Planifier une tache</h3>
			</div>
			<div class="panel-body">
				<div class="table-responvive">
					<table class="table">
						<thead>
							<tr>
								<th></th>
								<th>Date</th>
								<th>Nb heures</th>
								<th></th>
							</tr>
						</thead>
						<tbody>
							<td>
								<?= $this->formTache->getElement('id_user')?>
								<?= $this->formTache->getElement('id_tache')?>
							</td>
							<td><?= $this->formTache->getElement('date')?></td>
							<td><?= $this->formTache->getElement('nb_heures')?></td>
							<td><?= $this->formTache->getElement('priority')?></td>
							<td>
								<?= $this->formTache->getElement('ajouter')?>
							</td>
						</tbody>
					</table>
				</div>
			</div>
		</div>
		<div class="panel panel-primary">
			<div class="panel-heading">
				<h3 class="panel-title">Etapes du projet</h3>
			</div>
			<div class="panel-body">
				<div class="table-responvive">
					<table class="table">
						<thead>
							<tr>
								<th>#</th>
								<th>T&acirc;che</th>
								<th>Affectée &agrave;</th>
								<th>Nombre d'heures</th>
								<th>Planifiée le </th>
								<th>Réalisée le</th>
								<th></th>
							</tr>
						</thead>
						<tbody id="liste_items_projet">
							<?php foreach($this->taches as $tache): ?>
								<tr id="tache_<?= $tache->id ?>">
									<td></td>
									<td><?= $tache->tache ?></td>
									<td>
										<?= $this->GetUserById($tache->id_user1) ?>&nbsp;
										<?= $this->GetUserById($tache->id_user2) ?>&nbsp;
										<?= $this->GetUserById($tache->id_user3) ?>
									</td>
									<td id="nbh_<?= $tache->id?>"><?= $tache->duree ?></td>
									<td  id="plan_<?= $tache->id?>">
										<span style="color:red;"><?= $this->GetDateDone($tache->id) ?></span>
									</td>
									<td>
										<?php if($tache->date_fait != null && $tache->date_fait != '0000-00-00') :?>
											<span style="color:green;"><?= date('d/m/Y', strtotime($tache->date_fait)) ?></span>
										<?php endif; ?>
									</td>
									<td style="text-align:right;">
										<button type="button" class="btn btn-warning" aria-label="Left Align" id="edititemprojet_<?= $tache->id ?>" style="cursor:pointer;">
											<span class="glyphicon glyphicon-pencil" aria-hidden="true" ></span>
										</button>
										<button type="button" class="btn btn-warning" aria-label="Left Align" id="getCalendar_<?= $tache->id ?>_<?= $tache->id_user1 ?>">
											<span class="glyphicon glyphicon-calendar" aria-hidden="true"></span>
										</button>
										<button type="button" class="btn btn-danger sur" aria-label="Left Align" id="deleteitemprojet_<?= $tache->id ?>" style="cursor:pointer;">
											<span class="glyphicon glyphicon-trash" aria-hidden="true" ></span>
										</button>
									</td>
								</tr>
							<?php endforeach; ?>
						</tbody>
					</table>
				</div>
			</div>
		</div>
	</div>
</div>
