<table width="100%" class="tableItemsDevis">
    <tr>
        <th colspan="8">Adhésif</th>
    </tr>
    <tr>
        <th>Code</th>
        <th>Adhesifs</th>
        <th>Surface</th>
        <th>Quantité</th>
        <th>H.A M2/ML</th>
        <th>H.A Total</th>
        <th>Coef Marge</th>
        <th>Px vente</th>
    </tr>
    <?php if (isset($this->itemsAdhesif)) : ?>
        <?php foreach($this->itemsAdhesif as $key => $adhesif): ?>
            <?php $json = json_decode($adhesif->json, true) ?>
            <tr id="ligneRefAdhesif">
                <td>
                    <?= $json['code'] ?>
                </td>
                <td><?= $json['adhesif'] ?></td>
                <td><?= $json['surface'] ?></td>
                <td><?= $json['qte'] ?></td>
                <td><?= $json['h.a_ml'] ?></td>
                <td><?= $json['h.a_total'] ?></td>
                <td><?= $json['coefmarge'] ?></td>
                <td><?= $json['pxvente'] ?></td>
            </tr>
        <?php endforeach; ?>
    <?php endif; ?>
</table>