<div class="dropdown">
  <button class="btn btn-default dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-expanded="true">
    Menu
    <span class="caret"></span>
  </button>
  <ul class="dropdown-menu" role="menu" aria-labelledby="dropdownMenu1">
    <li role="presentation"><a role="menuitem" tabindex="-1" href="/projets/index?dr=0">Projets en cours</a></li>
    <li role="presentation"><a role="menuitem" tabindex="-1" href="/projets/ajout">Ajouter projet</a></li>
    <li role="presentation"><a role="menuitem" tabindex="-1" href="/projets/historique">Projets clotur&eacute;s</a></li> 
    <li role="presentation"><a role="menuitem" tabindex="-1" href="/projets/index?dr=1">Devis à relancer</a></li>
    <li role="presentation"><a role="menuitem" tabindex="-1" href="/projets/index?dr=2">Dossier en attente</a></li>
  </ul>
</div>