<div class="dropdown">
  <button class="btn btn-default dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-expanded="true">
    Menu
    <span class="caret"></span>
  </button>
  <ul class="dropdown-menu" role="menu" aria-labelledby="dropdownMenu1">
    <li role="presentation"><a role="menuitem" tabindex="-1" href="/facturation/index">Devis en attente</a></li>
    <li role="presentation"><a role="menuitem" tabindex="-1" href="/facturation/devisacceptes">Devis accept&eacute;s</a></li>
    <li role="presentation"><a role="menuitem" tabindex="-1" href="/facturation/creerdevis">Cr&eacute;er devis / facture</a></li>
    <li role="presentation"><a role="menuitem" tabindex="-1" href="/facturation/factures">Factures en attente</a></li>
    <li role="presentation"><a role="menuitem" tabindex="-1" href="/facturation/historique/f/devis">Historique devis</a></li>
    <li role="presentation"><a role="menuitem" tabindex="-1" href="/facturation/historique/f/facture">Historique factures</a></li>
  </ul>
</div>