<div class="dropdown">
  <button class="btn btn-default dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-expanded="true">
    Menu
    <span class="caret"></span>
  </button>
  <ul class="dropdown-menu" role="menu" aria-labelledby="dropdownMenu1">
    <li role="presentation"><a role="menuitem" tabindex="-1" href="/facture/index">Facture en attente</a></li>
    <li role="presentation"><a role="menuitem" tabindex="-1" href="/facture/histo">Historique des factures</a></li>
  </ul>
</div>