<div class="dropdown">
  <button class="btn btn-default dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-expanded="true">
    Menu
    <span class="caret"></span>
  </button>
  <ul class="dropdown-menu" role="menu" aria-labelledby="dropdownMenu1">
	  <li role="presentation"><a role="menuitem" tabindex="-1" href="/messages/">Messages reçus</a></li>
    <li role="presentation"><a role="menuitem" tabindex="-1" href="/messages/new">Nouveau message</a></li>
    <li role="presentation"><a role="menuitem" tabindex="-1" href="/messages/sent">Messages envoy&eacute;s</a></li>
  </ul>
</div>