
<script language="JavaScript">
    function openParent(url)
        {                
            window.opener.document.location.href = url;                   
        }
</script>

<?php
function getNomClassFromIndice($ind, $numJour)
{
    $nomClass = '';

	if($ind == 0)
	{
		if($numJour==1 || $numJour==2) 
			$nomClass='noDisplay';
	}

	if($ind == 1)
	{
		if( $numJour==2) 
			$nomClass='noDisplay';
	}

	if($ind == 5)
	{
		if( $numJour==0) 
			$nomClass='noDisplay';
	}

	if($ind == 6)
	{
		if( $numJour==0 || $numJour==1 ) 
			$nomClass='noDisplay';
	}

	if($ind>6)
        $nomClass='noDisplay';

	return $nomClass;
}
?>


<div class="panel panel-primary">
	<div class="panel-heading">
		<h3 class="panel-title">
			<button type="button" class="btn btn-warning" aria-label="Left Align" onclick="javascript:window.location.reload()">
				<span class="glyphicon glyphicon-refresh" aria-hidden="true"></span>
			</button>					
			<button type="button" class="btn btn-warning" aria-label="Left Align" id="gotoweek_<?= $this->prevWeek ?>">
				<span class="glyphicon glyphicon-backward" aria-hidden="true"></span>
			</button>
			<button type="button" class="btn btn-warning" aria-label="Left Align" id="gotoDay_less_<?= $this->prevWeek ?>">
				<span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
			</button>
			<button type="button" class="btn btn-warning" aria-label="Left Align" id="gotoweek_<?= date('W') ?>">
				Calendrier
			</button>
			<button type="button" class="btn btn-warning" aria-label="Left Align" id="gotoDay_more_<?= $this->nextWeek ?>">
				<span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
			</button>
			<button type="button" class="btn btn-warning" aria-label="Left Align" id="gotoweek_<?= $this->nextWeek ?>">
				<span class="glyphicon glyphicon-forward" aria-hidden="true"></span>
			</button>
		</h3>
	</div>

<input type="hidden" name="numJour" id="numJour" value="<?= $this->numJour ?>" >

	<div class="panel-body">
		<?= $this->selectUser ?>
		<div class="table-responvive">
			<table class="table table-hover table-condensed">
				<thead>
					<tr>
						<td><?= $this->form->getElement('date') ?></td>
						<td><?= $this->form->getElement('event') ?></td>
						<td><?= $this->form->getElement('priority') ?></td>
						<td><?= $this->form->getElement('nb_heures') ?></td>
						<td><?= $this->form->getElement('id_user1') ?></td>
						<td>
							<?= $this->form->getElement('ajouter') ?>
						</td>
						<td></td>
					</tr>
					<tr>
						<th style="width:18%;" data-numCol="0" data-col="1" class='<?= getNomClassFromIndice(0, $this->numJour) ?>' >Lundi</th>
						<th style="width:18%;" data-numCol="1" data-col="1" class='<?= getNomClassFromIndice(1, $this->numJour) ?>' >Mardi</th>
						<th style="width:18%;" data-numCol="2" data-col="1" class='<?= getNomClassFromIndice(2, $this->numJour) ?>'>Mercredi</th>
						<th style="width:18%;" data-numCol="3" data-col="1" class='<?= getNomClassFromIndice(3, $this->numJour) ?>'>Jeudi</th>
						<th style="width:18%;" data-numCol="4" data-col="1" class='<?= getNomClassFromIndice(4, $this->numJour) ?>'>Vendredi</th>

                        <th style="width:18%;" data-numCol="5" data-col="1" class='<?= getNomClassFromIndice(5, $this->numJour) ?>' >Lundi</th>
                        <th style="width:18%;" data-numCol="6" data-col="1" class='<?= getNomClassFromIndice(6, $this->numJour) ?>' >Mardi</th>
                        <th style="width:18%;" data-numCol="7" data-col="1" class='<?= getNomClassFromIndice(7, $this->numJour) ?>' >Mercredi</th>
                        <th style="width:18%;" data-numCol="8" data-col="1" class='<?= getNomClassFromIndice(8, $this->numJour) ?>' >Jeudi</th>
                        <th style="width:18%;" data-numCol="9" data-col="1" class='<?= getNomClassFromIndice(9, $this->numJour) ?>' >Vendredi</th>

                        <th style="width:18%;">
							Semaine suivante
						</th>
					</tr>
					<tr>
						<?php $indice = 1; ?>
						<?php foreach($this->dates as $key => $date):?>
                            <?php $key1 = date('l',strtotime( $key)); ?>
                            <?php if( (
                                strpos($key1, 'Saturday') === false
                                &&
                                strpos($key1, 'Sunday') === false
                                ) ): ?>
							    <th data-numCol="<?= ($indice-1) ?>" data-col="1" class="<?=  getNomClassFromIndice($indice-1, $this->numJour) ?>" ><?= $date.' '.strpos($key1, 'Saturday') ?></th>
                                <?php $indice++; ?>
                            <?php endif; ?>
						<?php endforeach;?>
						<th></th>
					</tr>
				</thead>
				<tbody>
					<tr> 
						<?php $indice = 1; ?>
						<?php foreach($this->dates as $key => $date):?>
                            <?php $key1 = date('l',strtotime( $key)); ?>
                            <?php if( (
                                strpos($key1, 'Saturday') === false
                                &&
                                strpos($key1, 'Sunday') === false
                            ) ): ?>
						<td data-numCol="<?= ($indice-1) ?>" data-col="1" class="<?=  getNomClassFromIndice($indice-1, $this->numJour) ?> droppable sortable" id="<?= $key ?>">
                            <?php if(count($this->eventsDate[$key])): ?>

								<?php foreach($this->eventsDate[$key] as $event):?>
                                    <?php /*
                                    <?php if(!isset($nbhPerUser[$key][$event->id_user1])) : ?>
                                        <?php $nbhPerUser[$key][$event->id_user1] = 0; ?>
                                    <? endif;?>

                                    <?php if(!isset($nbhPerUser[$key][$event->id_user2])) : ?>
                                        <?php $nbhPerUser[$key][$event->id_user2] = 0; ?>
                                    <? endif;?>

                                    <?php if(!isset($nbhPerUser[$key][$event->id_user3])) : ?>
                                        <?php $nbhPerUser[$key][$event->id_user3] = 0; ?>
                                    <? endif;?>
                                    */ ?>
									<?php if($this->IsDone($event->id_tache)):?>
										<?php $colorsPriority = [1=>'#DFD172',2=> 'orange', 3=>'red']; $p = "";?>
										<?php for($i=0; $i < $event->priority; $i++):?>
											<?php  $p .= "!";  ?>
										<?php endfor;?>
											<div id="event_<?= $event->id_event ?>" class="thumbnail draggable users ui-state-default user_<?= $event->id_user1?> <?= $event->id_user2?"user_" . $event->id_user2:"" ?> <?= $event->id_user3?"user_" . $event->id_user3:"" ?>">
												<div class="pull-right">
													<?php if($event->id_tache):?>
														<a class="btn btn-xs btn-primary small" onclick="openParent('/projets/fiche/id/<?= $this->GetProjectByTaskId($event->id_tache)?>')">
															<span class="glyphicon glyphicon-eye-open" aria-hidden="true"></span>
														</a>
														<a class="btn btn-xs btn-warning small" onclick="openParent('/projets/editer/id/<?= $this->GetProjectByTaskId($event->id_tache)?>')">
															<span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>
														</a>
													<?php endif;?>
													<a class="btn btn-xs btn-danger small" href="/calendar/delete/id/<?= $event->id_event?>/week/<?= $this->week?>">
														<span class="glyphicon glyphicon-trash" aria-hidden="true"></span>
													</a>
												</div>
												<span class="label" style="background-color: <?= $this->GetColorByUser($event->id_user1)?>">
													<?php $nbhPerUser[$key][$event->id_user1] += $event->nb_heures ?>
													<?= $this->GetUserById($event->id_user1) ?> : <?= $event->nb_heures ?> h
												</span><br />
												<?php if ($event->id_user2 != 0):?>
													<?php $nbhPerUser[$key][$event->id_user2] += $event->nb_heures ?>
													<span class="label" style="background-color: <?= $this->GetColorByUser($event->id_user2)?>">
														<?= $this->GetUserById($event->id_user2) ?> : <?= $event->nb_heures ?> h
													</span><br />
												<?php endif;?>
												<?php if ($event->id_user3 != 0):?>
													<?php $nbhPerUser[$key][$event->id_user3] += $event->nb_heures ?>
													<span class="label" style="background-color: <?= $this->GetColorByUser($event->id_user3)?>">
														<?= $this->GetUserById($event->id_user3) ?> : <?= $event->nb_heures ?> h
													</span><br />
												<?php endif;?>
												<?php if((int) $event->priority):?>
													&nbsp;<span class="label" style="background-color: <?= $colorsPriority[$event->priority]?>;">
														<?= $p ?>
													</span>
												<?php endif;?>
												<br />
												<?php if($event->id_tache): ?> 
													<?= $this->GetClientByTask($event->id_tache) ?> (<?= $this->GetProjectNum($event->id_tache) ?>)<br />
													<?= $this->GetTaskById($event->id_tache) ?>
												<?php else: ?>
													<?= $event->event; ?>
												<?php endif; ?>
											</div>
											<?php $p = "";?>
										<?php endif;?>
								<?php endforeach; ?>
							<?php endif; ?>
						</td>
						<?php $indice++; ?>
                        <?php endif; ?>
						<?php endforeach;?>
						<td id="<?= $this->semaineProchaine?>" class="droppable sortable"></td>
					</tr>
				</tbody>
				<tfoot>
					<tr>
						<?php $indice = 1; ?>
						<?php foreach($this->dates as $k => $date):?>
						<?php @ksort($nbhPerUser[$k]); ?>
							<th data-numCol="<?= ($indice-1) ?>" data-col="1" class="<?=  getNomClassFromIndice($indice-1, $this->numJour) ?>" >
								<?php
								if(count($nbhPerUser[$k])): ?>
									<?php foreach($nbhPerUser[$k] as $key =>$user): ?>
										<span class="label" style="display: block; margin: 3px;font-size:13px; ;background-color: <?= $this->GetColorByUser($key)?>">
											<?= $this->GetUserById($key); ?> : <?= $user ?>
										</span>
									<?php endforeach; ?>
								<?php endif; ?>
							</th>
						<?php $indice++; ?>
						<?php endforeach; ?>
						<td></td>
					</tr>
				</tfoot>
			</table>
		</div>
	</div>
</div>

<input type="hidden" name="numJourLocalStorage" id="numJourLocalStorage">