<tr id="tache_<?php echo $this->id_tache ?>">
	<td></td>
	<td><?php echo $this->tache ?></td>
	<td>
		<?php echo $this->GetUserById($this->id_user1) ?>&nbsp;
		<?php echo $this->GetUserById($this->id_user2) ?>&nbsp;
		<?php echo $this->GetUserById($this->id_user3) ?>
	</td>
	<td id="nbh_<?php echo $this->id_tache?>"><?php echo $this->duree ?></td>
	<td id="nbh_<?php echo $this->id_tache?>">
		<span style="color:red;"><?php echo $this->GetDateDone($this->id_tache) ?></span>
	</td>
	<td></td>
	<td style="text-align: right;">
		<button type="button" class="btn btn-warning" aria-label="Left Align" id="edititemprojet_<?php echo $this->id_tache ?>" style="cursor:pointer;">
			<span class="glyphicon glyphicon-pencil" aria-hidden="true" ></span>
		</button>
		<button type="button" class="btn btn-warning" aria-label="Left Align" id="getCalendar_<?php echo $this->id_tache ?>_<?php echo $this->id_user1 ?>">
			<span class="glyphicon glyphicon-calendar" aria-hidden="true"></span>
		</button>
		<a href="/projets/deletetache/id/<?php echo $this->id_tache?>/id_projet/<?php echo $this->id_projet?>" class="btn btn-danger" aria-label="Left Align">
			<span class="glyphicon glyphicon-trash" aria-hidden="true"></span>
		</a>

	</td>
</tr>