<?php if(count($this->catalogues->toArray())):?>
	<?php foreach($this->catalogues as $catalogue):?>
		<tr class="<?= $catalogue->colorclass ?>" style="display: table;width: 100%;">
			<td width="5%"><?php echo $catalogue->code_me?></td>
			<td width="5%"><?php echo $catalogue->reference?></td>
			<td width="15%"><?php echo $catalogue->fournisseur?></td>
			<td width="5%"><?php echo $catalogue->type?></td>
			<td width="3%"><?php echo $catalogue->epaisseur?></td>
			<td width="10%"><?php echo $catalogue->format?></td>
			<td width="10%"><?php echo $catalogue->surface_totale?></td>
			<td width="28%"><?php echo $catalogue->designation ?></td>
			<td width="6%" style="text-align:right;">
				<?php if(!(int) $catalogue->unitaire):?>
					<?php if($catalogue->prixM2 == null):?>
						<?php echo $catalogue->prixML ?>
					<?php else:?>
						<?php echo $catalogue->prixM2 ?>
					<?php endif;?>
				<?php else:?>
					<?php echo $catalogue->unitaire ?>
				<?php endif;?>
				&nbsp;&euro;
			</td>
			<td width="3%" style="text-align:center;">
				<?php if(!(int) $catalogue->unitaire):?>
					<?php if($catalogue->prixM2 == null):?>
						Ml
					<?php else:?>
						M2
					<?php endif;?>
				<?php else:?>
					Unitaire
				<?php endif;?>
			</td>
			<td width="3%" style="text-align:right;"><?php echo $catalogue->coeff_marge?></td>
			<td width="7%" style="text-align:right;">
                <?php if($this->fromDevis != 0):?>
                    <button type="button" class="btn btn-warning" aria-label="Left Align" id="fill_form_<?php echo $catalogue->id_produit ?>">
                      <span class="glyphicon glyphicon-arrow-right" aria-hidden="true"></span>
                    </button>
                <?php else:?>
                    <button type="button" class="btn btn-primary" aria-label="Left Align" id="fiche_catalogue_<?= $catalogue->id_produit?>">
                        <span class="glyphicon glyphicon-eye-open" aria-hidden="true"></span>
                    </button>
                    <button type="button" class="btn btn-warning" aria-label="Left Align" id="edit_catalogue_<?= $catalogue->id_produit?>">
                        <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>
                    </button>
                    <button type="button" class="btn btn-danger" aria-label="Left Align" id="delete_catalogue_<?= $catalogue->id_produit?>">
                        <span class="glyphicon glyphicon-trash" aria-hidden="true"></span>
                    </button>
                <?php endif;?>
			</td>
		</tr>
	<?php endforeach; ?>
<?php endif; ?>