<?php if($this->client): ?>
	<tr>
		<td></td>
		<td><?php echo $this->client->societe?></td>
		<td><?php echo $this->client->adresse . ' ' . $this->client->codepostal . ' ' . $this->client->ville?></td>
		<td><?php echo $this->client->tel?></td>
		<td>
			<a href="mailto:<?php echo $this->client->mel?>"><?php echo $this->client->mel?></a>
		</td>
		<td style="text-align: right;">
			<button type="button" class="btn btn-primary" aria-label="Left Align" id="fiche_clients_<?php echo $this->client->id_client?>">
			  <span class="glyphicon glyphicon-eye-open" aria-hidden="true"></span>
			</button>
			<button type="button" class="btn btn-warning" aria-label="Left Align" id="edit_clients_<?php echo $this->client->id_client?>">
			  <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>
			</button>
			<button type="button" class="btn btn-danger" aria-label="Left Align" id="delete_clients_<?php echo $this->client->id_client?>">
			  <span class="glyphicon glyphicon-trash" aria-hidden="true"></span>
			</button>
		</td>
	</tr>
<?php else: ?>
	<?php foreach($this->clients as $client): ?>
		<tr>
			<td></td>
			<td><?php echo $client->societe?></td>
			<td><?php echo $client->adresse . ' ' . $client->codepostal . ' ' . $client->ville?></td>
			<td><?php echo $client->tel?></td>
			<td>
				<a href="mailto:<?php echo $client->mel?>"><?php echo $client->mel?></a>
			</td>
			<td style="text-align: right;">
				<button type="button" class="btn btn-primary" aria-label="Left Align" id="fiche_clients_<?php echo $client->id_client?>">
				  <span class="glyphicon glyphicon-eye-open" aria-hidden="true"></span>
				</button>
				<button type="button" class="btn btn-warning" aria-label="Left Align" id="edit_clients_<?php echo $client->id_client?>">
				  <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>
				</button>
				<button type="button" class="btn btn-danger" aria-label="Left Align" id="delete_clients_<?php echo $client->id_client?>">
				  <span class="glyphicon glyphicon-trash" aria-hidden="true"></span>
				</button>
			</td>
		</tr>
	<?php endforeach; ?>
<?php endif; ?>
