<?php
/**
 * Created by PhpStorm.
 * User: alain
 * Date: 29/12/2017
 * Time: 11:12
 */
?>

<div id="panelFaconnage" class="panel panel-primary">
    <div class="panel-heading nav navbar-default">
        <div class="row">
            <div class="col-md-6">
                <h3 class="panel-title" data-toggle="collapse" href="#collapsefaconnages">Façonnage</h3>
            </div>
            <div class="col-md-6">
                <ul class="nav navbar-nav navbar-right navbarPanel">
                    <li id="BtAjoutligneFaconnage" title="Ajouter une ligne">
                        <span class="glyphicon glyphicon-plus"></span>
                    </li>
                    <li id="BtSuprimeligneFaconnage" title="Supprimer le bloc">
                        <span class="glyphicon glyphicon-remove"></span>
                    </li>
                </ul>
            </div>
        </div>
    </div>
    <div id="collapsefaconnages" class="panel-body panel-collapse in">
        <table class="table-produits-devis" id="tableFaconnage">
            <tr>
                <th width="3%">Code</th>
                <th>Faconnage</th>
                <th width="3%">Quantité</th>
                <th width="7%">H.A M2/ML</th>
                <th width="7%">H.A Total</th>
                <th width="7%">Px vente</th>
                <th width="2%"></th>
            </tr>
            <?php if( count($this->itemsFaconnage) == 0): ?>
            <tr id="ligneRefFaconnage"  data-key="ligneRefFaconnage_0">
                <td>
                    <input type="text" name="code"      data-indice="0" title="" onFocus="fctSetFocus();" onkeyup="fctRemplitListeFaconnage(0);" onChange="fctChangeValeurDevisFaconnage();" class="tableCode dropdown-toggle" list="listeFaconnage_0"/>
                    <button type="button" class="btn btn-warning" aria-label="Left Align" onclick="fctOuvreCatalogue(0, 'Faconnage');">
                        <span class="glyphicon glyphicon-lamp" aria-hidden="true"></span>
                    </button>
                    <datalist id="listeFaconnage_0">
                    </datalist>
                    <input type="hidden" name="json_Faconnage[]">
                </td>
                <td><input type="text" name="faconnage" data-indice="0" title="" onFocus="fctSetFocus()" onChange="fctChangeValeurDevisFaconnage();" /></td>
                <td><input type="text" name="qte"       data-indice="0" title="" onFocus="fctSetFocus()" class="inputNumber" onChange="fctChangeValeurDevisFaconnage();" /></td>
                <td><input type="text" name="h.a_ml"    data-indice="0" title="" onFocus="fctSetFocus()" class="inputNumber" onChange="fctChangeValeurDevisFaconnage();" /></td>
                <td><input type="text" name="h.a_total" data-indice="0" title="" onFocus="fctSetFocus()" class="inputNumber" readonly /></td>
                <td><input type="text" name="pxvente"   data-indice="0" title="" onFocus="fctSetFocus()" class="inputNumber" readonly /></td>
                <td><span class="glyphicon glyphicon-trash" aria-hidden="true" onClick="fctSupprimeLigneFaconnage(0);" title="Supprimer la ligne" ></span></td>
            </tr>
            <?php endif; ?>
            <?php if (isset($this->itemsFaconnage)) : ?>
                <?php foreach($this->itemsFaconnage as $key => $faconnage): ?>
                    <?php $json = json_decode($faconnage->json, true) ?>
                <tr id="ligneRefFaconnage"  data-key="ligneRefFaconnage_<?= $key ?>">
                    <td>
                        <input type="text" name="code"      data-indice="<?= $key ?>" title="" onFocus="fctSetFocus();" onkeyup="fctRemplitListeFaconnage(<?= $key ?>);" onChange="fctChangeValeurDevisFaconnage();" class="tableCode dropdown-toggle" list="listeFaconnage_<?= $key ?>" value="<?= $json['code'] ?>"/>
                        <button type="button" class="btn btn-warning" aria-label="Left Align" onclick="fctOuvreCatalogue(<?= $key ?>, 'Faconnage');">
                            <span class="glyphicon glyphicon-lamp" aria-hidden="true"></span>
                        </button>
                        <datalist id="listeFaconnage_<?= $key ?>">
                        </datalist>
                        <input type="hidden" name="json_Faconnage[]" value="<?= json_decode($json) ?>">
                    </td>
                    <td><input type="text" name="faconnage" data-indice="<?= $key ?>" title="" onFocus="fctSetFocus()" onChange="fctChangeValeurDevisFaconnage();" value="<?= $json['faconnage'] ?>"/></td>
                    <td><input type="text" name="qte"       data-indice="<?= $key ?>" title="" onFocus="fctSetFocus()" class="inputNumber" onChange="fctChangeValeurDevisFaconnage();" value="<?= $json['qte'] ?>"/></td>
                    <td><input type="text" name="h.a_ml"    data-indice="<?= $key ?>" title="" onFocus="fctSetFocus()" class="inputNumber" onChange="fctChangeValeurDevisFaconnage();" value="<?= $json['h.a_ml'] ?>"/></td>
                    <td><input type="text" name="h.a_total" data-indice="<?= $key ?>" title="" onFocus="fctSetFocus()" class="inputNumber" readonly value="<?= $json['h.a_total'] ?>"/></td>
                    <td><input type="text" name="pxvente"   data-indice="<?= $key ?>" title="" onFocus="fctSetFocus()" class="inputNumber" readonly value="<?= $json['pxvente'] ?>"/></td>
                    <td><span class="glyphicon glyphicon-trash" aria-hidden="true" onClick="fctSupprimeLigneFaconnage(<?= $key ?>);" title="Supprimer la ligne" ></span></td>
                </tr>
                <?php endforeach; ?>
            <?php endif; ?>
            <tfoot>
                <tr>
                    <td colspan="6">
                        <table class="table-produits-devis">
                            <tr>
                                <td class="titrefooter haTotal">Total support</td>
                                <td class="titrefooter haTotal">H.A Total</td>
                                <td id="h_a_totauxFaconnage" class="haTotal">&nbsp;</td>
                                <td class="titrefooter marge" >Marge</td>
                                <td id="margeFaconnage" class="marge">&nbsp;</td>
                                <td class="titrefooter pxventeTotal">Px vente</td>
                                <td id="totalPxVenteFaconnage" class="pxventeTotal" colspan="2">&nbsp;</td>
                            </tr>
                        </table>
                    </td>
                </tr>
            </tfoot>
        </table>
    </div>
    <div class="elemCache">
        <table>
            <tr id="elemCacheFaconnage">
                <td>
                    <input type="text" name="code"      data-indice="XXX" title="" onFocus="fctSetFocus();" onkeyup="fctRemplitListeFaconnage(XXX);" onChange="fctChangeValeurDevisFaconnage();" class="tableCode dropdown-toggle" list="listeFaconnage_XXX"/>
                    <button type="button" class="btn btn-warning" aria-label="Left Align" onclick="fctOuvreCatalogue(XXX, 'Faconnage');">
                        <span class="glyphicon glyphicon-lamp" aria-hidden="true"></span>
                    </button>
                    <datalist id="listeFaconnage_XXX">
                    </datalist>
                    <input type="hidden" name="json_Faconnage[]">
                </td>
                <td><input type="text" name="faconnage" data-indice="XXX" title="" onFocus="fctSetFocus()" onChange="fctChangeValeurDevisFaconnage();" /></td>
                <td><input type="text" name="qte"       data-indice="XXX" title="" onFocus="fctSetFocus()" class="inputNumber" onChange="fctChangeValeurDevisFaconnage();" /></td>
                <td><input type="text" name="h.a_ml"    data-indice="XXX" title="" onFocus="fctSetFocus()" class="inputNumber" onChange="fctChangeValeurDevisFaconnage();" /></td>
                <td><input type="text" name="h.a_total" data-indice="XXX" title="" onFocus="fctSetFocus()" class="inputNumber" readonly /></td>
                <td><input type="text" name="pxvente"   data-indice="XXX" title="" onFocus="fctSetFocus()" class="inputNumber" readonly /></td>
                <td><span class="glyphicon glyphicon-trash" aria-hidden="true" onClick="fctSupprimeLigneFaconnage(XXX);" title="Supprimer la ligne" ></span></td>
            </tr>
        </table>
    </div>
    <input type="hidden" name="nbLigneFaconnage" id="nbLigneFaconnage" value="<?= count($this->itemsFaconnage) ?>">
</div>