<?php
/**
 * Created by PhpStorm.
 * User: alain
 * Date: 29/12/2017
 * Time: 11:12
 */
?>

<div class="panel panel-primary">
    <div class="panel-heading">
        <h3 class="panel-title" data-toggle="collapse" href="#collapsesoustraitance">Sous-traitance</h3>
    </div>
    <div id="collapsesoustraitance" class="panel-body panel-collapse in">
        <button type="button" id="BtAjoutligneSousTraitance" class="btn btn-default voffset1" title="Ajouter une ligne">
            <span class="glyphicon glyphicon-plus"></span>
        </button>
        <button type="button" id="BtSuprimeligneSousTraitance" class="btn btn-default voffset1" title="Supprimer une ligne">
            <span class="glyphicon glyphicon-minus"></span>
        </button>
        <table class="table-produits-devis" id="tableSousTraitance">
            <tr>
                <th class="txtEntete">Code</th>
                <th>Sous traitance</th>
                <th class="txtEntete">Quantité</th>
                <th>H.A M2/ML</th>
                <th>H.A Total</th>
                <th class="txtEntete">Coef marge</th>
                <th>Px vente</th>
            </tr>
            <?php if( count($this->itemsSousTraitance) == 0): ?>
            <tr id="ligneRefSousTraitance">
                <td>
                    <input type="text" name="code"      title="" onFocus="fctSetFocus();" onkeyup="fctRemplitListeSousTraitance(0);" onChange="fctChangeValeurDevisSousTraitance();" class="dropdown-toggle" list="listeSousTraitance_0"/>
                    <datalist id="listeSousTraitance_0">
                    </datalist>
                    <input type="hidden" name="json_SousTraitance[]">
                </td>
                <td><input type="text" name="support"   title="" onFocus="fctSetFocus()" onChange="fctChangeValeurDevisSousTraitance();"/></td>
                <td><input type="text" name="qte"       title="" onFocus="fctSetFocus()" onChange="fctChangeValeurDevisSousTraitance();"/></td>
                <td><input type="text" name="h.a_ml"    title="" onFocus="fctSetFocus()" onChange="fctChangeValeurDevisSousTraitance();"/></td>
                <td><input type="text" name="h.a_total" title="" onFocus="fctSetFocus()" readonly /></td>
                <td><input type="text" name="coefMarge" title="" onFocus="fctSetFocus()" onChange="fctChangeValeurDevisSousTraitance();"/></td>
                <td><input type="text" name="pxvente"   title="" onFocus="fctSetFocus()" readonly /></td>
            </tr>
            <?php endif; ?>
            <?php foreach($this->itemsSousTraitance as $key => $soustraitance): ?>
                <?php $json = json_decode($soustraitance->json, true) ?>
            <tr id="ligneRefSousTraitance">
                <td>
                    <input type="text" name="code"      title="" onFocus="fctSetFocus();" onkeyup="fctRemplitListeSousTraitance(<?= $key ?>);" onChange="fctChangeValeurDevisSousTraitance();" class="dropdown-toggle" list="listeSousTraitance_<?= $key ?>" value="<?= $json['code'] ?>"/>
                    <datalist id="listeSousTraitance_<?= $key ?>">
                    </datalist>
                    <input type="hidden" name="json_SousTraitance[]" value="<?= json_encode($json) ?>">
                </td>
                <td><input type="text" name="support"   title="" onFocus="fctSetFocus()" onChange="fctChangeValeurDevisSousTraitance();" value="<?= $json['support'] ?>"/></td>
                <td><input type="text" name="qte"       title="" onFocus="fctSetFocus()" onChange="fctChangeValeurDevisSousTraitance();" value="<?= $json['qte'] ?>"/></td>
                <td><input type="text" name="h.a_ml"    title="" onFocus="fctSetFocus()" onChange="fctChangeValeurDevisSousTraitance();" value="<?= $json['h.a_ml'] ?>"/></td>
                <td><input type="text" name="h.a_total" title="" onFocus="fctSetFocus()" readonly value="<?= $json['h.a_total'] ?>"/></td>
                <td><input type="text" name="coefMarge" title="" onFocus="fctSetFocus()" onChange="fctChangeValeurDevisSousTraitance();" value="<?= $json['coefMarge'] ?>"/></td>
                <td><input type="text" name="pxvente"   title="" onFocus="fctSetFocus()" readonly value="<?= $json['pxvente'] ?>"/></td>
            </tr>
            <?php endforeach; ?>
            <tfoot>
                <tr>
                    <td colspan="8">
                        <table class="table-produits-devis">
                            <tr>
                                <td class="titrefooter haTotal">Total support</td>
                                <td class="titrefooter haTotal">H.A Total</td>
                                <td id="h_a_totauxSousTraitance" class="haTotal">&nbsp;</td>
                                <td class="titrefooter marge" >Marge</td>
                                <td id="margeSousTraitance" class="marge">&nbsp;</td>
                                <td class="titrefooter pxventeTotal">Px vente</td>
                                <td id="totalPxVenteSousTraitance" class="pxventeTotal" colspan="2">&nbsp;</td>
                            </tr>
                        </table>
                    </td>
                </tr>
            </tfoot>
        </table>
    </div>
    <div class="elemCache">
        <table>
            <tr id="elemCacheSousTraitance">
                <td>
                    <input type="text" name="code"      title="" onFocus="fctSetFocus();" onkeyup="fctRemplitListeSousTraitance(XXX);" onChange="fctChangeValeurDevisSousTraitance();" class="dropdown-toggle" list="listeSousTraitance_XXX"/>
                    <datalist id="listeSousTraitance_XXX">
                    </datalist>
                    <input type="hidden" name="json_SousTraitance[]">
                </td>
                <td><input type="text" name="support"   title="" onFocus="fctSetFocus()" onChange="fctChangeValeurDevisSousTraitance();" /></td>
                <td><input type="text" name="qte"       title="" onFocus="fctSetFocus()" onChange="fctChangeValeurDevisSousTraitance();" /></td>
                <td><input type="text" name="h.a_ml"    title="" onFocus="fctSetFocus()" onChange="fctChangeValeurDevisSousTraitance();" /></td>
                <td><input type="text" name="h.a_total" title="" onFocus="fctSetFocus()" readonly /></td>
                <td><input type="text" name="coefMarge" title="" onFocus="fctSetFocus()" onChange="fctChangeValeurDevisSousTraitance();" /></td>
                <td><input type="text" name="pxvente"   title="" onFocus="fctSetFocus()" readonly /></td>
            </tr>
        </table>
    </div>
    <input type="hidden" name="nbLigneSousTraitance" id="nbLigneSousTraitance" value="<?= count($this->itemsSousTraitance)+1 ?>">
</div>