<?php
/**
 * Created by PhpStorm.
 * User: alain
 * Date: 29/12/2017
 * Time: 11:12
 */
?>

<div class="panel panel-primary">
    <div class="panel-heading">
        <h3 class="panel-title" data-toggle="collapse" href="#collapseadhesif">Adhésifs</h3>
    </div>
    <div id="collapseadhesif" class="panel-body panel-collapse in">
        <button type="button" id="BtAjoutligneAdhesif" class="btn btn-default voffset1" title="Ajouter une ligne">
            <span class="glyphicon glyphicon-plus"></span>
        </button>
        <button type="button" id="BtSuprimeligneAdhesif" class="btn btn-default voffset1" title="Supprimer une ligne">
            <span class="glyphicon glyphicon-minus"></span>
        </button>
        <table class="table-produits-devis" id="tableAdhesif">
            <tr>
                <th class="txtEntete">Code</th>
                <th>Adhesifs</th>
                <th>Surface</th>
                <th class="txtEntete">Quantité</th>
                <th>H.A M2/ML</th>
                <th>H.A Total</th>
                <th class="txtEntete">Coef Marge</th>
                <th>Px vente</th>
            </tr>
            <?php if(count($this->itemsAdhesif) ==0): ?>
            <tr id="ligneRefAdhesif">
                <td>
                    <input type="text" name="code"      title="" onFocus="fctSetFocus();" onkeyup="fctRemplitListeAdhesif(0);" onChange="fctChangeValeurDevisAdhesif();" class="dropdown-toggle" list="listeAdhesif_0"/>
                    <datalist id="listeAdhesif_0">
                    </datalist>
                </td>
                <td><input type="text" name="adhesif"   title="" onFocus="fctSetFocus()" onChange="fctChangeValeurDevisAdhesif();" /></td>
                <td><input type="text" name="surface"   title="" onFocus="fctSetFocus()" onChange="fctChangeValeurDevisAdhesif();" /></td>
                <td><input type="text" name="qte"       title="" onFocus="fctSetFocus()" onChange="fctChangeValeurDevisAdhesif();" /></td>
                <td><input type="text" name="h.a_ml"    title="" onFocus="fctSetFocus()" onChange="fctChangeValeurDevisAdhesif();" /></td>
                <td><input type="text" name="h.a_total" title="" onFocus="fctSetFocus()" readonly /></td>
                <td><input type="text" name="coefMarge" title="" onFocus="fctSetFocus()" onChange="fctChangeValeurDevisAdhesif();" /></td>
                <td><input type="text" name="pxvente"   title="" onFocus="fctSetFocus()" readonly /></td>
            </tr>
            <?php endif; ?>
            <?php foreach($this->itemsAdhesif as $key => $adhesif): ?>
            <tr id="ligneRefAdhesif">
                <td>
                    <input type="text" name="code"      title="" onFocus="fctSetFocus();" onkeyup="fctRemplitListeAdhesif(<?= $key ?>);" onChange="fctChangeValeurDevisAdhesif();" class="dropdown-toggle" list="listeAdhesif_<?= $key ?>"/>
                    <datalist id="listeAdhesif_<?= $key ?>">
                    </datalist>
                </td>
                <td><input type="text" name="adhesif"   title="" onFocus="fctSetFocus()" onChange="fctChangeValeurDevisAdhesif();" /></td>
                <td><input type="text" name="surface"   title="" onFocus="fctSetFocus()" onChange="fctChangeValeurDevisAdhesif();" /></td>
                <td><input type="text" name="qte"       title="" onFocus="fctSetFocus()" onChange="fctChangeValeurDevisAdhesif();" value="<?= $adhesif->qte ?>" /></td>
                <td><input type="text" name="h.a_ml"    title="" onFocus="fctSetFocus()" onChange="fctChangeValeurDevisAdhesif();" value="<?= $adhesif->pu ?>" /></td>
                <td><input type="text" name="h.a_total" title="" onFocus="fctSetFocus()" readonly /></td>
                <td><input type="text" name="coefMarge" title="" onFocus="fctSetFocus()" onChange="fctChangeValeurDevisAdhesif();"  value="<?= $adhesif->marge ?>"/></td>
                <td><input type="text" name="pxvente"   title="" onFocus="fctSetFocus()" readonly /></td>
            </tr>
            <?php endforeach; ?>
            <tfoot>
                <tr>
                    <td colspan="8">
                        <table class="table-produits-devis">
                            <tr>
                                <td class="titrefooter haTotal">Total support</td>
                                <td class="titrefooter haTotal">H.A Total</td>
                                <td id="h_a_totauxAdhesif" class="haTotal">&nbsp;</td>
                                <td class="titrefooter marge" >Marge</td>
                                <td id="margeAdhesif" class="marge">&nbsp;</td>
                                <td class="titrefooter pxventeTotal">Px vente</td>
                                <td id="totalPxVenteAdhesif" class="pxventeTotal" colspan="2">&nbsp;</td>
                            </tr>
                        </table>
                    </td>
                </tr>
            </tfoot>
        </table>
    </div>
    <div class="elemCache">
        <table>
            <tr id="elemCacheAdhesif">
                <td>
                    <input type="text" name="code"      title="" onFocus="fctSetFocus();" onkeyup="fctRemplitListeAdhesif(XXX);" onChange="fctChangeValeurDevisAdhesif();" class="dropdown-toggle" list="listeAdhesif_XXX"/>
                    <datalist id="listeAdhesif_XXX">
                    </datalist>
                </td>
                <td><input type="text" name="adhesif"   title="" onFocus="fctSetFocus()" onChange="fctChangeValeurDevisAdhesif();" /></td>
                <td><input type="text" name="surface"   title="" onFocus="fctSetFocus()" onChange="fctChangeValeurDevisAdhesif();" /></td>
                <td><input type="text" name="qte"       title="" onFocus="fctSetFocus()" onChange="fctChangeValeurDevisAdhesif();" /></td>
                <td><input type="text" name="h.a_ml"    title="" onFocus="fctSetFocus()" onChange="fctChangeValeurDevisAdhesif();" /></td>
                <td><input type="text" name="h.a_total" title="" onFocus="fctSetFocus()" readonly /></td>
                <td><input type="text" name="coefMarge" title="" onFocus="fctSetFocus()" onChange="fctChangeValeurDevisAdhesif();" /></td>
                <td><input type="text" name="pxvente"   title="" onFocus="fctSetFocus()" readonly /></td>
            </tr>
        </table>
    </div>
    <input type="hidden" name="nbLigneAdhesif" id="nbLigneAdhesif" value="<?= count($this->itemsAdhesif)+1 ?>">
</div>