<?php
/**
 * Created by PhpStorm.
 * User: alain
 * Date: 29/12/2017
 * Time: 11:12
 */
?>

<div class="panel panel-primary">
    <div class="panel-heading">
        <h3 class="panel-title">Prestations</h3>
    </div>
    <div class="panel-body">
        <button type="button" id="BtAjoutlignePrestation" class="btn btn-default voffset1" title="Ajouter une ligne">
            <span class="glyphicon glyphicon-plus"></span>
        </button>
        <button type="button" id="BtSuprimelignePrestation" class="btn btn-default voffset1" title="Supprimer une ligne">
            <span class="glyphicon glyphicon-minus"></span>
        </button>
        <table class="table-produits-devis" id="tablePrestation">
            <tr>
                <th>Code</th>
                <th>Presation</th>
                <th>Quantité</th>
                <th>Tarif</th>
                <th>Px vente</th>
            </tr>
            <tr id="ligneRefPrestation">
                <td><input type="text" name="code"          title="" onFocus="fctSetFocus()"  onChange="fctChangeValeurDevisPrestation();"  /></td>
                <td><input type="text" name="prestation"    title="" onFocus="fctSetFocus()" onChange="fctChangeValeurDevisPrestation();" /></td>
                <td><input type="text" name="qte"           title="" onFocus="fctSetFocus()" onChange="fctChangeValeurDevisPrestation();" /></td>
                <td><input type="text" name="tarif"         title="" onFocus="fctSetFocus()" onChange="fctChangeValeurDevisPrestation();" /></td>
                <td><input type="text" name="pxvente"       title="" onFocus="fctSetFocus()" readonly /></td>
            </tr>
            <tfoot>
                <tr>
                    <td colspan="5">
                        <table class="table-produits-devis">
                            <tr>
                                <td class="titrefooter haTotal">Total support</td>
                                <td class="titrefooter haTotal">H.A Total</td>
                                <td id="h_a_totauxPrestation" class="haTotal">&nbsp;</td>
                                <td class="titrefooter marge" >Marge</td>
                                <td id="margePrestation" class="marge">&nbsp;</td>
                                <td class="titrefooter pxventeTotal">Px vente</td>
                                <td id="totalPxVentePrestation" class="pxventeTotal" colspan="2">&nbsp;</td>
                            </tr>
                        </table>
                    </td>
                </tr>
            </tfoot>
        </table>
    </div>
    <div class="elemCache">
        <table>
            <tr id="elemCachePrestation">
                <td><input type="text" name="code"          title="" onFocus="fctSetFocus()" onChange="fctChangeValeurDevisPrestation();" /></td>
                <td><input type="text" name="prestation"    title="" onFocus="fctSetFocus()" onChange="fctChangeValeurDevisPrestation();" /></td>
                <td><input type="text" name="qte"           title="" onFocus="fctSetFocus()" onChange="fctChangeValeurDevisPrestation();" /></td>
                <td><input type="text" name="tarif"         title="" onFocus="fctSetFocus()" onChange="fctChangeValeurDevisPrestation();" /></td>
                <td><input type="text" name="pxvente"       title="" onFocus="fctSetFocus()" readonly /></td>
            </tr>
        </table>
    </div>

</div>