<?php
/**
 * Created by PhpStorm.
 * User: alain
 * Date: 29/12/2017
 * Time: 11:12
 */
?>

<div class="panel panel-primary">
    <div class="panel-heading nav navbar-default">
        <div class="row">
            <div class="col-md-6">
                <h3 class="panel-title" data-toggle="collapse" href="#collapseprestations">Prestations</h3>
            </div>
            <div class="col-md-6">
                <ul class="nav navbar-nav navbar-right navbarPanel">
                    <li id="BtAjoutlignePrestation" title="Ajouter une ligne">
                        <span class="glyphicon glyphicon-plus"></span>
                    </li>
                    <li id="BtSuprimelignePrestation" title="Supprimer une ligne">
                        <span class="glyphicon glyphicon-minus"></span>
                    </li>
                </ul>
            </div>
        </div>
    </div>
    <div id="collapseprestations" class="panel-body panel-collapse in">
        <table class="table-produits-devis" id="tablePrestation">
            <tr>
                <th>Code</th>
                <th>Presation</th>
                <th>Quantité</th>
                <th>Tarif</th>
                <th>Px vente</th>
            </tr>
            <?php if( count($this->itemsPrestation) == 0): ?>
            <tr id="ligneRefPrestation">
                <td>
                    <input type="text" name="code"      title="" onFocus="fctSetFocus();" onkeyup="fctRemplitListePrestation(0);" onChange="fctChangeValeurDevisPrestation();" class="dropdown-toggle" list="listePrestation_0"/>
                    <datalist id="listePrestation_0">
                    </datalist>
                    <input type="hidden" name="json_Prestation[]">
                </td>
                <td><input type="text" name="prestation"    title="" onFocus="fctSetFocus()" onChange="fctChangeValeurDevisPrestation();" /></td>
                <td><input type="text" name="qte"           title="" onFocus="fctSetFocus()" class="inputNumber" onChange="fctChangeValeurDevisPrestation();" /></td>
                <td><input type="text" name="tarif"         title="" onFocus="fctSetFocus()" class="inputNumber" onChange="fctChangeValeurDevisPrestation();" /></td>
                <td><input type="text" name="pxvente"       title="" onFocus="fctSetFocus()" class="inputNumber" readonly /></td>
            </tr>
            <?php endif; ?>
            <?php if (isset($this->itemsPrestation)) : ?>
                <?php foreach($this->itemsPrestation as $key => $presta): ?>
                    <?php $json = json_decode($presta->json, true) ?>
                <tr id="ligneRefPrestation">
                    <td>
                        <input type="text" name="code"      title="" onFocus="fctSetFocus();" onkeyup="fctRemplitListePrestation(<?= $key ?>);" onChange="fctChangeValeurDevisPrestation();" class="dropdown-toggle" list="listePrestation_<?= $key ?>"  value="<?= $json['code'] ?>"/>
                        <datalist id="listePrestation_<?= $key ?>">
                        </datalist>
                        <input type="hidden" name="json_Prestation[]"  value="<?= json_encode($json) ?>">
                    </td>
                    <td><input type="text" name="prestation"    title="" onFocus="fctSetFocus()" onChange="fctChangeValeurDevisPrestation();"  value="<?= $json['prestation'] ?>"/></td>
                    <td><input type="text" name="qte"           title="" onFocus="fctSetFocus()" class="inputNumber" onChange="fctChangeValeurDevisPrestation();"  value="<?= $json['qte'] ?>" /></td>
                    <td><input type="text" name="tarif"         title="" onFocus="fctSetFocus()" class="inputNumber" onChange="fctChangeValeurDevisPrestation();"  value="<?= $json['tarif'] ?>" /></td>
                    <td><input type="text" name="pxvente"       title="" onFocus="fctSetFocus()" class="inputNumber" readonly  value="<?= $json['pxvente'] ?>"/></td>
                </tr>
                <?php endforeach; ?>
            <?php endif; ?>
            <tfoot>
                <tr>
                    <td colspan="5">
                        <table class="table-produits-devis">
                            <tr>
                                <td class="titrefooter haTotal">Total support</td>
                                <td class="titrefooter haTotal">H.A Total</td>
                                <td id="h_a_totauxPrestation" class="haTotal">&nbsp;</td>
                                <td class="titrefooter marge" >Marge</td>
                                <td id="margePrestation" class="marge">&nbsp;</td>
                                <td class="titrefooter pxventeTotal">Px vente</td>
                                <td id="totalPxVentePrestation" class="pxventeTotal" colspan="2">&nbsp;</td>
                            </tr>
                        </table>
                    </td>
                </tr>
            </tfoot>
        </table>
    </div>
    <div class="elemCache">
        <table>
            <tr id="elemCachePrestation">
                <td>
                    <input type="text" name="code"      title="" onFocus="fctSetFocus();" onkeyup="fctRemplitListePrestation(XXX);" onChange="fctChangeValeurDevisPrestation();" class="dropdown-toggle" list="listePrestation_XXX"/>
                    <datalist id="listePrestation_XXX">
                    </datalist>
                    <input type="hidden" name="json_Prestation[]">
                </td>
                <td><input type="text" name="prestation"    title="" onFocus="fctSetFocus()" onChange="fctChangeValeurDevisPrestation();" /></td>
                <td><input type="text" name="qte"           title="" onFocus="fctSetFocus()" class="inputNumber" onChange="fctChangeValeurDevisPrestation();" /></td>
                <td><input type="text" name="tarif"         title="" onFocus="fctSetFocus()" class="inputNumber" onChange="fctChangeValeurDevisPrestation();" /></td>
                <td><input type="text" name="pxvente"       title="" onFocus="fctSetFocus()" class="inputNumber" readonly /></td>
            </tr>
        </table>
    </div>
    <input type="hidden" name="nbLignePrestation" id="nbLignePrestation" value="<?= count($this->itemsPrestation)+1 ?>">
</div>