<?php
/**
 * Created by PhpStorm.
 * User: alain
 * Date: 29/12/2017
 * Time: 11:12
 */
?>

<div class="panel panel-primary">
    <div class="panel-heading nav navbar-default">
        <div class="row">
            <div class="col-md-6">
                <h3 class="panel-title" data-toggle="collapse" href="#collapsefaconnages">Façonnage</h3>
            </div>
            <div class="col-md-6">
                <ul class="nav navbar-nav navbar-right navbarPanel">
                    <li id="BtAjoutligneFaconnage" title="Ajouter une ligne">
                        <span class="glyphicon glyphicon-plus"></span>
                    </li>
                    <li id="BtSuprimeligneFaconnage" title="Supprimer une ligne">
                        <span class="glyphicon glyphicon-minus"></span>
                    </li>
                </ul>
            </div>
        </div>
    </div>
    <div id="collapsefaconnages" class="panel-body panel-collapse in">
        <table class="table-produits-devis" id="tableFaconnage">
            <tr>
                <th class="txtEntete">Code</th>
                <th>Faconnage</th>
                <th class="txtEntete">Quantité</th>
                <th>H.A M2/ML</th>
                <th>H.A Total</th>
                <th>Px vente</th>
            </tr>
            <?php if( count($this->itemsFaconnage) == 0): ?>
            <tr id="ligneRefFaconnage">
                <td>
                    <input type="text" name="code"      title="" onFocus="fctSetFocus();" onkeyup="fctRemplitListeFaconnage(0);" onChange="fctChangeValeurDevisFaconnage();" class="dropdown-toggle" list="listeFaconnage_0"/>
                    <datalist id="listeFaconnage_0">
                    </datalist>
                    <input type="hidden" name="json_Faconnage[]">
                </td>
                <td><input type="text" name="faconnage" title="" onFocus="fctSetFocus()" onChange="fctChangeValeurDevisFaconnage();" /></td>
                <td><input type="text" name="qte"       title="" onFocus="fctSetFocus()" class="inputNumber" onChange="fctChangeValeurDevisFaconnage();" /></td>
                <td><input type="text" name="h.a_ml"    title="" onFocus="fctSetFocus()" class="inputNumber" onChange="fctChangeValeurDevisFaconnage();" /></td>
                <td><input type="text" name="h.a_total" title="" onFocus="fctSetFocus()" class="inputNumber" readonly /></td>
                <td><input type="text" name="pxvente"   title="" onFocus="fctSetFocus()" class="inputNumber" readonly /></td>
            </tr>
            <?php endif; ?>
            <?php foreach($this->itemsFaconnage as $key => $faconnage): ?>
                <?php $json = json_decode($faconnage->json, true) ?>
            <tr id="ligneRefFaconnage">
                <td>
                    <input type="text" name="code"      title="" onFocus="fctSetFocus();" onkeyup="fctRemplitListeFaconnage(<?= $key ?>);" onChange="fctChangeValeurDevisFaconnage();" class="dropdown-toggle" list="listeFaconnage_<?= $key ?>" value="<?= $json['code'] ?>"/>
                    <datalist id="listeFaconnage_<?= $key ?>">
                    </datalist>
                    <input type="hidden" name="json_Faconnage[]" value="<?= json_decode($json) ?>">
                </td>
                <td><input type="text" name="faconnage" title="" onFocus="fctSetFocus()" onChange="fctChangeValeurDevisFaconnage();" value="<?= $json['faconnage'] ?>"/></td>
                <td><input type="text" name="qte"       title="" onFocus="fctSetFocus()" class="inputNumber" onChange="fctChangeValeurDevisFaconnage();" value="<?= $json['qte'] ?>"/></td>
                <td><input type="text" name="h.a_ml"    title="" onFocus="fctSetFocus()" class="inputNumber" onChange="fctChangeValeurDevisFaconnage();" value="<?= $json['h.a_ml'] ?>"/></td>
                <td><input type="text" name="h.a_total" title="" onFocus="fctSetFocus()" class="inputNumber" readonly value="<?= $json['h.a_total'] ?>"/></td>
                <td><input type="text" name="pxvente"   title="" onFocus="fctSetFocus()" class="inputNumber" readonly value="<?= $json['pxvente'] ?>"/></td>
            </tr>
            <?php endforeach; ?>
            <tfoot>
                <tr>
                    <td colspan="6">
                        <table class="table-produits-devis">
                            <tr>
                                <td class="titrefooter haTotal">Total support</td>
                                <td class="titrefooter haTotal">H.A Total</td>
                                <td id="h_a_totauxFaconnage" class="haTotal">&nbsp;</td>
                                <td class="titrefooter marge" >Marge</td>
                                <td id="margeFaconnage" class="marge">&nbsp;</td>
                                <td class="titrefooter pxventeTotal">Px vente</td>
                                <td id="totalPxVenteFaconnage" class="pxventeTotal" colspan="2">&nbsp;</td>
                            </tr>
                        </table>
                    </td>
                </tr>
            </tfoot>
        </table>
    </div>
    <div class="elemCache">
        <table>
            <tr id="elemCacheFaconnage">
                <td>
                    <input type="text" name="code"      title="" onFocus="fctSetFocus();" onkeyup="fctRemplitListeFaconnage(XXX);" onChange="fctChangeValeurDevisFaconnage();" class="dropdown-toggle" list="listeFaconnage_XXX"/>
                    <datalist id="listeFaconnage_XXX">
                    </datalist>
                    <input type="hidden" name="json_Faconnage[]">
                </td>
                <td><input type="text" name="faconnage" title="" onFocus="fctSetFocus()" onChange="fctChangeValeurDevisFaconnage();" /></td>
                <td><input type="text" name="qte"       title="" onFocus="fctSetFocus()" class="inputNumber" onChange="fctChangeValeurDevisFaconnage();" /></td>
                <td><input type="text" name="h.a_ml"    title="" onFocus="fctSetFocus()" class="inputNumber" onChange="fctChangeValeurDevisFaconnage();" /></td>
                <td><input type="text" name="h.a_total" title="" onFocus="fctSetFocus()" class="inputNumber" readonly /></td>
                <td><input type="text" name="pxvente"   title="" onFocus="fctSetFocus()" class="inputNumber" readonly /></td>
            </tr>
        </table>
    </div>
    <input type="hidden" name="nbLigneFaconnage" id="nbLigneFaconnage" value="<?= count($this->itemsFaconnage)+1 ?>">
</div>