<?php
/**
 * Created by PhpStorm.
 * User: alain
 * Date: 29/12/2017
 * Time: 11:12
 */
?>

<div class="panel panel-primary">
    <div class="panel-heading nav navbar-default">
        <div class="row">
            <div class="col-md-6">
                <h3 class="panel-title" data-toggle="collapse" href="#collapsefraistechniques">Frais Techniques</h3>
            </div>
            <div class="col-md-6">
                <ul class="nav navbar-nav navbar-right navbarPanel">
                    <li id="BtAjoutligneFraisTechnique" title="Ajouter une ligne">
                        <span class="glyphicon glyphicon-plus"></span>
                    </li>
                    <!--
                    <li id="BtSuprimeligneFraisTechnique" title="Supprimer une ligne">
                        <span class="glyphicon glyphicon-minus"></span>
                    </li>
                    -->
                </ul>
            </div>
        </div>
    </div>
    <div id="collapsefraistechniques" class="panel-body panel-collapse in">
        <table class="table-produits-devis" id="tableFraisTechnique">
            <tr>
                <th>Code</th>
                <th>Frais Techniques</th>
                <th>Taux</th>
                <th>Heures</th>
                <th>Minutes</th>
                <th>Tarif horaire</th>
                <th>Tarif minute</th>
                <th>Px vente</th>
            </tr>
            <?php if( count($this->itemsFraisTechnique) == 0): ?>
            <tr id="ligneRefFraisTechnique"  data-key="ligneRefFraisTechnique_0">
                <td>
                    <input type="text" name="code"      title="" onFocus="fctSetFocus();" onkeyup="fctRemplitListeFraisTechnique(0);" onChange="fctChangeValeurDevisFraisTechnique();" class="dropdown-toggle" list="listeFraisTechnique_0"/>
                    <datalist id="listeFraisTechnique_0">
                    </datalist>
                    <input type="hidden" name="json_FraisTechnique[]">
                </td>
                <td><input type="text" name="fraisTechnique"    title="" onFocus="fctSetFocus()" onChange="fctChangeValeurDevisFraisTechnique();" /></td>
                <td><input type="text" name="taux"              title="" onFocus="fctSetFocus()" class="inputNumber" onChange="fctChangeValeurDevisFraisTechnique();" /></td>
                <td><input type="text" name="heures"            title="" onFocus="fctSetFocus()" class="inputNumber" onChange="fctChangeValeurDevisFraisTechnique();" /></td>
                <td><input type="text" name="minutes"           title="" onFocus="fctSetFocus()" class="inputNumber" onChange="fctChangeValeurDevisFraisTechnique();" /></td>
                <td><input type="text" name="tarifHoraire"      title="" onFocus="fctSetFocus()" class="inputNumber" readonly /></td>
                <td><input type="text" name="tarifMinute"       title="" onFocus="fctSetFocus()" class="inputNumber" readonly /></td>
                <td><input type="text" name="pxvente"           title="" onFocus="fctSetFocus()" class="inputNumber" readonly /></td>
                <td><span class="glyphicon glyphicon-trash" aria-hidden="true" onClick="fctSupprimeLigneFraisTechnique(0);" title="Supprimer la ligne" ></span></td>
            </tr>
            <?php endif; ?>
            <?php if (isset($this->itemsFraisTechnique)) : ?>
                <?php foreach($this->itemsFraisTechnique as $key => $fraistechnique): ?>
                    <?php $json = json_decode($fraistechnique->json, true) ?>
                <tr id="ligneRefFraisTechnique"  data-key="ligneRefFraisTechnique_<?= $key ?>">
                    <td>
                        <input type="text" name="code"      title="" onFocus="fctSetFocus();" onkeyup="fctRemplitListeFraisTechnique(<?= $key ?>);" onChange="fctChangeValeurDevisFraisTechnique();" class="dropdown-toggle" list="listeFraisTechnique_<?= $key ?>" value="<?= $json['code'] ?>"/>
                        <datalist id="listeFraisTechnique_<?= $key ?>">
                        </datalist>
                        <input type="hidden" name="json_FraisTechnique[]" value="<?= json_encode($json) ?>">
                    </td>
                    <td><input type="text" name="fraisTechnique"    title="" onFocus="fctSetFocus()" onChange="fctChangeValeurDevisFraisTechnique();" value="<?= $json['fraistechnique'] ?>"/></td>
                    <td><input type="text" name="taux"              title="" onFocus="fctSetFocus()" class="inputNumber" onChange="fctChangeValeurDevisFraisTechnique();" value="<?= $json['taux'] ?>"/></td>
                    <td><input type="text" name="heures"            title="" onFocus="fctSetFocus()" class="inputNumber" onChange="fctChangeValeurDevisFraisTechnique();" value="<?= $json['heures'] ?>"/></td>
                    <td><input type="text" name="minutes"           title="" onFocus="fctSetFocus()" class="inputNumber" onChange="fctChangeValeurDevisFraisTechnique();" value="<?= $json['minutes'] ?>"/></td>
                    <td><input type="text" name="tarifHoraire"      title="" onFocus="fctSetFocus()" class="inputNumber" readonly value="<?= $json['tarifhoraire'] ?>"/></td>
                    <td><input type="text" name="tarifMinute"       title="" onFocus="fctSetFocus()" class="inputNumber" readonly value="<?= $json['tarifminute'] ?>"/></td>
                    <td><input type="text" name="pxvente"           title="" onFocus="fctSetFocus()" class="inputNumber" readonly value="<?= $json['pxvente'] ?>"/></td>
                    <td><span class="glyphicon glyphicon-trash" aria-hidden="true" onClick="fctSupprimeLigneFraisTechnique(<?= $key ?>);" title="Supprimer la ligne" ></span></td>
                </tr>
                <?php endforeach; ?>
            <?php endif; ?>
            <tfoot>
                <tr>
                    <td colspan="8">
                        <table class="table-produits-devis">
                            <tr>
                                <td class="titrefooter haTotal">Total support</td>
                                <td class="titrefooter haTotal">H.A Total</td>
                                <td id="h_a_totauxFraisTechnique" class="haTotal">&nbsp;</td>
                                <td class="titrefooter marge" >Marge</td>
                                <td id="margeFraisTechnique" class="marge">&nbsp;</td>
                                <td class="titrefooter pxventeTotal">Px vente</td>
                                <td id="totalPxVenteFraisTechnique" class="pxventeTotal" colspan="2">&nbsp;</td>
                            </tr>
                        </table>
                    </td>
                </tr>
            </tfoot>
        </table>
    </div>
    <div class="elemCache">
        <table>
            <tr id="elemCacheFraisTechnique">
                <td>
                    <input type="text" name="code"      title="" onFocus="fctSetFocus();" onkeyup="fctRemplitListeFraisTechnique(XXX);" onChange="fctChangeValeurDevisFraisTechnique();" class="dropdown-toggle" list="listeFraisTechnique_XXX"/>
                    <datalist id="listeFraisTechnique_XXX">
                    </datalist>
                    <input type="hidden" name="json_FraisTechnique[]">
                </td>
                <td><input type="text" name="fraisTechnique"    title="" onFocus="fctSetFocus()" onChange="fctChangeValeurDevisFraisTechnique();" /></td>
                <td><input type="text" name="taux"              title="" onFocus="fctSetFocus()" class="inputNumber" onChange="fctChangeValeurDevisFraisTechnique();" /></td>
                <td><input type="text" name="heures"            title="" onFocus="fctSetFocus()" class="inputNumber" onChange="fctChangeValeurDevisFraisTechnique();" /></td>
                <td><input type="text" name="minutes"           title="" onFocus="fctSetFocus()" class="inputNumber" onChange="fctChangeValeurDevisFraisTechnique();" /></td>
                <td><input type="text" name="tarifHoraire"      title="" onFocus="fctSetFocus()" class="inputNumber" readonly /></td>
                <td><input type="text" name="tarifMinute"       title="" onFocus="fctSetFocus()" class="inputNumber" readonly /></td>
                <td><input type="text" name="pxvente"           title="" onFocus="fctSetFocus()" class="inputNumber" readonly /></td>
                <td><span class="glyphicon glyphicon-trash" aria-hidden="true" onClick="fctSupprimeLigneFraisTechnique(XXX);" title="Supprimer la ligne" ></span></td>
            </tr>
        </table>
    </div>
    <input type="hidden" name="nbLigneFraisTechnique" id="nbLigneFraisTechnique" value="<?= count($this->itemsFraisTechnique) ?>">
</div>