<?php
/**
 * Created by PhpStorm.
 * User: alain
 * Date: 29/12/2017
 * Time: 11:12
 */
?>

<div class="panel panel-primary">
    <div class="panel-heading" >
        <h3 class="panel-title" data-toggle="collapse" href="#collapseproduit">Produits</h3>
    </div>
    <div id="collapseproduit" class="panel-body panel-collapse in">
            <button type="button" id="BtAjoutligneProduit" class="btn btn-default voffset1" title="Ajouter une ligne">
                <span class="glyphicon glyphicon-plus"></span>
            </button>
            <button type="button" id="BtSuprimeligneProduit" class="btn btn-default voffset1" title="Supprimer une ligne">
                <span class="glyphicon glyphicon-minus"></span>
            </button>
            <table class="table-produits-devis" id="tableProduit">
                <tr>
                    <th class="txtEntete">Code</th>
                    <th>Support</th>
                    <th>Format</th>
                    <th class="txtEntete">Quantité</th>
                    <th>H.A M2/ML</th>
                    <th>H.A Total</th>
                    <th class="txtEntete">Coef marge</th>
                    <th>Px vente</th>
                </tr>
                <?php foreach($this->itemsProduits as $key => $produit): ?>
                <tr id="ligneRefProduit">
                    <td>
                        <input type="text" name="code"      title="" onFocus="fctSetFocus();" onkeyup="fctRemplitListeProduit(<?= $key ?>);" onChange="fctChangeValeurDevisProduit();" class="dropdown-toggle" list="listeProduit_<?= $key ?>"/>
                        <datalist id="listeProduit_<?= $key ?>">
                        </datalist>
                    </td>
                    <td><input type="text" name="support"   title="" onFocus="fctSetFocus();" onChange="fctChangeValeurDevisProduit();" /></td>
                    <td><input type="text" name="format"    title="" onFocus="fctSetFocus();" onChange="fctChangeValeurDevisProduit();" /></td>
                    <td><input type="text" name="qte"       title="" onFocus="fctSetFocus();" onChange="fctChangeValeurDevisProduit();" class="inputNumber" value="<?= $produit->qte ?>"/></td>
                    <td><input type="text" name="h.a_ml"    title="" onFocus="fctSetFocus();" onChange="fctChangeValeurDevisProduit();" class="inputNumber" value="<?= $produit->pu ?>"/></td>
                    <td><input type="text" name="h.a_total" title="" onFocus="fctSetFocus();" readonly  class="inputNumber" /></td>
                    <td><input type="text" name="coefMarge" title="" onChange="fctChangeValeurDevisProduit();" class="inputNumber" value="<?= $produit->marge ?>"/></td>
                    <td><input type="text" name="pxvente"   title="" readonly class="inputNumber"/></td>
                </tr>
                <?php endforeach; ?>
                <tfoot>
                    <tr>
                        <td colspan="9">
                            <table class="table-produits-devis">
                                <tr>
                                    <td class="titrefooter haTotal">Total support</td>
                                    <td class="titrefooter haTotal">H.A Total</td>
                                    <td id="h_a_totauxProduit" class="haTotal">&nbsp;</td>
                                    <td class="titrefooter marge" >Marge</td>
                                    <td id="margeProduit" class="marge">&nbsp;</td>
                                    <td class="titrefooter pxventeTotal">Px vente</td>
                                    <td id="totalPxVenteProduit" class="pxventeTotal" colspan="2">&nbsp;</td>
                                </tr>
                            </table>
                        </td>
                    </tr>
                </tfoot>
            </table>
        </div>
        <div class="elemCache">
            <table>
                <tr id="elemCacheProduit">
                    <td>
                        <input type="text" name="code"      title="" onFocus="fctSetFocus();" onkeyup="fctRemplitListeProduit(XXX);" onChange="fctChangeValeurDevisProduit();" class="dropdown-toggle" list="listeProduit_XXX"/>
                        <datalist id="listeProduit_XXX">
                        </datalist>
                    </td>
                    <td><input type="text" name="support"   title="" onFocus="fctSetFocus();" onChange="fctChangeValeurDevisProduit();" /></td>
                    <td><input type="text" name="format"    title="" onFocus="fctSetFocus();" onChange="fctChangeValeurDevisProduit();" /></td>
                    <td><input type="text" name="qte"       title="" onFocus="fctSetFocus();" onChange="fctChangeValeurDevisProduit();" class="inputNumber" /></td>
                    <td><input type="text" name="h.a_ml"    title="" onFocus="fctSetFocus();" onChange="fctChangeValeurDevisProduit();" class="inputNumber" /></td>
                    <td><input type="text" name="h.a_total" title="" onFocus="fctSetFocus();" readonly  class="inputNumber" /></td>
                    <td><input type="text" name="coefMarge" title="" onChange="fctChangeValeurDevisProduit();" class="inputNumber"/></td>
                    <td><input type="text" name="pxvente"   title="" readonly class="inputNumber"/></td>
                </tr>
            </table>
        </div>
    <input type="hidden" name="nbLigneProduit" id="nbLigneProduit" value="<?= count($this->itemsProduits)+1 ?>">
</div>
