<?php
/**
 * Created by PhpStorm.
 * User: alain
 * Date: 29/12/2017
 * Time: 11:12
 */
?>

<div id="panelPose" class="panel panel-primary">
    <div class="panel-heading nav navbar-default">
        <div class="row">
            <div class="col-md-6">
                <h3 class="panel-title" data-toggle="collapse" href="#collapsepose">Pose</h3>
            </div>
            <div class="col-md-6">
                <ul class="nav navbar-nav navbar-right navbarPanel">
                    <li id="BtAjoutlignePose" title="Ajouter une ligne">
                        <span class="glyphicon glyphicon-plus"></span>
                    </li>
                    <li id="BtSuprimelignePose" title="Supprimer le bloc">
                        <span class="glyphicon glyphicon-remove"></span>
                    </li>
                </ul>
            </div>
        </div>
    </div>
    <div id="collapsepose" class="panel-body panel-collapse in">
        <table class="table-produits-devis" id="tablePose">
            <tr>
                <th>Code</th>
                <th>Pose</th>
                <th>Quantité</th>
                <th>H.A M2/ML</th>
                <th>H.A Total</th>
                <th>Coef Marge</th>
                <th>Px vente</th>
            </tr>
            <?php if( count($this->itemsPose) == 0): ?>
            <tr id="ligneRefPose"  data-key="ligneRefPose_0">
                <td>
                    <input type="text" name="code"      title="" onFocus="fctSetFocus();" onkeyup="fctRemplitListePose(0);" onChange="fctChangeValeurDevisPose();" class="dropdown-toggle" list="listePose_0"/>
                    <datalist id="listePose_0">
                    </datalist>
                    <input type="hidden" name="json_Pose[]">
                </td>
                <td><input type="text" name="pose"      title="" onFocus="fctSetFocus()" onChange="fctChangeValeurDevisPose();"/></td>
                <td><input type="text" name="qte"       title="" onFocus="fctSetFocus()" class="inputNumber" onChange="fctChangeValeurDevisPose();"/></td>
                <td><input type="text" name="h.a_ml"    title="" onFocus="fctSetFocus()" class="inputNumber" onChange="fctChangeValeurDevisPose();"/></td>
                <td><input type="text" name="h.a_total" title="" onFocus="fctSetFocus()" class="inputNumber" readonly /></td>
                <td><input type="text" name="coefMarge" title="" onFocus="fctSetFocus()" class="inputNumber" onChange="fctChangeValeurDevisPose();"/></td>
                <td><input type="text" name="pxvente"   title="" onFocus="fctSetFocus()" class="inputNumber" readonly /></td>
                <td><span class="glyphicon glyphicon-trash" aria-hidden="true" onClick="fctSupprimeLignePose(0);" title="Supprimer la ligne" ></span></td>
            </tr>
            <?php endif; ?>
            <?php if (isset($this->itemsPose)) : ?>
                <?php foreach($this->itemsPose as $key => $pose): ?>
                    <?php $json = json_decode($pose->json, true) ?>
                <tr id="ligneRefPose"  data-key="ligneRefPose_<?= $key ?>">
                    <td>
                        <input type="text" name="code"      title="" onFocus="fctSetFocus();" onkeyup="fctRemplitListePose(<?=$key ?>);" onChange="fctChangeValeurDevisPose();" class="dropdown-toggle" list="listePose_<?=$key ?>" value="<?= $json['code'] ?>"/>
                        <datalist id="listePose_<?=$key ?>">
                        </datalist>
                        <input type="hidden" name="json_Pose[]" value="<?= json_decode($json) ?>">
                    </td>
                    <td><input type="text" name="pose"      title="" onFocus="fctSetFocus()" onChange="fctChangeValeurDevisPose();" value="<?= $json['pose'] ?>"/></td>
                    <td><input type="text" name="qte"       title="" onFocus="fctSetFocus()" class="inputNumber" onChange="fctChangeValeurDevisPose();" value="<?= $json['qte'] ?>"/></td>
                    <td><input type="text" name="h.a_ml"    title="" onFocus="fctSetFocus()" class="inputNumber" onChange="fctChangeValeurDevisPose();" value="<?= $json['h.a_ml'] ?>"/></td>
                    <td><input type="text" name="h.a_total" title="" onFocus="fctSetFocus()" class="inputNumber" readonly value="<?= $json['h.a_total'] ?>"/></td>
                    <td><input type="text" name="coefMarge" title="" onFocus="fctSetFocus()" class="inputNumber" onChange="fctChangeValeurDevisPose();" value="<?= $json['coefmarge'] ?>"/></td>
                    <td><input type="text" name="pxvente"   title="" onFocus="fctSetFocus()" class="inputNumber" readonly value="<?= $json['pxvente'] ?>"/></td>
                    <td><span class="glyphicon glyphicon-trash" aria-hidden="true" onClick="fctSupprimeLignePose(<?= $key ?>);" title="Supprimer la ligne" ></span></td>
                </tr>
                <?php endforeach; ?>
            <?php endif; ?>
            <tfoot>
                <tr>
                    <td colspan="7">
                        <table class="table-produits-devis">
                            <tr>
                                <td class="titrefooter haTotal">Total support</td>
                                <td class="titrefooter haTotal">H.A Total</td>
                                <td id="h_a_totauxPose" class="haTotal">&nbsp;</td>
                                <td class="titrefooter marge" >Marge</td>
                                <td id="margePose" class="marge">&nbsp;</td>
                                <td class="titrefooter pxventeTotal">Px vente</td>
                                <td id="totalPxVentePose" class="pxventeTotal" colspan="2">&nbsp;</td>
                            </tr>
                        </table>
                    </td>
                </tr>
            </tfoot>
        </table>

    </div>

    <div class="elemCache">
        <table>
            <tr id="elemCachePose">
                <td>
                    <input type="text" name="code"      title="" onFocus="fctSetFocus();" onkeyup="fctRemplitListePose(XXX);" onChange="fctChangeValeurDevisPose();" class="dropdown-toggle" list="listePose_XXX"/>
                    <datalist id="listePose_XXX">
                    </datalist>
                    <input type="hidden" name="json_Pose[]">
                </td>
                <td><input type="text" name="pose"      title="" onFocus="fctSetFocus()" onChange="fctChangeValeurDevisPose();"/></td>
                <td><input type="text" name="qte"       title="" onFocus="fctSetFocus()" class="inputNumber" onChange="fctChangeValeurDevisPose();"/></td>
                <td><input type="text" name="h.a_ml"    title="" onFocus="fctSetFocus()" class="inputNumber" onChange="fctChangeValeurDevisPose();"/></td>
                <td><input type="text" name="h.a_total" title="" onFocus="fctSetFocus()" class="inputNumber" readonly /></td>
                <td><input type="text" name="coefMarge" title="" onFocus="fctSetFocus()" class="inputNumber" onChange="fctChangeValeurDevisPose();"/></td>
                <td><input type="text" name="pxvente"   title="" onFocus="fctSetFocus()" class="inputNumber" readonly /></td>
                <td><span class="glyphicon glyphicon-trash" aria-hidden="true" onClick="fctSupprimeLignePose(XXX);" title="Supprimer la ligne" ></span></td>
            </tr>
        </table>
    </div>
    <input type="hidden" name="nbLignePose" id="nbLignePose" value="<?= count($this->itemsPose) ?>">
</div>
