<?php
/**
 * Created by PhpStorm.
 * User: alain
 * Date: 29/12/2017
 * Time: 11:12
 */
?>

<div id="panelFourniture" class="panel panel-primary">
    <div class="panel-heading nav navbar-default">
        <div class="row">
            <div class="col-md-6">
                <h3 class="panel-title" data-toggle="collapse" href="#collapsefourniture">Fournitures</h3>
            </div>
            <div class="col-md-6">
                <ul class="nav navbar-nav navbar-right navbarPanel">
                    <li id="BtAjoutligneFourniture" title="Ajouter une ligne">
                        <span class="glyphicon glyphicon-plus"></span>
                    </li>
                    <li id="BtSuprimeligneFourniture" title="Supprimer le bloc">
                        <span class="glyphicon glyphicon-remove"></span>
                    </li>
                </ul>
            </div>
        </div>
    </div>
    <div id="collapsefourniture" class="panel-body panel-collapse  <?php if(strrpos($this->fieldsCollapse, 'collapsefourniture') !== false) : ?> collapse <?php else: ?> in <?php endif;  ?>">
        <table class="table-produits-devis" id="tableFourniture">
            <tr>
                <th width="3%">Code</th>
                <th>Fourniture</th>
                <th width="3%">Quantité</th>
                <th width="7%">H.A M2/ML</th>
                <th width="7%">H.A Total</th>
                <th width="7%">Coef Marge</th>
                <th width="7%">Px vente</th>
                <th width="2%"></th>
            </tr>
            <?php if( count($this->itemsFourniture) == 0): ?>
            <tr id="ligneRefFourniture"  data-key="ligneRefFourniture_0">
                <td>
                    <input type="text" name="code"          data-indice="0" title="" onFocus="fctSetFocus();" onkeyup="fctRemplitListeFourniture(0);" onChange="fctChangeValeurDevisFourniture();" class="tableCode dropdown-toggle" list="listeFourniture_0"/>
                    <button type="button" class="btn btn-warning" aria-label="Left Align" onclick="fctOuvreCatalogue(0, 'Fourniture');">
                        <span class="glyphicon glyphicon-lamp" aria-hidden="true"></span>
                    </button>
                    <datalist id="listeFourniture_0">
                    </datalist>
                    <input type="hidden" name="json_Fourniture[]">
                </td>
                <td><input type="text" name="fourniture"    data-indice="0" title="" onFocus="fctSetFocus()" onChange="fctChangeValeurDevisFourniture();"/></td>
                <td><input type="text" name="qte"           data-indice="0" title="" onFocus="fctSetFocus()" class="inputNumber" onChange="fctChangeValeurDevisFourniture();"/></td>
                <td><input type="text" name="h.a_ml"        data-indice="0" title="" onFocus="fctSetFocus()" class="inputNumber" onChange="fctChangeValeurDevisFourniture();"/></td>
                <td><input type="text" name="h.a_total"     data-indice="0" title="" onFocus="fctSetFocus()" class="inputNumber" readonly /></td>
                <td><input type="text" name="coefMarge"     data-indice="0" title="" onFocus="fctSetFocus()" class="inputNumber" onChange="fctChangeValeurDevisFourniture();"/></td>
                <td><input type="text" name="pxvente"       data-indice="0" title="" onFocus="fctSetFocus()" class="inputNumber" readonly /></td>
                <td><span class="glyphicon glyphicon-trash" aria-hidden="true" onClick="fctSupprimeLigneFourniture(0);" title="Supprimer la ligne" ></span></td>
            </tr>
            <?php endif; ?>
            <?php if (isset($this->itemsFourniture)) : ?>
                <?php foreach($this->itemsFourniture as $key => $fourniture): ?>
                    <?php $json = json_decode($fourniture->json, true) ?>
                <tr id="ligneRefFourniture"  data-key="ligneRefFourniture_<?= $key ?>">
                    <td>
                        <input type="text" name="code"          data-indice="<?= $key ?>" title="" onFocus="fctSetFocus();" onkeyup="fctRemplitListeFourniture(<?= $key ?>);" onChange="fctChangeValeurDevisFourniture();" class="tableCode dropdown-toggle" list="listeFourniture_<?= $key ?>" value="<?= $json['code'] ?>"/>
                        <button type="button" class="btn btn-warning" aria-label="Left Align" onclick="fctOuvreCatalogue(<?= $key ?>, 'Fourniture');">
                            <span class="glyphicon glyphicon-lamp" aria-hidden="true"></span>
                        </button>
                        <datalist id="listeFourniture_<?= $key ?>">
                        </datalist>
                        <input type="hidden" name="json_Fourniture[]" value="<?= json_decode($json) ?>">
                    </td>
                    <td><input type="text" name="fourniture"    data-indice="<?= $key ?>" title="" onFocus="fctSetFocus()" onChange="fctChangeValeurDevisFourniture();" value="<?= $json['fourniture'] ?>"/></td>
                    <td><input type="text" name="qte"           data-indice="<?= $key ?>" title="" onFocus="fctSetFocus()" class="inputNumber" onChange="fctChangeValeurDevisFourniture();" value="<?= $json['qte'] ?>" /></td>
                    <td><input type="text" name="h.a_ml"        data-indice="<?= $key ?>" title="" onFocus="fctSetFocus()" class="inputNumber" onChange="fctChangeValeurDevisFourniture();" value="<?= $json['h.a_ml'] ?>"/></td>
                    <td><input type="text" name="h.a_total"     data-indice="<?= $key ?>" title="" onFocus="fctSetFocus()" class="inputNumber" readonly value="<?= $json['h.a_total'] ?>"/></td>
                    <td><input type="text" name="coefMarge"     data-indice="<?= $key ?>" title="" onFocus="fctSetFocus()" class="inputNumber" onChange="fctChangeValeurDevisFourniture();" value="<?= $json['coefmarge'] ?>"/></td>
                    <td><input type="text" name="pxvente"       data-indice="<?= $key ?>" title="" onFocus="fctSetFocus()" class="inputNumber" readonly value="<?= $json['pxvente'] ?>"/></td>
                    <td><span class="glyphicon glyphicon-trash" aria-hidden="true" onClick="fctSupprimeLigneFourniture(<?= $key ?>);" title="Supprimer la ligne" ></span></td>
                </tr>
                <?php endforeach; ?>
            <?php endif; ?>
            <tfoot>
                <tr>
                    <td colspan="7">
                        <table class="table-produits-devis">
                            <tr>
                                <td class="titrefooter haTotal">Total support</td>
                                <td class="titrefooter haTotal">H.A Total</td>
                                <td id="h_a_totauxFourniture" class="haTotal">&nbsp;</td>
                                <td class="titrefooter marge" >Marge</td>
                                <td id="margeFourniture" class="marge">&nbsp;</td>
                                <td class="titrefooter pxventeTotal">Px vente</td>
                                <td id="totalPxVenteFourniture" class="pxventeTotal" colspan="2">&nbsp;</td>
                            </tr>
                        </table>
                    </td>
                </tr>
            </tfoot>
        </table>
    </div>
    <div class="elemCache">
        <table>
            <tr id="elemCacheFourniture">
                <td>
                    <input type="text" name="code"          data-indice="XXX" title="" onFocus="fctSetFocus();" onkeyup="fctRemplitListeFourniture(XXX);" onChange="fctChangeValeurDevisFourniture();" class="tableCode dropdown-toggle" list="listeFourniture_XXX"/>
                    <button type="button" class="btn btn-warning" aria-label="Left Align" onclick="fctOuvreCatalogue(XXX, 'ForfaitPrestation');">
                        <span class="glyphicon glyphicon-lamp" aria-hidden="true"></span>
                    </button>
                    <datalist id="listeFourniture_XXX">
                    </datalist>
                    <input type="hidden" name="json_Fourniture[]">
                </td>
                <td><input type="text" name="fourniture"    data-indice="XXX" title="" onFocus="fctSetFocus()" onChange="fctChangeValeurDevisFourniture();" /></td>
                <td><input type="text" name="qte"           data-indice="XXX" title="" onFocus="fctSetFocus()" class="inputNumber" onChange="fctChangeValeurDevisFourniture();" /></td>
                <td><input type="text" name="h.a_ml"        data-indice="XXX" title="" onFocus="fctSetFocus()" class="inputNumber" onChange="fctChangeValeurDevisFourniture();" /></td>
                <td><input type="text" name="h.a_total"     data-indice="XXX" title="" onFocus="fctSetFocus()" class="inputNumber" readonly /></td>
                <td><input type="text" name="coefMarge"     data-indice="XXX" title="" onFocus="fctSetFocus()" class="inputNumber" onChange="fctChangeValeurDevisFourniture();" /></td>
                <td><input type="text" name="pxvente"       data-indice="XXX" title="" onFocus="fctSetFocus()" class="inputNumber" readonly /></td>
                <td><span class="glyphicon glyphicon-trash" aria-hidden="true" onClick="fctSupprimeLigneFourniture(XXX);" title="Supprimer la ligne" ></span></td>
            </tr>
        </table>
    </div>
    <input type="hidden" name="nbLigneFourniture" id="nbLigneFourniture" value="<?= count($this->itemsFourniture) ?>">
</div>