<?php
/**
 * Created by PhpStorm.
 * User: alain
 * Date: 29/12/2017
 * Time: 11:12
 */
?>

<div class="panel panel-primary">
    <div class="panel-heading">
        <h3 class="panel-title">Pose</h3>
    </div>
    <div class="panel-body">

        <button class="btn btn-primary" id="BtAjoutlignePose" >Ajouter une ligne</button>
        <button class="btn btn-primary" id="BtSuprimelignePose" >Supprimer une ligne</button>


        <table class="table-produits-devis" id="tablePose">
            <tr>
                <th>Code</th>
                <th>Pose</th>
                <th>Quantité</th>
                <th>H.A M2/ML</th>
                <th>H.A Total</th>
                <th>Coef Marge</th>
                <th>Px vente</th>
            </tr>
            <tr id="ligneRefPose">
                <td><input type="text" name="code"      title="" onFocus="fctSetFocus()" /></td>
                <td><input type="text" name="pose"      title="" onFocus="fctSetFocus()" /></td>
                <td><input type="text" name="qte"       title="" onFocus="fctSetFocus()" /></td>
                <td><input type="text" name="h.a_m2ml"  title="" onFocus="fctSetFocus()" /></td>
                <td><input type="text" name="h.a_total" title="" onFocus="fctSetFocus()" /></td>
                <td><input type="text" name="coefMarge" title="" onFocus="fctSetFocus()" /></td>
                <td><input type="text" name="pxVente"   title="" onFocus="fctSetFocus()" /></td>
            </tr>
            <tfoot>
            <tr>
                <td colspan="2">
                    <table class="table-produits-devis">
                        <tr>
                            <td>Total support</td>
                            <td>H.A Total</td>
                            <td>&nbsp;</td>
                            <td>&nbsp;</td>
                            <td>Marge</td>
                        </tr>
                    </table>
                </td>
                <td>&nbsp;</td>
                <td>&nbsp;</td>
                <td>Px vente</td>
                <td>&nbsp;</td>
                <td>&nbsp;</td>
            </tr>
            </tfoot>
        </table>

    </div>

    <div class="elemCache">
        <table>
            <tr id="elemCachePose">
                <td><input type="text" name="code"      title="" onFocus="fctSetFocus()" /></td>
                <td><input type="text" name="pose"      title="" onFocus="fctSetFocus()" /></td>
                <td><input type="text" name="qte"       title="" onFocus="fctSetFocus()" /></td>
                <td><input type="text" name="h.a_m2ml"  title="" onFocus="fctSetFocus()" /></td>
                <td><input type="text" name="h.a_total" title="" onFocus="fctSetFocus()" /></td>
                <td><input type="text" name="coefMarge" title="" onFocus="fctSetFocus()" /></td>
                <td><input type="text" name="pxVente"   title="" onFocus="fctSetFocus()" /></td>
            </tr>
        </table>
    </div>

</div>


</div>