<?php
/**
 * Created by PhpStorm.
 * User: alain
 * Date: 29/12/2017
 * Time: 11:12
 */
?>

<div class="panel panel-primary">
    <div class="panel-heading">
        <h3 class="panel-title">Fournitures</h3>
    </div>
    <div class="panel-body">
        <button type="button" id="BtAjoutligneFourniture" class="btn btn-default voffset1" title="Ajouter une ligne">
            <span class="glyphicon glyphicon-plus"></span>
        </button>
        <button type="button" id="BtSuprimeligneFourniture" class="btn btn-default voffset1" title="Supprimer une ligne">
            <span class="glyphicon glyphicon-minus"></span>
        </button>
        <table class="table-produits-devis" id="tableFourniture">
            <tr>
                <th>Code</th>
                <th>Fourniture</th>
                <th>Quantité</th>
                <th>H.A M2/ML</th>
                <th>H.A Total</th>
                <th>Coef Marge</th>
                <th>Px vente</th>
            </tr>
            <tr id="ligneRefFourniture">
                <td>
                    <input type="text" name="code"      title="" onFocus="fctSetFocus();" onkeyup="fctRemplitListeFourniture(0);" onChange="fctChangeValeurDevisFourniture();" class="dropdown-toggle" list="listeFourniture_0"/>
                    <datalist id="listeFourniture_0">
                    </datalist>
                </td>
                <td><input type="text" name="fourniture"    title="" onFocus="fctSetFocus()" onChange="fctChangeValeurDevisFourniture();" /></td>
                <td><input type="text" name="qte"           title="" onFocus="fctSetFocus()" onChange="fctChangeValeurDevisFourniture();" /></td>
                <td><input type="text" name="h.a_ml"        title="" onFocus="fctSetFocus()" onChange="fctChangeValeurDevisFourniture();" /></td>
                <td><input type="text" name="h.a_total"     title="" onFocus="fctSetFocus()" readonly /></td>
                <td><input type="text" name="coefMarge"     title="" onFocus="fctSetFocus()" onChange="fctChangeValeurDevisFourniture();" /></td>
                <td><input type="text" name="pxvente"       title="" onFocus="fctSetFocus()" readonly /></td>
            </tr>
            <tfoot>
                <tr>
                    <td colspan="7">
                        <table class="table-produits-devis">
                            <tr>
                                <td class="titrefooter haTotal">Total support</td>
                                <td class="titrefooter haTotal">H.A Total</td>
                                <td id="h_a_totauxFourniture" class="haTotal">&nbsp;</td>
                                <td class="titrefooter marge" >Marge</td>
                                <td id="margeFourniture" class="marge">&nbsp;</td>
                                <td class="titrefooter pxventeTotal">Px vente</td>
                                <td id="totalPxVenteFourniture" class="pxventeTotal" colspan="2">&nbsp;</td>
                            </tr>
                        </table>
                    </td>
                </tr>
            </tfoot>
        </table>
    </div>
    <div class="elemCache">
        <table>
            <tr id="elemCacheFourniture">
                <td>
                    <input type="text" name="code"      title="" onFocus="fctSetFocus();" onkeyup="fctRemplitListeFourniture(XXX);" onChange="fctChangeValeurDevisFourniture();" class="dropdown-toggle" list="listeFourniture_XXX"/>
                    <datalist id="listeFourniture_XXX">
                    </datalist>
                </td>
                <td><input type="text" name="fourniture"    title="" onFocus="fctSetFocus()" onChange="fctChangeValeurDevisFourniture();" /></td>
                <td><input type="text" name="qte"           title="" onFocus="fctSetFocus()" onChange="fctChangeValeurDevisFourniture();" /></td>
                <td><input type="text" name="h.a_ml"        title="" onFocus="fctSetFocus()" onChange="fctChangeValeurDevisFourniture();" /></td>
                <td><input type="text" name="h.a_total"     title="" onFocus="fctSetFocus()" readonly /></td>
                <td><input type="text" name="coefMarge"     title="" onFocus="fctSetFocus()" onChange="fctChangeValeurDevisFourniture();" /></td>
                <td><input type="text" name="pxvente"       title="" onFocus="fctSetFocus()" readonly /></td>
            </tr>
        </table>
    </div>
    <input type="hidden" name="nbLigneFourniture" id="nbLigneFourniture" value="1">
</div>