<?php
/**
 * Created by PhpStorm.
 * User: alain
 * Date: 29/12/2017
 * Time: 11:12
 */
?>

<div class="panel panel-primary">
    <div class="panel-heading">
        <h3 class="panel-title">Déplacements</h3>
    </div>
    <div class="panel-body">
        <button type="button" id="BtAjoutligneDeplacement" class="btn btn-default voffset1" title="Ajouter une ligne">
            <span class="glyphicon glyphicon-plus"></span>
        </button>
        <button type="button" id="BtSuprimeligneDeplacement" class="btn btn-default voffset1" title="Supprimer une ligne">
            <span class="glyphicon glyphicon-minus"></span>
        </button>
        <table class="table-produits-devis" id="tableDeplacement">
            <tr>
                <th>Code</th>
                <th>Deplacement</th>
                <th>Quantité</th>
                <th>Tarif unique</th>
                <th>Coût/jour</th>
                <th>Nb jours</th>
                <th>Px vente</th>
            </tr>
            <tr id="ligneRefDeplacement">
                <td><input type="text" name="code"          title="" onFocus="fctSetFocus()" onChange="fctChangeValeurDevisDeplacement();" ></td>
                <td><input type="text" name="deplacement"   title="" onFocus="fctSetFocus()" onChange="fctChangeValeurDevisDeplacement();" ></td>
                <td><input type="text" name="qte"           title="" onFocus="fctSetFocus()" onChange="fctChangeValeurDevisDeplacement();" ></td>
                <td><input type="text" name="tarifUnique"   title="" onFocus="fctSetFocus()" onChange="fctChangeValeurDevisDeplacement();" ></td>
                <td><input type="text" name="coutJour"      title="" onFocus="fctSetFocus()" readonly ></td>
                <td><input type="text" name="nbJours"       title="" onFocus="fctSetFocus()" onChange="fctChangeValeurDevisDeplacement();" ></td>
                <td><input type="text" name="pxvente"       title="" onFocus="fctSetFocus()" readonly /></td>
            </tr>
            <tfoot>
                <tr>
                    <td colspan="7">
                        <table class="table-produits-devis">
                            <tr>
                                <td class="titrefooter haTotal">Total support</td>
                                <td class="titrefooter haTotal">H.A Total</td>
                                <td id="h_a_totauxDeplacement" class="haTotal">&nbsp;</td>
                                <td class="titrefooter marge" >Marge</td>
                                <td id="margeDeplacement" class="marge">&nbsp;</td>
                                <td class="titrefooter pxventeTotal">Px vente</td>
                                <td id="totalPxVenteDeplacement" class="pxventeTotal" colspan="2">&nbsp;</td>
                            </tr>
                        </table>
                    </td>
                </tr>
            </tfoot>
        </table>
    </div>
    <div class="elemCache">
        <table>
            <tr id="elemCacheDeplacement">
                <td><input type="text" name="code"          title="" onFocus="fctSetFocus()" onChange="fctChangeValeurDevisDeplacement();" ></td>
                <td><input type="text" name="deplacement"   title="" onFocus="fctSetFocus()" onChange="fctChangeValeurDevisDeplacement();" ></td>
                <td><input type="text" name="qte"           title="" onFocus="fctSetFocus()" onChange="fctChangeValeurDevisDeplacement();" ></td>
                <td><input type="text" name="tarifUnique"   title="" onFocus="fctSetFocus()" onChange="fctChangeValeurDevisDeplacement();" ></td>
                <td><input type="text" name="coutJour"      title="" onFocus="fctSetFocus()" readonly ></td>
                <td><input type="text" name="nbJours"       title="" onFocus="fctSetFocus()" onChange="fctChangeValeurDevisDeplacement();" ></td>
                <td><input type="text" name="pxvente"       title="" onFocus="fctSetFocus()" readonly /></td>
            </tr>
        </table>
    </div>

</div>


</div>