<?php
/**
 * Created by PhpStorm.
 * User: alain
 * Date: 29/12/2017
 * Time: 11:12
 */
?>

<div class="panel panel-primary">
    <div class="panel-heading">
        <h3 class="panel-title">Sous-traitance</h3>
    </div>
    <div class="panel-body">
        <button type="button" id="BtAjoutligneSousTraitance" class="btn btn-default voffset1" title="Ajouter une ligne">
            <span class="glyphicon glyphicon-plus"></span>
        </button>
        <button type="button" id="BtSuprimeligneSousTraitance" class="btn btn-default voffset1" title="Supprimer une ligne">
            <span class="glyphicon glyphicon-minus"></span>
        </button>
        <table class="table-produits-devis" id="tableSousTraitance">
            <tr>
                <th>Code</th>
                <th>Sous traitance</th>
                <th>Quantité</th>
                <th>H.A M2/ML</th>
                <th>H.A Total</th>
                <th>Coef marge</th>
                <th>Px vente</th>
            </tr>
            <tr id="ligneRefSousTraitance">
                <td><input type="text" name="code"      title="" onFocus="fctSetFocus()" onChange="fctChangeValeurDevisSousTraitance();"/></td>
                <td><input type="text" name="support"   title="" onFocus="fctSetFocus()" onChange="fctChangeValeurDevisSousTraitance();"/></td>
                <td><input type="text" name="qte"       title="" onFocus="fctSetFocus()" onChange="fctChangeValeurDevisSousTraitance();"/></td>
                <td><input type="text" name="h.a_ml"    title="" onFocus="fctSetFocus()" onChange="fctChangeValeurDevisSousTraitance();"/></td>
                <td><input type="text" name="h.a_total" title="" onFocus="fctSetFocus()" readonly /></td>
                <td><input type="text" name="coefMarge" title="" onFocus="fctSetFocus()" onChange="fctChangeValeurDevisSousTraitance();"/></td>
                <td><input type="text" name="pxvente"   title="" onFocus="fctSetFocus()" readonly /></td>
            </tr>
            <tfoot>
                <tr>
                    <td colspan="8">
                        <table class="table-produits-devis">
                            <tr>
                                <td class="titrefooter haTotal">Total support</td>
                                <td class="titrefooter haTotal">H.A Total</td>
                                <td id="h_a_totauxSousTraitance" class="haTotal">&nbsp;</td>
                                <td class="titrefooter marge" >Marge</td>
                                <td id="margeSousTraitance" class="marge">&nbsp;</td>
                                <td class="titrefooter pxventeTotal">Px vente</td>
                                <td id="totalPxVenteSousTraitance" class="pxventeTotal" colspan="2">&nbsp;</td>
                            </tr>
                        </table>
                    </td>
                </tr>
            </tfoot>
        </table>
    </div>
    <div class="elemCache">
        <table>
            <tr id="elemCacheSousTraitance">
                <td><input type="text" name="code"      title="" onFocus="fctSetFocus()" onChange="fctChangeValeurDevisSousTraitance();" /></td>
                <td><input type="text" name="support"   title="" onFocus="fctSetFocus()" onChange="fctChangeValeurDevisSousTraitance();" /></td>
                <td><input type="text" name="qte"       title="" onFocus="fctSetFocus()" onChange="fctChangeValeurDevisSousTraitance();" /></td>
                <td><input type="text" name="h.a_ml"    title="" onFocus="fctSetFocus()" onChange="fctChangeValeurDevisSousTraitance();" /></td>
                <td><input type="text" name="h.a_total" title="" onFocus="fctSetFocus()" readonly /></td>
                <td><input type="text" name="coefMarge" title="" onFocus="fctSetFocus()" onChange="fctChangeValeurDevisSousTraitance();" /></td>
                <td><input type="text" name="pxvente"   title="" onFocus="fctSetFocus()" readonly /></td>
            </tr>
        </table>
    </div>
</div>