<?php
/**
 * Created by PhpStorm.
 * User: alain
 * Date: 29/12/2017
 * Time: 11:12
 */
?>

<div class="panel panel-primary">
    <div class="panel-heading">
        <h3 class="panel-title">Déplacements</h3>
    </div>
    <div class="panel-body">

        <button class="btn btn-primary" id="BtAjoutligneDeplacement" >Ajouter une ligne</button>
        <button class="btn btn-primary" id="BtSuprimeligneDeplacement" >Supprimer une ligne</button>


        <table class="table-produits-devis" id="tableDeplacement">
            <tr>
                <th>Code</th>
                <th>Deplacement</th>
                <th>Quantité</th>
                <th>Tarif unique</th>
                <th>Coût/jour</th>
                <th>Nb jours</th>
                <th>Px vente</th>
            </tr>
            <tr id="ligneRefDeplacement">
                <td><input type="text" name="code"          title="" onFocus="fctSetFocus()"/></td>
                <td><input type="text" name="Deplacement"   title="" onFocus="fctSetFocus()"/></td>
                <td><input type="text" name="qte"           title="" onFocus="fctSetFocus()"/></td>
                <td><input type="text" name="tarifUnique"   title="" onFocus="fctSetFocus()"/></td>
                <td><input type="text" name="coutJour"      title="" onFocus="fctSetFocus()"/></td>
                <td><input type="text" name="nbJours"       title="" onFocus="fctSetFocus()"/></td>
                <td><input type="text" name="pxVente"       title="" onFocus="fctSetFocus()"/></td>
            </tr>
            <tfoot>
            <tr>
                <td colspan="2">
                    <table class="table-produits-devis">
                        <tr>
                            <td>Total support</td>
                            <td>H.A Total</td>
                            <td>&nbsp;</td>
                            <td>&nbsp;</td>
                            <td>Marge</td>
                        </tr>
                    </table>
                </td>
                <td>&nbsp;</td>
                <td>&nbsp;</td>
                <td>Px vente</td>
                <td>&nbsp;</td>
                <td>&nbsp;</td>
            </tr>
            </tfoot>
        </table>

    </div>

    <div class="elemCache">
        <table>
            <tr id="elemCacheDeplacement">
                <td><input type="text" name="code"          title="" onFocus="fctSetFocus()"/></td>
                <td><input type="text" name="Deplacement"   title="" onFocus="fctSetFocus()"/></td>
                <td><input type="text" name="qte"           title="" onFocus="fctSetFocus()"/></td>
                <td><input type="text" name="tarifUnique"   title="" onFocus="fctSetFocus()"/></td>
                <td><input type="text" name="coutJour"      title="" onFocus="fctSetFocus()"/></td>
                <td><input type="text" name="nbJours"       title="" onFocus="fctSetFocus()"/></td>
                <td><input type="text" name="pxVente"       title="" onFocus="fctSetFocus()"/></td>
            </tr>
        </table>
    </div>

</div>


</div>