<?php
/**
 * Created by PhpStorm.
 * User: alain
 * Date: 29/12/2017
 * Time: 11:12
 */
?>

<div class="panel panel-primary">
    <div class="panel-heading">
        <h3 class="panel-title" data-toggle="collapse" href="#collapsefaconnages">Façonnages</h3>
    </div>
    <div id="collapsefaconnages" class="panel-body panel-collapse in">
        <button type="button" id="BtAjoutligneFaconnage" class="btn btn-default voffset1" title="Ajouter une ligne">
            <span class="glyphicon glyphicon-plus"></span>
        </button>
        <button type="button" id="BtSuprimeligneFaconnage" class="btn btn-default voffset1" title="Supprimer une ligne">
            <span class="glyphicon glyphicon-minus"></span>
        </button>
        <table class="table-produits-devis" id="tableFaconnage">
            <tr>
                <th class="txtEntete">Code</th>
                <th>Faconnage</th>
                <th class="txtEntete">Quantité</th>
                <th>H.A M2/ML</th>
                <th>H.A Total</th>
                <th>Px vente</th>
            </tr>
            <tr id="ligneRefFaconnage">
                <td>
                    <input type="text" name="code"      title="" onFocus="fctSetFocus();" onkeyup="fctRemplitListeFaconnage(0);" onChange="fctChangeValeurDevisFaconnage();" class="dropdown-toggle" list="listeFaconnage_0"/>
                    <datalist id="listeFaconnage_0">
                    </datalist>
                </td>
                <td><input type="text" name="faconnage" title="" onFocus="fctSetFocus()" onChange="fctChangeValeurDevisFaconnage();" /></td>
                <td><input type="text" name="qte"       title="" onFocus="fctSetFocus()" onChange="fctChangeValeurDevisFaconnage();" /></td>
                <td><input type="text" name="h.a_ml"    title="" onFocus="fctSetFocus()" onChange="fctChangeValeurDevisFaconnage();" /></td>
                <td><input type="text" name="h.a_total" title="" onFocus="fctSetFocus()" readonly /></td>
                <td><input type="text" name="pxvente"   title="" onFocus="fctSetFocus()" readonly /></td>
            </tr>
            <tfoot>
                <tr>
                    <td colspan="6">
                        <table class="table-produits-devis">
                            <tr>
                                <td class="titrefooter haTotal">Total support</td>
                                <td class="titrefooter haTotal">H.A Total</td>
                                <td id="h_a_totauxFaconnage" class="haTotal">&nbsp;</td>
                                <td class="titrefooter marge" >Marge</td>
                                <td id="margeFaconnage" class="marge">&nbsp;</td>
                                <td class="titrefooter pxventeTotal">Px vente</td>
                                <td id="totalPxVenteFaconnage" class="pxventeTotal" colspan="2">&nbsp;</td>
                            </tr>
                        </table>
                    </td>
                </tr>
            </tfoot>
        </table>
    </div>
    <div class="elemCache">
        <table>
            <tr id="elemCacheFaconnage">
                <td>
                    <input type="text" name="code"      title="" onFocus="fctSetFocus();" onkeyup="fctRemplitListeFaconnage(XXX);" onChange="fctChangeValeurDevisFaconnage();" class="dropdown-toggle" list="listeFaconnage_XXX"/>
                    <datalist id="listeFaconnage_XXX">
                    </datalist>
                </td>
                <td><input type="text" name="faconnage" title="" onFocus="fctSetFocus()" onChange="fctChangeValeurDevisFaconnage();" /></td>
                <td><input type="text" name="qte"       title="" onFocus="fctSetFocus()" onChange="fctChangeValeurDevisFaconnage();" /></td>
                <td><input type="text" name="h.a_ml"    title="" onFocus="fctSetFocus()" onChange="fctChangeValeurDevisFaconnage();" /></td>
                <td><input type="text" name="h.a_total" title="" onFocus="fctSetFocus()" readonly /></td>
                <td><input type="text" name="pxvente"   title="" onFocus="fctSetFocus()" readonly /></td>
            </tr>
        </table>
    </div>
    <input type="hidden" name="nbLigneFaconnage" id="nbLigneFaconnage" value="1">
</div>