<?php
/**
 * Created by PhpStorm.
 * User: alain
 * Date: 29/12/2017
 * Time: 11:12
 */
?>

<div id="panelForfaitPrestation" class="panel panel-primary">
    <div class="panel-heading nav navbar-default">
        <div class="row">
            <div class="col-md-6">
                <h3 class="panel-title" data-toggle="collapse" href="#collapseforfaitprestation">Forfait / Prestation</h3>
            </div>
            <div class="col-md-6">
                <ul class="nav navbar-nav navbar-right navbarPanel">
                    <li id="BtAjoutligneForfaitPrestation" title="Ajouter une ligne">
                        <span class="glyphicon glyphicon-plus"></span>
                    </li>
                    <li id="BtSuprimeligneForfaitPrestation" title="Supprimer le bloc">
                        <span class="glyphicon glyphicon-remove"></span>
                    </li>
                </ul>
            </div>
        </div>
    </div>
    <div id="collapseforfaitprestation" class="panel-body panel-collapse  <?php if(strrpos($this->fieldsCollapse, 'collapseforfaitprestation') !== false) : ?> collapse <?php else: ?> in <?php endif;  ?>">
        <table class="table-produits-devis" id="tableForfaitPrestation">
            <tr>
                <th width="3%">Code</th>
                <th>Presation</th>
                <th width="3%">Quantité</th>
                <th width="7%">Tarif</th>
                <th width="7%">Px vente</th>
                <th width="2%"></th>
            </tr>
            <?php if( count($this->itemsForfaitPrestation) == 0): ?>
            <tr id="ligneRefForfaitPrestation"  data-key="ligneRefForfaitPrestation_0">
                <td>
                    <input type="text" name="code"          data-indice="0" title="" onFocus="fctSetFocus();" onkeyup="fctRemplitListeForfaitPrestation(0);" onChange="fctChangeValeurDevisForfaitPrestation();" class="tableCode dropdown-toggle" list="listeForfaitPrestation_0"/>
                    <button type="button" class="btn btn-warning" aria-label="Left Align" onclick="fctOuvreCatalogue(0, 'ForfaitPrestation');">
                        <span class="glyphicon glyphicon-lamp" aria-hidden="true"></span>
                    </button>
                    <datalist id="listeForfaitPrestation_0">
                    </datalist>
                    <input type="hidden" name="json_ForfaitPrestation[]">
                </td>
                <td><input type="text" name="prestation"    data-indice="0" title="" onFocus="fctSetFocus()" onChange="fctChangeValeurDevisForfaitPrestation();"/></td>
                <td><input type="text" name="qte"           data-indice="0" title="" onFocus="fctSetFocus()" class="inputNumber" onChange="fctChangeValeurDevisForfaitPrestation();"/></td>
                <td><input type="text" name="tarif"         data-indice="0" title="" onFocus="fctSetFocus()" class="inputNumber" onChange="fctChangeValeurDevisForfaitPrestation();"/></td>
                <td><input type="text" name="pxvente"       data-indice="0" title="" onFocus="fctSetFocus()" class="inputNumber" readonly /></td>
                <td><span class="glyphicon glyphicon-trash" aria-hidden="true" onClick="fctSupprimeLigneForfaitPrestation(0);" title="Supprimer la ligne" ></span></td>
            </tr>
            <?php endif; ?>
            <?php if (isset($this->itemsForfaitPrestation)) : ?>
                <?php foreach($this->itemsForfaitPrestation as $key => $forfaitPresta): ?>
                    <?php $json = json_decode($forfaitPresta->json, true) ?>
                <tr id="ligneRefForfaitPrestation"  data-key="ligneRefForfaitPrestation_<?= $key ?>">
                    <td>
                        <input type="text" name="code"          data-indice="<?= $key ?>" title="" onFocus="fctSetFocus();" onkeyup="fctRemplitListeForfaitPrestation(<?= $key ?>);" onChange="fctChangeValeurDevisForfaitPrestation();" class="tableCode dropdown-toggle" list="listeForfaitPrestation_<?= $key ?>" value="<?= $json['code'] ?>"/>
                        <button type="button" class="btn btn-warning" aria-label="Left Align" onclick="fctOuvreCatalogue(<?= $key ?>, 'ForfaitPrestation');">
                            <span class="glyphicon glyphicon-lamp" aria-hidden="true"></span>
                        </button>
                        <datalist id="listeForfaitPrestation_<?= $key ?>">
                        </datalist>
                        <input type="hidden" name="json_ForfaitPrestation[]" value="<?= json_encode($json) ?>">
                    </td>
                    <td><input type="text" name="prestation"    data-indice="<?= $key ?>" title="" onFocus="fctSetFocus()" onChange="fctChangeValeurDevisForfaitPrestation();" value="<?= $json['prestation'] ?>"/></td>
                    <td><input type="text" name="qte"           data-indice="<?= $key ?>" title="" onFocus="fctSetFocus()" class="inputNumber" onChange="fctChangeValeurDevisForfaitPrestation();" value="<?= $json['qte'] ?>" /></td>
                    <td><input type="text" name="tarif"         data-indice="<?= $key ?>" title="" onFocus="fctSetFocus()" class="inputNumber" onChange="fctChangeValeurDevisForfaitPrestation();" value="<?= $json['tarif'] ?>"/></td>
                    <td><input type="text" name="pxvente"       data-indice="<?= $key ?>" title="" onFocus="fctSetFocus()" class="inputNumber" readonly value="<?= $json['pxvente'] ?>"/></td>
                    <td><span class="glyphicon glyphicon-trash" aria-hidden="true" onClick="fctSupprimeLigneForfaitPrestation(<?= $key ?>);" title="Supprimer la ligne" ></span></td>
                </tr>
                <?php endforeach; ?>
            <?php endif; ?>
            <tfoot>
                <tr>
                    <td colspan="8">
                        <table class="table-produits-devis">
                            <tr>
                                <td class="titrefooter haTotal">Total support</td>
                                <td class="titrefooter haTotal">H.A Total</td>
                                <td id="h_a_totauxForfaitPrestation" class="haTotal">&nbsp;</td>
                                <td class="titrefooter marge" >Marge</td>
                                <td id="margeForfaitPrestation" class="marge">&nbsp;</td>
                                <td class="titrefooter pxventeTotal">Px vente</td>
                                <td id="totalPxVenteForfaitPrestation" class="pxventeTotal" colspan="2">&nbsp;</td>
                            </tr>
                        </table>
                    </td>
                </tr>
            </tfoot>
        </table>
    </div>
    <div class="elemCache">
        <table>
            <tr id="elemCacheForfaitPrestation">
                <td>
                    <input type="text" name="code"          data-indice="XXX" title="" onFocus="fctSetFocus();" onkeyup="fctRemplitListeForfaitPrestation(XXX);" onChange="fctChangeValeurDevisForfaitPrestation();" class="tableCode dropdown-toggle" list="listeForfaitPrestation_XXX"/>
                    <button type="button" class="btn btn-warning" aria-label="Left Align" onclick="fctOuvreCatalogue(XXX, 'ForfaitPrestation');">
                        <span class="glyphicon glyphicon-lamp" aria-hidden="true"></span>
                    </button>
                    <datalist id="listeForfaitPrestation_XXX">
                    </datalist>
                    <input type="hidden" name="json_ForfaitPrestation[]">
                </td>
                <td><input type="text" name="prestation"    data-indice="XXX" title="" onFocus="fctSetFocus()" onChange="fctChangeValeurDevisForfaitPrestation();" /></td>
                <td><input type="text" name="qte"           data-indice="XXX" title="" onFocus="fctSetFocus()" class="inputNumber" onChange="fctChangeValeurDevisForfaitPrestation();" /></td>
                <td><input type="text" name="tarif"         data-indice="XXX" title="" onFocus="fctSetFocus()" class="inputNumber" onChange="fctChangeValeurDevisForfaitPrestation();" /></td>
                <td><input type="text" name="pxvente"       data-indice="XXX" title="" onFocus="fctSetFocus()" class="inputNumber" readonly /></td>
                <td><span class="glyphicon glyphicon-trash" aria-hidden="true" onClick="fctSupprimeLigneForfaitPrestation(XXX);" title="Supprimer la ligne" ></span></td>
            </tr>
        </table>
    </div>
    <input type="hidden" name="nbLigneForfaitPrestation" id="nbLigneForfaitPrestation" value="<?= count($this->itemsForfaitPrestation) ?>">
</div>