<?php
/**
 * Created by PhpStorm.
 * User: alain
 * Date: 29/12/2017
 * Time: 11:12
 */
?>

<div class="panel panel-primary">
    <div class="panel-heading">
        <h3 class="panel-title" data-toggle="collapse" href="#collapsefraistechniques">Frais Techniques</h3>
    </div>
    <div id="collapsefraistechniques" class="panel-body panel-collapse in">
        <button type="button" id="BtAjoutligneFraisTechnique" class="btn btn-default voffset1" title="Ajouter une ligne">
            <span class="glyphicon glyphicon-plus"></span>
        </button>
        <button type="button" id="BtSuprimeligneFraisTechnique" class="btn btn-default voffset1" title="Supprimer une ligne">
            <span class="glyphicon glyphicon-minus"></span>
        </button>
        <table class="table-produits-devis" id="tableFraisTechnique">
            <tr>
                <th class="txtEntete">Code</th>
                <th>Frais Techniques</th>
                <th>Taux</th>
                <th>Heures</th>
                <th>Minutes</th>
                <th>Tarif horaire</th>
                <th>Tarif minute</th>
                <th>Px vente</th>
            </tr>
            <?php if( count($this->itemsFraisTechniques) == 0): ?>
            <tr id="ligneRefFraisTechnique">
                <td>
                    <input type="text" name="code"      title="" onFocus="fctSetFocus();" onkeyup="fctRemplitListeFraisTechnique(0);" onChange="fctChangeValeurDevisFraisTechnique();" class="dropdown-toggle" list="listeFraisTechnique_0"/>
                    <datalist id="listeFraisTechnique_0">
                    </datalist>
                    <input type="hidden" name="json_FraisTechnique[]">
                </td>
                <td><input type="text" name="fraisTechnique"    title="" onFocus="fctSetFocus()" onChange="fctChangeValeurDevisFraisTechnique();" /></td>
                <td><input type="text" name="taux"              title="" onFocus="fctSetFocus()" onChange="fctChangeValeurDevisFraisTechnique();" /></td>
                <td><input type="text" name="heures"            title="" onFocus="fctSetFocus()" onChange="fctChangeValeurDevisFraisTechnique();" /></td>
                <td><input type="text" name="minutes"           title="" onFocus="fctSetFocus()" onChange="fctChangeValeurDevisFraisTechnique();" /></td>
                <td><input type="text" name="tarifHoraire"      title="" onFocus="fctSetFocus()" readonly /></td>
                <td><input type="text" name="tarifMinute"       title="" onFocus="fctSetFocus()" readonly /></td>
                <td><input type="text" name="pxvente"           title="" onFocus="fctSetFocus()" readonly /></td>
            </tr>
            <?php endif; ?>
            <?php foreach($this->itemsFraisTechniques as $key => $fraistechnique): ?>
                <?php $json = json_decode($fraistechnique->json, true) ?>
            <tr id="ligneRefFraisTechnique">
                <td>
                    <input type="text" name="code"      title="" onFocus="fctSetFocus();" onkeyup="fctRemplitListeFraisTechnique(<?= $key ?>);" onChange="fctChangeValeurDevisFraisTechnique();" class="dropdown-toggle" list="listeFraisTechnique_<?= $key ?>" value="<?= $json['code'] ?>"/>
                    <datalist id="listeFraisTechnique_<?= $key ?>">
                    </datalist>
                    <input type="hidden" name="json_FraisTechnique[]" value="<?= json_encode($json) ?>">
                </td>
                <td><input type="text" name="fraisTechnique"    title="" onFocus="fctSetFocus()" onChange="fctChangeValeurDevisFraisTechnique();" value="<?= $json['fraisTechnique'] ?>"/></td>
                <td><input type="text" name="taux"              title="" onFocus="fctSetFocus()" onChange="fctChangeValeurDevisFraisTechnique();" value="<?= $json['taux'] ?>"/></td>
                <td><input type="text" name="heures"            title="" onFocus="fctSetFocus()" onChange="fctChangeValeurDevisFraisTechnique();" value="<?= $json['heures'] ?>"/></td>
                <td><input type="text" name="minutes"           title="" onFocus="fctSetFocus()" onChange="fctChangeValeurDevisFraisTechnique();" value="<?= $json['minutes'] ?>"/></td>
                <td><input type="text" name="tarifHoraire"      title="" onFocus="fctSetFocus()" readonly value="<?= $json['tarifHoraire'] ?>"/></td>
                <td><input type="text" name="tarifMinute"       title="" onFocus="fctSetFocus()" readonly value="<?= $json['tarifMinute'] ?>"/></td>
                <td><input type="text" name="pxvente"           title="" onFocus="fctSetFocus()" readonly value="<?= $json['pxvente'] ?>"/></td>
            </tr>
            <?php endforeach; ?>
            <tfoot>
                <tr>
                    <td colspan="8">
                        <table class="table-produits-devis">
                            <tr>
                                <td class="titrefooter haTotal">Total support</td>
                                <td class="titrefooter haTotal">H.A Total</td>
                                <td id="h_a_totauxFraisTechnique" class="haTotal">&nbsp;</td>
                                <td class="titrefooter marge" >Marge</td>
                                <td id="margeFraisTechnique" class="marge">&nbsp;</td>
                                <td class="titrefooter pxventeTotal">Px vente</td>
                                <td id="totalPxVenteFraisTechnique" class="pxventeTotal" colspan="2">&nbsp;</td>
                            </tr>
                        </table>
                    </td>
                </tr>
            </tfoot>
        </table>
    </div>
    <div class="elemCache">
        <table>
            <tr id="elemCacheFraisTechnique">
                <td>
                    <input type="text" name="code"      title="" onFocus="fctSetFocus();" onkeyup="fctRemplitListeFraisTechnique(XXX);" onChange="fctChangeValeurDevisFraisTechnique();" class="dropdown-toggle" list="listeFraisTechnique_XXX"/>
                    <datalist id="listeFraisTechnique_XXX">
                    </datalist>
                    <input type="hidden" name="json_FraisTechnique[]">
                </td>
                <td><input type="text" name="fraisTechnique"    title="" onFocus="fctSetFocus()" onChange="fctChangeValeurDevisFraisTechnique();" /></td>
                <td><input type="text" name="taux"              title="" onFocus="fctSetFocus()" onChange="fctChangeValeurDevisFraisTechnique();" /></td>
                <td><input type="text" name="heures"            title="" onFocus="fctSetFocus()" onChange="fctChangeValeurDevisFraisTechnique();" /></td>
                <td><input type="text" name="minutes"           title="" onFocus="fctSetFocus()" onChange="fctChangeValeurDevisFraisTechnique();" /></td>
                <td><input type="text" name="tarifHoraire"      title="" onFocus="fctSetFocus()" readonly /></td>
                <td><input type="text" name="tarifMinute"       title="" onFocus="fctSetFocus()" readonly /></td>
                <td><input type="text" name="pxvente"           title="" onFocus="fctSetFocus()" readonly /></td>
            </tr>
        </table>
    </div>
    <input type="hidden" name="nbLigneFraisTechnique" id="nbLigneFraisTechnique" value="<?= count($this->itemsFraisTechniques)+1 ?>">
</div>