<?php
/**
 * Created by PhpStorm.
 * User: alain
 * Date: 29/12/2017
 * Time: 11:12
 */
?>

<div class="panel panel-primary">
    <div class="panel-heading">
        <h3 class="panel-title" data-toggle="collapse" href="#collapseforfaitprestation">Forfait / Prestation</h3>
    </div>
    <div id="collapseforfaitprestation" class="panel-body panel-collapse in">
        <button type="button" id="BtAjoutligneForfaitPrestation" class="btn btn-default voffset1" title="Ajouter une ligne">
            <span class="glyphicon glyphicon-plus"></span>
        </button>
        <button type="button" id="BtSuprimeligneForfaitPrestation" class="btn btn-default voffset1" title="Supprimer une ligne">
            <span class="glyphicon glyphicon-minus"></span>
        </button>
        <table class="table-produits-devis" id="tableForfaitPrestation">
            <tr>
                <th class="txtEntete">Code</th>
                <th>Presation</th>
                <th class="txtEntete">Quantité</th>
                <th>Tarif</th>
                <th>Px vente</th>
            </tr>
            <tr id="ligneRefForfaitPrestation">
                <td>
                    <input type="text" name="code"      title="" onFocus="fctSetFocus();" onkeyup="fctRemplitListeForfaitPrestation(0);" onChange="fctChangeValeurDevisForfaitPrestation();" class="dropdown-toggle" list="listeForfaitPrestation_0"/>
                    <datalist id="listeForfaitPrestation_0">
                    </datalist>
                </td>
                <td><input type="text" name="prestation"    title="" onFocus="fctSetFocus()" onChange="fctChangeValeurDevisForfaitPrestation();"/></td>
                <td><input type="text" name="qte"           title="" onFocus="fctSetFocus()" onChange="fctChangeValeurDevisForfaitPrestation();"/></td>
                <td><input type="text" name="tarif"         title="" onFocus="fctSetFocus()" onChange="fctChangeValeurDevisForfaitPrestation();"/></td>
                <td><input type="text" name="pxvente"       title="" onFocus="fctSetFocus()" readonly /></td>
            </tr>
            <tfoot>
                <tr>
                    <td colspan="8">
                        <table class="table-produits-devis">
                            <tr>
                                <td class="titrefooter haTotal">Total support</td>
                                <td class="titrefooter haTotal">H.A Total</td>
                                <td id="h_a_totauxForfaitPrestation" class="haTotal">&nbsp;</td>
                                <td class="titrefooter marge" >Marge</td>
                                <td id="margeForfaitPrestation" class="marge">&nbsp;</td>
                                <td class="titrefooter pxventeTotal">Px vente</td>
                                <td id="totalPxVenteForfaitPrestation" class="pxventeTotal" colspan="2">&nbsp;</td>
                            </tr>
                        </table>
                    </td>
                </tr>
            </tfoot>
        </table>
    </div>
    <div class="elemCache">
        <table>
            <tr id="elemCacheForfaitPrestation">
                <td>
                    <input type="text" name="code"      title="" onFocus="fctSetFocus();" onkeyup="fctRemplitListeForfaitPrestation(XXX);" onChange="fctChangeValeurDevisForfaitPrestation();" class="dropdown-toggle" list="listeForfaitPrestation_XXX"/>
                    <datalist id="listeForfaitPrestation_XXX">
                    </datalist>
                </td>
                <td><input type="text" name="prestation"    title="" onFocus="fctSetFocus()" onChange="fctChangeValeurDevisForfaitPrestation();" /></td>
                <td><input type="text" name="qte"           title="" onFocus="fctSetFocus()" onChange="fctChangeValeurDevisForfaitPrestation();" /></td>
                <td><input type="text" name="tarif"         title="" onFocus="fctSetFocus()" onChange="fctChangeValeurDevisForfaitPrestation();" /></td>
                <td><input type="text" name="pxvente"       title="" onFocus="fctSetFocus()" readonly /></td>
            </tr>
        </table>
    </div>
    <input type="hidden" name="nbLigneForfaitPrestation" id="nbLigneForfaitPrestation" value="1">
</div>