<?php
/**
 * Created by PhpStorm.
 * User: alain
 * Date: 29/12/2017
 * Time: 11:12
 */
?>

<div class="panel panel-primary">
    <div class="panel-heading">
        <h3 class="panel-title">Adhésifs</h3>
    </div>
    <div class="panel-body">

        <table class="table-produits-devis">
            <tr>

            </tr>
            <tr>

            </tr>
            <tfoot>
                <tr>

                </tr>
            </tfoot>
        </table>

    </div>
</div>