<?php
/**
 * Created by PhpStorm.
 * User: alain
 * Date: 29/12/2017
 * Time: 11:12
 */
?>

<div class="panel panel-primary">
    <div class="panel-heading nav navbar-default">
        <div class="row">
            <div class="col-md-6">
                <h3 class="panel-title" data-toggle="collapse" href="#collapsedeplacement">Déplacement</h3>
            </div>
            <div class="col-md-6">
                <ul class="nav navbar-nav navbar-right navbarPanel">
                    <li id="BtAjoutligneDeplacement" title="Ajouter une ligne">
                        <span class="glyphicon glyphicon-plus"></span>
                    </li>
                    <li id="BtSuprimeligneDeplacement" title="Supprimer une ligne">
                        <span class="glyphicon glyphicon-minus"></span>
                    </li>
                </ul>
            </div>
        </div>
    </div>
    <div id="collapsedeplacement" class="panel-body panel-collapse in">
       <table class="table-produits-devis" id="tableDeplacement">
            <tr>
                <th>Code</th>
                <th>Deplacement</th>
                <th>Quantité</th>
                <th>Tarif unique</th>
                <th>Coût/jour</th>
                <th>Nb jours</th>
                <th>Px vente</th>
            </tr>
            <?php if(count($this->itemsDeplacement) == 0): ?>
                <tr id="ligneRefDeplacement">
                    <td>
                        <input type="text" name="code"      title="" onFocus="fctSetFocus();" onkeyup="fctRemplitListeDeplacement(0);" onChange="fctChangeValeurDevisDeplacement();" class="dropdown-toggle" list="listeDeplacement_0"/>
                        <datalist id="listeDeplacement_0">
                        </datalist>
                        <input type="hidden" name="json_Deplacement[]">
                    </td>
                    <td><input type="text" name="deplacement"   title="" onFocus="fctSetFocus()" onChange="fctChangeValeurDevisDeplacement();" ></td>
                    <td><input type="text" name="qte"           title="" onFocus="fctSetFocus()" class="inputNumber" onChange="fctChangeValeurDevisDeplacement();" ></td>
                    <td><input type="text" name="tarifUnique"   title="" onFocus="fctSetFocus()" class="inputNumber" onChange="fctChangeValeurDevisDeplacement();" ></td>
                    <td><input type="text" name="coutJour"      title="" onFocus="fctSetFocus()" class="inputNumber" readonly ></td>
                    <td><input type="text" name="nbJours"       title="" onFocus="fctSetFocus()" class="inputNumber" onChange="fctChangeValeurDevisDeplacement();" ></td>
                    <td><input type="text" name="pxvente"       title="" onFocus="fctSetFocus()" class="inputNumber" readonly /></td>
                </tr>
            <?php endif; ?>
           <?php if (isset($this->itemsDeplacement)) : ?>
                <?php foreach($this->itemsDeplacement as $key => $deplacement): ?>
                    <?php $json = json_decode($deplacement->json, true) ?>
                <tr id="ligneRefDeplacement">
                    <td>
                        <input type="text" name="code"      title="" onFocus="fctSetFocus();" onkeyup="fctRemplitListeDeplacement(<?= $key ?>);" onChange="fctChangeValeurDevisDeplacement();" class="dropdown-toggle" list="listeDeplacement_<?= $key ?>" value="<?= $json['code'] ?>" />
                        <datalist id="listeDeplacement_<?= $key ?>">
                        </datalist>
                        <input type="hidden" name="json_Deplacement[]" value="<?= json_encode($json) ?>">
                    </td>
                    <td><input type="text" name="deplacement"   title="" onFocus="fctSetFocus()" onChange="fctChangeValeurDevisDeplacement();" value="<?= $json['deplacement'] ?>"></td>
                    <td><input type="text" name="qte"           title="" onFocus="fctSetFocus()" class="inputNumber" onChange="fctChangeValeurDevisDeplacement();" value="<?= $json['qte'] ?>"></td>
                    <td><input type="text" name="tarifUnique"   title="" onFocus="fctSetFocus()" class="inputNumber" onChange="fctChangeValeurDevisDeplacement();" value="<?= $json['tarifunique'] ?>"></td>
                    <td><input type="text" name="coutJour"      title="" onFocus="fctSetFocus()" class="inputNumber" readonly value="<?= $json['coutjour'] ?>"></td>
                    <td><input type="text" name="nbJours"       title="" onFocus="fctSetFocus()" class="inputNumber" onChange="fctChangeValeurDevisDeplacement();" value="<?= $json['nbjours'] ?>"></td>
                    <td><input type="text" name="pxvente"       title="" onFocus="fctSetFocus()" class="inputNumber" readonly value="<?= $json['pxvente'] ?>"/></td>
                </tr>
                <?php endforeach; ?>
           <?php endif; ?>
            <tfoot>
                <tr>
                    <td colspan="7">
                        <table class="table-produits-devis">
                            <tr>
                                <td class="titrefooter haTotal">Total support</td>
                                <td class="titrefooter haTotal">H.A Total</td>
                                <td id="h_a_totauxDeplacement" class="haTotal">&nbsp;</td>
                                <td class="titrefooter marge" >Marge</td>
                                <td id="margeDeplacement" class="marge">&nbsp;</td>
                                <td class="titrefooter pxventeTotal">Px vente</td>
                                <td id="totalPxVenteDeplacement" class="pxventeTotal" colspan="2">&nbsp;</td>
                            </tr>
                        </table>
                    </td>
                </tr>
            </tfoot>
        </table>
    </div>
    <div class="elemCache">
        <table>
            <tr id="elemCacheDeplacement">
                <td>
                    <input type="text" name="code"      title="" onFocus="fctSetFocus();" onkeyup="fctRemplitListeDeplacement(XXX);" onChange="fctChangeValeurDevisDeplacement();" class="dropdown-toggle" list="listeDeplacement_XXX"/>
                    <datalist id="listeDeplacement_XXX">
                    </datalist>
                    <input type="hidden" name="json_Deplacement[]">
                </td>
                <td><input type="text" name="deplacement"   title="" onFocus="fctSetFocus()" onChange="fctChangeValeurDevisDeplacement();" ></td>
                <td><input type="text" name="qte"           title="" onFocus="fctSetFocus()" class="inputNumber" onChange="fctChangeValeurDevisDeplacement();" ></td>
                <td><input type="text" name="tarifUnique"   title="" onFocus="fctSetFocus()" class="inputNumber" onChange="fctChangeValeurDevisDeplacement();" ></td>
                <td><input type="text" name="coutJour"      title="" onFocus="fctSetFocus()" class="inputNumber" readonly ></td>
                <td><input type="text" name="nbJours"       title="" onFocus="fctSetFocus()" class="inputNumber" onChange="fctChangeValeurDevisDeplacement();" ></td>
                <td><input type="text" name="pxvente"       title="" onFocus="fctSetFocus()" class="inputNumber" readonly /></td>
            </tr>
        </table>
    </div>
    <input type="hidden" name="nbLigneDeplacement" id="nbLigneDeplacement" value="<?= count($this->itemsDeplacement)+1 ?>">
</div>