<div class="panel panel-primary">
	<div class="panel-heading">
		<h3 class="panel-title">Messages reçus</h3>
	</div>
	<div class="panel-body">
		<div class="table-responvive">
			<table class="table table-hover table-condensed tablesorter" id="sorter">
				<thead>
					<tr>
						<th>Date</th>
						<th>Dossier</th>
						<th>Titre</th>
						<th>Auteur</th>
						<th>Vu le</th>
					</tr>
				</thead>
				<tbody>
					<?php foreach($this->receivedmessages as $message): ?>
						<tr>
							<td><?php echo date('d/m/Y', strtotime($message->date)) ?></td>
							<td><?php echo $message->dossier?></td>
							<td>
								<?php echo $message->titre ?>
							</td>
							<td><?php echo $this->GetUserById($message->id_user) ?></td>
							<td><?php echo $message->date_vu != '' ? date('d/m/Y', strtotime($message->date_vu)) : '' ?> - <?php echo $message->heure_vu?></td>
							<td style="text-align: right;">
								<a href="/messages/reponse/reponse/<?php echo $message->id_message ?>" class="btn btn-info">
									<span class="glyphicon glyphicon-share" aria-hidden="true"></span>
								</a>
								<a href="/messages/view/id/<?php echo $message->id_message ?>" class="btn btn-primary">
									<span class="glyphicon glyphicon-eye-open" aria-hidden="true"></span>
								</a>
								<a href="/messages/delete/id/<?php echo $message->id_message ?>" class="btn btn-danger sur">
									<span class="glyphicon glyphicon-trash" aria-hidden="true"></span>
								</a>
							</td>
						</tr>
					<?php endforeach; ?>
				</tbody>
			</table>
		</div>
	</div>
</div>
