<div class="panel panel-primary">
	<div class="panel-heading">
		<h3 class="panel-title">Messages envoy&eacute;s</h3>
	</div>
	<div class="panel-body">
		<div class="table-responvive">
			<table class="table table-hover table-condensed">
				<thead>
					<tr>
						<th>#</th>
						<th>Date</th>
						<th>Dossier</th>
						<th>Titre</th>
						<th>Destinataire</th>
						<th>Vu le</th>
						<th></th>
					</tr>
				</thead>
				<tbody>
					<tr>
					<?php foreach($this->sendmessages as $message): ?>
						<tr>
							<td></td>
							<td><?= date('d/m/Y', strtotime($message->date)) ?></td>
							<td><?= $message->dossier?></td>
							<td>
								<?= $message->titre ?>
							</td>
							<td><?= $message->id_destinataire != NULL ?$this->GetUserById($message->id_destinataire): 'Tout le monde' ?></td>
							<td><?= $message->date_vu != NULL ? date('d/m/Y', strtotime($message->date_vu)) : '' ?> - <?= $message->heure_vu?></td>
							<td>
								<a href="/messages/view/id/<?= $message->id_message ?>" class="btn btn-primary">
									<span class="glyphicon glyphicon-eye-open" aria-hidden="true"></span>
								</a>
							</td>
						</tr>
					<?php endforeach; ?>
					</tr>
				</tbody>
			</table>
		</div>
	</div>
</div>