<div class="panel panel-primary">
    <div class="panel-heading">
        <h3 class="panel-title">Liste des produits</h3>
    </div>
    <div class="panel-body">
        <div class="table-responvive">
            <table class="table table-hover table-condensed tablesorter" id="sorter">
                <thead>
                <tr>
                    <th style="width:10%">
                        Référence ME
                    </th>
                    <th>Fournisseur</th>
                    <th>Type</th>
                    <th style="width:8%">Epaisseur</th>
                    <th style="width:10%">Format</th>
                    <th style="width:35%">D&eacute;signation</th>
                    <th style="width:6%">P.U.</th>
                    <th>Unité</th>
                    <th>Coef</th>
                    <th></th>
                </tr>
                <tr>
                    <td>
                        <?= $this->filtreCatalogue->getElement('reference') ?>
                    </td>
                    <td>
                        <?= $this->filtreCatalogue->getElement('fournisseur') ?>
                    </td>
                    <td><?= $this->filtreCatalogue->getElement('type') ?></td>
                    <td><?= $this->filtreCatalogue->getElement('epaisseur') ?></td>
                    <td><?= $this->filtreCatalogue->getElement('format') ?></td>
                    <td>
                        <?= $this->filtreCatalogue->getElement('produit') ?>
                    </td>
                    <td colspan="4" style="text-align:right;">
                        <img src="/images/load.gif" alt="loader" id="loader"/>
                        <?= $this->filtreCatalogue->getElement('rechercher') ?>
                        <?= $this->filtreCatalogue->getElement('resetCatalogue') ?>
                    </td>
                </tr>
                </thead>
                <tbody id="liste_produits">
                <?php foreach($this->catalogues as $catalogue):?>
                    <tr>
                        <td><?= $catalogue->code_me?></td>
                        <td><?= $catalogue->fournisseur?></td>
                        <td><?= $catalogue->type?></td>
                        <td><?= $catalogue->epaisseur?></td>
                        <td><?= $catalogue->format?></td>
                        <td><?= $catalogue->designation ?></td>
                        <td style="text-align:right;">
                            <?php if(!(int) $catalogue->unitaire):?>
                                <?php if($catalogue->prixM2 == null):?>
                                    <?= $catalogue->prixML ?>
                                <?php else:?>
                                    <?= $catalogue->prixM2 ?>
                                <?php endif;?>
                            <?php else:?>
                                <?= $catalogue->unitaire ?>
                            <?php endif;?>
                            &nbsp;&euro;
                        </td>
                        <td style="text-align:center;">
                            <?php if(!(int) $catalogue->unitaire):?>
                                <?php if($catalogue->prixM2 == null):?>
                                    Ml
                                <?php else:?>
                                    M2
                                <?php endif;?>
                            <?php else:?>
                                Unitaire
                            <?php endif;?>
                        </td>
                        <td style="text-align:right;"><?= $catalogue->coeff_marge?></td>
                        <td style="text-align: right;">
                            <button type="button" class="btn btn-primary" aria-label="Left Align" id="fiche_catalogue_<?= $catalogue->id_produit?>">
                                <span class="glyphicon glyphicon-eye-open" aria-hidden="true"></span>
                            </button>
                            <button type="button" class="btn btn-warning" aria-label="Left Align" id="edit_catalogue_<?= $catalogue->id_produit?>">
                                <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>
                            </button>
                            <button type="button" class="btn btn-danger" aria-label="Left Align" id="delete_catalogue_<?= $catalogue->id_produit?>">
                                <span class="glyphicon glyphicon-trash" aria-hidden="true"></span>
                            </button>
                        </td>
                    </tr>
                <?php endforeach; ?>
                </tbody>
            </table>
        </div>
    </div>
</div>