<div class="panel panel-primary">
    <div class="panel-heading">
        <h3 class="panel-title">Liste des produits</h3>
    </div>
    <div class="panel-body">
        <div class="table-responvive">
            <table class="table table-hover table-condensed tablesorter" id="sorter">
                <thead>
                <tr>
                    <th>Code ME</th>
                    <th>Reférence</th>
                    <th>Désignation</th>
                    <th>Fournisseur</th>
                    <th></th>
                </tr>
                <form method="post">
                    <tr>
                    </tr>
                </form>
                </thead>
                <tbody id="listeProduits">
                <?php foreach($this->produits as $produit): ?>
                    <tr>
                        <td>
                            <?= $produit->code_me ?>
                        </td>
                        <td>
                            <?= $produit->reference ?>
                        </td>
                        <td>
                            <?= $produit->designation ?>
                        </td>
                        <td>
                            <?= $produit->fournisseur ?>
                        </td>
                        <td style="text-align: right;">
                            <button type="button" class="btn btn-primary" aria-label="Left Align" id="fiche_catalogue_<?= $produit->id_produit?>">
                                <span class="glyphicon glyphicon-eye-open" aria-hidden="true"></span>
                            </button>
                            <button type="button" class="btn btn-warning" aria-label="Left Align" id="edit_catalogue_<?= $produit->id_produit?>">
                                <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>
                            </button>
                            <button type="button" class="btn btn-danger" aria-label="Left Align" id="delete_catalogue_<?= $produit->id_produit?>">
                                <span class="glyphicon glyphicon-trash" aria-hidden="true"></span>
                            </button>
                        </td>
                    </tr>
                <?php endforeach; ?>
                </tbody>
            </table>
        </div>
    </div>
</div>