<?php echo $this->doctype() . PHP_EOL; ?>
<html xmlns="http://www.w3.org/1999/xhtml">
	<head>
		<title>Marne Enseigne</title>
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<?php
			echo $this->JQuery()->setVersion('1.11.2')->setUIVersion('1.11.4'), PHP_EOL;			
		?>
<!-- 		<link rel="stylesheet" href="/css/marneenseigne.css"> -->
		<link rel="stylesheet" type="text/css" href="/css/custom-theme/jquery-ui-1.10.0.custom.css"/>
		<!-- Latest compiled and minified CSS -->
		<link rel="stylesheet" href="/bootstrap/css/bootstrap.min.css">
		
		<!-- Optional theme -->
		<link rel="stylesheet" href="/bootstrap/css/bootstrap-theme.min.css">
		
		 <!--[if lt IE 9]>
            <link rel="stylesheet" type="text/css" href="css/custom-theme/jquery.ui.1.10.0.ie.css"/>
        <![endif]-->
		
		<!-- Latest compiled and minified JavaScript -->
		<script type="text/javascript" src="/bootstrap/js/bootstrap.min.js"></script>
		<script type="text/javascript" src="/js/tinymce/tinymce.min.js"></script>
		<script type="text/javascript" src="/js/tinymce/jquery.tinymce.min.js"></script>
		<script type="text/javascript" src="/js/scripts.js"></script>
		
		<style>
			.panel{
				border: 1px solid black;
			}
		</style>
	</head>
	<body>
		<div class="container-fluid">
			<div class="row-fluid">
				<div class="col-lg-12">
					<?php echo $this->layout()->content; ?>
				</div>
		</div>
	</body>
</html>

