<div class="row-fluid">
    <div class="col-lg-12">
        <div class="panel panel-primary">
            <div class="panel-heading">
                <h3 class="panel-title">Facture</h3>
            </div>
            <div class="panel-body">
                <div class="table-responvive">
                    <table class="table table-hover table-condensed tablesorter" id="sorter">
                        <thead style="display: contents; width:100%;">
                        <tr style="display: table-row;width: 100%;">
                            <th>Dossier</th>
                            <th>Date facture</th>
                            <th>Echéance</th>
                            <th>Client</th>
                            <th>Montant H.T.</th>
                            <th></th>
                        </tr>
                        </thead>
                        <tbody id="listeFactures">
                        <?php foreach($this->paginator as $dev): ?>
                            <tr id="devis_<?= $dev->id ?>" style="display: table-row;width: 100%;">
                                <td>
                                    <?= $dev->ref ?>
                                </td>
                                <td><?= date('d/m/Y', strtotime($dev->date_facture)) ?></td>
                                <td>
                                    <span style="color:<?= $this->GetFlagDate($dev->date_validite) ?>">&#x25A3;</span> &nbsp;&nbsp;
                                    <?= date('d/m/Y', strtotime($dev->date_paiement)) ?>
                                </td>
                                <td><?= $this->GetClientById($dev->id_client) ?></td>
                                <td><?= $this->GetSum($dev->id) ?></td>
                                <td style="text-align: right;">
                                    <button type="button" class="btn btn-primary" aria-label="Left Align" id="fiche_facturation_<?php echo $dev->id ?>">
                                        <span class="glyphicon glyphicon-eye-open" aria-hidden="true"></span>
                                    </button>
                                </td>
                            </tr>
                        <?php endforeach; ?>
                        </tbody>
                        <tfoot>
                        <tr style="display: table-row;width: 100%;">
                            <td colspan="6">
                                <?= $this->paginationControl($this->paginator); ?>
                            </td>
                        </tr>
                        </tfoot>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
