<div class="panel panel-primary">
	<div class="panel-heading">
		<h3 class="panel-title">Supprimer un utilisateur</h3>
	</div>
	<div class="panel-body">
		<div class="table-responvive">
			<table class="table table-hover table-condensed">
				<thead>
					<tr>
						<th>#</th>
						<th>Nom</th>
						<th>Login</th>
						<th>Status</th>
						<th></th>
					</tr>
				</thead>
				<tbody>
					<?php foreach($this->users as $user):?>
						<tr>
							<td></td>
							<td><?php echo $user->nom?></td>
							<td><?php echo $user->login?></td>
							<td><?php echo $user->status?></td>
							<td style="text-align: right;">
								<button type="button" class="btn btn-warning" aria-label="Left Align" id="edit_utilisateur_<?php echo $user->id_user ?>">
								  <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>
								</button>
								<button type="button" class="btn btn-danger" aria-label="Left Align" id="delete_utilisateur_<?php echo $user->id_user ?>">
								  <span class="glyphicon glyphicon-trash" aria-hidden="true"></span>
								</button>
							</td>
						</tr>
					<?php endforeach;?>
				</tbody>
			</table>
		</div>
	</div>
</div>