ALTER TABLE projetstaches ADD ( visible INT );

UPDATE projetstaches set visible = 1;

ALTER TABLE projets ADD ( colorclass varchar(10),
						  devisarelancer INT );

UPDATE projets set devisarelancer = 0;

-- --------------------------------------------------

CREATE TABLE PRODUIT (
  ID INT PRIMARY KEY,
  CODE_ME VARCHAR(20),
  NATURE VARCHAR(200),
  FORMAT VARCHAR(10),
  EPAISSEUR INT,
  SURFACE_TOTAL FLOAT,
  PRIX_M2 FLOAT,
  ID_TYPE_PRODUIT INT,
  ID_FOURNISSEUR INT,
  COEF_MARGE INT,
  NOTE VARCHAR(2000)
);

CREATE TABLE TYPE_PRODUIT (
  ID INT PRIMARY KEY,
  NOM VARCHAR(20)
);

CREATE TABLE FOURNISSEUR (
  ID INT PRIMARY KEY,
  CODE VARCHAR(20),
  NOM VARCHAR(200),

);

ALTER TABLE PRODUIT ADD CONSTRAINT FOREIGN KEY FK_IDFOURNISSEUR (ID_FOURNISSEUR) REFERENCES FOURNISSEUR (ID);
ALTER TABLE PRODUIT ADD CONSTRAINT FOREIGN KEY FK_IDTYPEPRODUIT (ID_TYPEPRODUIT) REFERENCES TYPE_PRODUIT (ID);
