<div id="plaletteCouleur" class="pickColor noDisplay" >
    <form action="" id="formPaletteColor" method="POST" >
        <input type="hidden" name="<?= $this->nom_name_pc ?>" id="<?= $this->nom_id_pc ?>" value="">

        <table class="pickColor">
            <tbody>
            <tr class="changeColor blue" data-origin="<?= $this->origin ?>">
                <td>&nbsp;</td>
            </tr>
            <tr class="changeColor lightBlue" data-origin="<?= $this->origin ?>">
                <td>&nbsp;</td>
            </tr>
            <tr class="changeColor green" data-origin="<?= $this->origin ?>">
                <td>&nbsp;</td>
            </tr>
            <tr class="changeColor lightgreen" data-origin="<?= $this->origin ?>">
                <td>&nbsp;</td>
            </tr>
            <tr class="changeColor orange" data-origin="<?= $this->origin ?>" >
                <td>&nbsp;</td>
            </tr>
            <tr class="changeColor darkorange" data-origin="<?= $this->origin ?>">
                <td>&nbsp;</td>
            </tr>
            <tr class="changeColor yellow" data-origin="<?= $this->origin ?>">
                <td>&nbsp;</td>
            </tr>
            <tr class="changeColor lemon" data-origin="<?= $this->origin ?>">
                <td>&nbsp;</td>
            </tr>
            <tr class="changeColor red" data-origin="<?= $this->origin ?>">
                <td>&nbsp;</td>
            </tr>
            <tr class="changeColor redVif" data-origin="<?= $this->origin ?>">
                <td>&nbsp;</td>
            </tr>
            <tr class="changeColor violet" data-origin="<?= $this->origin ?>">
                <td>&nbsp;</td>
            </tr>
            <tr class="changeColor gray" data-origin="<?= $this->origin ?>">
                <td>&nbsp;</td>
            </tr>
            <tr class="changeColor marron" data-origin="<?= $this->origin ?>" >
                <td>&nbsp;</td>
            </tr>
            <tr class="changeColor none" data-origin="<?= $this->origin ?>">
                <td>&nbsp;</td>
            </tr>
            </tbody>
        </table>

    </form>
</div>